### ISSUE TITLE
FreeMarker template error (DEBUG mode; use RETHROW in production!)

### ISSUE THREAD

**Issue by igorbljahhin** [Netflix/eureka#1000]
Suddenly our instance of Eureka gives this error message:

![image](https://user-images.githubusercontent.com/1252230/31772585-db180512-b4e8-11e7-842c-ac99034b3305.png)

Nothing was changed on our side. What should I do to fix this issue?

**Comment by igorbljahhin** [comment]
I discovered the source of the issue. It happened when I connected to same Eureka two instances of my app: one was deployed in Amazon and second was started locally on my computer.

**Comment by qiangdavidliu** [comment]
Hi @igorbljahhin it looks like you have resolved your own issue? Please reopen if you have any more questions. Thanks.

**Comment by manhdat107** [comment]
> I discovered the source of the issue. It happened when I connected to same Eureka two instances of my app: one was deployed in Amazon and second was started locally on my computer.

can You help me find a way to fix this issue? tks
