### ISSUE TITLE
do these kind of fallbacks make sense? - eurekaServer.port and port

### ISSUE THREAD

**Issue by odin-delrio** [Netflix/eureka#1004]
Hi,
I've been recently playing with eureka configs and I encountered myself searching for a strange error with the ports configuration... at the end of the day, it was my fault, I was using `eureka.port` instead of `eureka.eurekaServer.port` for telling my service where eureka server was listening.
The thing is that eureka has defined fallbacks for both ports to use the other one if one is missing...
does this makes sense? why if no eureka server port is defined the fallback is the service port?

https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/PropertyBasedClientConfigConstants.java#-L45-L46

![image](https://user-images.githubusercontent.com/9112748/31937115-cf623f5c-b8b3-11e7-9379-de73e3e7b1a5.png)

![image](https://user-images.githubusercontent.com/9112748/31937163-ec4be7bc-b8b3-11e7-9e93-7d6c413ae2a7.png)

I think that a proper error message will be more helpful...
Current behaviour allows projects with wrong config to luckily work if eureka and the service are listening on the same port... dealing in wrong assumptions to the developers.

what do you think?

**Comment by qiangdavidliu** [comment]
Hi @odin-delrio thank you for raising the issue. I believe these exists for backward compatibility reasons only. If you think a more clear message should be present, we'd love a PR. Thanks again.
