### ISSUE TITLE
Update REST docs for UP'ing an instance

### ISSUE THREAD

**Issue by jpedro** [Netflix/eureka#1005]
The REST docs (https://github.com/Netflix/eureka/wiki/Eureka-REST-operations) are wrong regarding UP'ing an instance.

They say use a `DELETE` method but should be a `PUT` instead:

```
Put instance back into service (remove override) | DELETE/eureka/v2/apps/appID/instanceID/status?value=UP (The value=UP is optional, it is used as a suggestion for the fallback status due to removal of the override)
```

**Comment by qiangdavidliu** [comment]
@jpedro the documentation is correct, however the wording is misleading. I have updated the documentation to "`Put` instance back into service". Thanks for the issue.
