### ISSUE TITLE
euraka-server dashboard not working

### ISSUE THREAD

**Issue by jimxu1982** [Netflix/eureka#1016]
<com.netflix.eureka.util.StatusInfo>
  <generalStats>
    <environment>test</environment>
    <num-of-cpus>4</num-of-cpus>
    <total-avail-memory>368mb</total-avail-memory>
    <current-memory-usage>203mb (55%)</current-memory-usage>
    <server-uptime>00:04</server-uptime>
  </generalStats>
  <applicationStats>
    <registered-replicas></registered-replicas>
    <available-replicas></available-replicas>
    <unavailable-replicas></unavailable-replicas>
  </applicationStats>
  <instanceInfo>
    <instanceId>XUZHIJING:eureka-server:8761</instanceId>
    <hostName>localhost</hostName>
    <app>EUREKA-SERVER</app>
    <ipAddr>10.118.86.189</ipAddr>
    <status>UP</status>
    <overriddenstatus>UNKNOWN</overriddenstatus>
    <port enabled="true">8761</port>
    <securePort enabled="false">443</securePort>
    <countryId>1</countryId>
    <dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
      <name>MyOwn</name>
    </dataCenterInfo>
    <leaseInfo>
      <renewalIntervalInSecs>30</renewalIntervalInSecs>
      <durationInSecs>90</durationInSecs>
      <registrationTimestamp>0</registrationTimestamp>
      <lastRenewalTimestamp>0</lastRenewalTimestamp>
      <evictionTimestamp>0</evictionTimestamp>
      <serviceUpTimestamp>0</serviceUpTimestamp>
    </leaseInfo>
    <metadata class="java.util.Collections$EmptyMap"/>
    <homePageUrl>http://localhost:8761/</homePageUrl>
    <statusPageUrl>http://localhost:8761/info</statusPageUrl>
    <healthCheckUrl>http://localhost:8761/health</healthCheckUrl>
    <vipAddress>eureka-server</vipAddress>
    <secureVipAddress>eureka-server</secureVipAddress>
    <isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
    <lastUpdatedTimestamp>1511512774606</lastUpdatedTimestamp>
    <lastDirtyTimestamp>1511512775037</lastDirtyTimestamp>
  </instanceInfo>
</com.netflix.eureka.util.StatusInfo>

**Comment by qiangdavidliu** [comment]
Hi, can you please add some additional details to describe your issue? Thanks
