### ISSUE TITLE
Clent Event listener from eureka server.

### ISSUE THREAD

**Issue by ex00** [Netflix/eureka#1027]
Hi.
I have issue: 
On eureka client site I have logic is related with some services. This logic have same actions for different services - get url to service from eureka and call rest endpoint a service.

And I would want to know about other new connected service to eureka server via events is coming from server. Is it possible?

**Comment by qiangdavidliu** [comment]
Hi @ex00 the java eureka client provides an event interface `eurekaClient.registerEventListener` that allows you to listen to eureka update events. Under the hood, the client/server communication is still poll based however.

**Comment by ex00** [comment]
Hi @qiangdavidliu 
Thanks for you reply! Do you talk about EurekaEvent?
I woluld like register listener for events about register new application in server. Wich implementation of EurekaEvent I could use for it?

**Comment by qiangdavidliu** [comment]
Hi, you might want to take a look at [CacheRefreshedEvent](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/CacheRefreshedEvent.java), which is generated each time the client receives an update. If you want to look into specifics however, you'll have to implement that logic when the event is triggered.

**Comment by ex00** [comment]
I changed logic of my application and this issue is not actual already. Thaks for help!
