### ISSUE TITLE
Broken link to 'EurekaServerConfig' section from 'Configuring Eureka' Wiki section

### ISSUE THREAD

**Issue by Victoremepunto** [Netflix/eureka#1032]
The link to EurekaServerConfig javadoc is broken, drops 404 => http://netflix.github.io/eureka/javadoc/eureka-core/com/netflix/eureka/EurekaServerConfig.html

The source link is in the main page of the section 'Configuring Eureka' of the Wiki.
 
I think is the same issue described in the already closed #775

**Comment by qiangdavidliu** [comment]
Hi @Victoremepunto we don't maintain the javadoc html for eureka at that url any more unfortunately. The javadocs are still present on the interface and I have updated the link from the wiki page to point to that.
