### ISSUE TITLE
probation list or vetting time for registering instances

### ISSUE THREAD

**Issue by SyCode7** [Netflix/eureka#1034]
Hi, I searched without success for a feature that permits Eureka server to add an instance to temporary network until the end of some dort of check e.g verification test. The idea is not to reject the request, assign the instance temporary metadata e.g. port, host that allows for inspection/verification while not yet registered. Instance may be registered if it passes those test and assigned to correct/productive metadata. 

I am experimenting with the setting the instance status as `STARTING `. for example 
`info.setStatus(com.netflix.appinfo.InstanceInfo.InstanceStatus.STARTING);`
Will there be a better solution ?

**Comment by qiangdavidliu** [comment]
@SyCode7 I'm not sure I 100% understand your request, but I don't think we have anything in mind to support your exact request. What we do with our server framework internally, is that all applications start up in the STARTING state, and once ready, their UP/DOWN status is tied to the application's healthcheck state. This should offer similar functionality to what you request I think?
