### ISSUE TITLE
Too many threads created for DiscoveryClient

### ISSUE THREAD

**Issue by fahimfarookme** [Netflix/eureka#1037]
We observed that too many threads created with the name `DiscoveryClient`. PFB the thread counts created for running around 27 microservice instances (eureka clients) in a managed server.

|Thread Name|Count|
|---|---|
|DiscoveryClient-%d | 84|
|DiscoveryClient-CacheRefreshExecutor-%d | 28|
|DiscoveryClient-HeartbeatExecutor-%d | 27|
|DiscoveryClient-InstanceInfoReplicator-%d | 27|

I have defined the `maximumPoolSize` for `HeartbeatExecutor` and `CacheRefreshExecutor` as 2, however they were created only 1 per microservice instance.

1. Even though the [pool size of DiscoveryClient scheduler is 2](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L373), it was always resulted in 3  DiscoveryClient threads per discovery client. I couldn't find any other reference to DiscoveryClient  executor as well.

2. From an initial analysis looks like it's possible to get rid of `DiscoveryClient` threads if `DiscoveryClient-CacheRefreshExecutor` and `DiscoveryClient-HeartbeatExecutor` are defined as `ScheduledThreadPoolExecutor` (rather than `ThreadPoolExecutor`). i.e. similar to the approach followed for `InstanceInfoReplicator`.

**Comment by sarbull** [comment]
+1

**Comment by qiangdavidliu** [comment]
@fahimfarookme thanks for the data, we will take a look at this.
