### ISSUE TITLE
spring cloud eureka change default status-page-url-path to /actuator/info?

### ISSUE THREAD

**Issue by dragontree101** [Netflix/eureka#1042]
in spring boot 2, actuator endpoint is `/actuator/info`, but default eureka default is
```
eureka:
  instance:
    status-page-url-path: /info
```

i think in spring cloud release in `Finchley` version, eureka should change default to `/actuator/info`, yestoday i have question to `spring-cloud` gitter.

**Comment by spencergibb** [comment]
Not the spring cloud Netflix repository

**Comment by dragontree101** [comment]
ok, i issue to spring cloud netfilx, close this issue
