### ISSUE TITLE
Spectator instead of Servo (deprecated) ?

### ISSUE THREAD

**Issue by ravikancherla** [Netflix/eureka#1046]
As Servo is deprecated and no longer maintained, any plan on using spectator instead of servo library ? I still see there are references to Servo in ThresholdLevelsMetric.java

I am not using Servo anyway. If there is a way to disable Servo instead, that works for me too. I am currently having a blocker due to the usage of Servo

https://github.com/Netflix/servo/issues/443

**Comment by qiangdavidliu** [comment]
@ravikancherla thanks for raising this issue. I followed your links and it looks like you have made a PR against servo that resolves this issue. Are you able to pin forward your servo version and achieve your goals?

We will look at updating the eureka dependency versions on servo to the latest soon.

(On the matter of moving to spectator, that is something we wanted to look at but unfortunately is not at the top of our priorities at the moment).
