### ISSUE TITLE
[Question] How does eureka client failover?

### ISSUE THREAD

**Issue by mengjiann** [Netflix/eureka#1047]
Referring to the "Eureka Failover" section in the page: https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2, it mentions that "eureka clients automatically failover to other nodes in the cluster."

And also in the "Assigning EIPs using Service Urls" section, it mentions "The Eureka clients similarly try to find a Eureka server co-located in the same zone and if they do not find any, they fail over to the Eureka servers in the other zones."

Just curious on how the eureka client is able to identify Eureka server located in the same zone? Is there another configuration for it? or it is done automatically internally?

**Comment by dougbacelar** [comment]
https://cloud.spring.io/spring-cloud-netflix/multi/multi__service_discovery_eureka_clients.html#_zones

**Comment by qiangdavidliu** [comment]
@mengjiann the eureka client implementation have an internal resolver concept where it reads data about the eureka servers (via the standard eureka api) which is then used for failovers. You can take a look at this class for the actual implementation:
https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/shared/transport/decorator/RetryableEurekaHttpClient.java

**Comment by mengjiann** [comment]
Thanks. I will read on the references.
