### ISSUE TITLE
Eureka and Zuul outdated

### ISSUE THREAD

**Issue by rashad-farajullayev** [Netflix/eureka#1048]
Spring Cloud uses Netflix API for Microservices architecture. Some people claim the Netflix tools are outdated and Netflix doesn't work on it any more. 

1. Rumors say Netflix is currently working on quite another alternative to replace at least Eureka and Zuul. Is that true? 
2. Should we currently switch to something else while it is not too late?
3. When will the new version be released approximately? 
4. Will new version be included in Spring Cloud? 
5. If we today go with these API staff do we have to worry about their deprecation in the coming years?

Thanks for attention

**Comment by brharrington** [comment]
I don't work on either and so may not have full context. At first glance these questions seem to pertain more to Zuul than Eureka.

> Rumors say Netflix is currently working on quite another alternative to replace at least Eureka and Zuul. Is that true?

I'm guessing this was in reference to the new version of Zuul. A 2.x version that was released a few months ago. There are some blog posts and presentations linked off the readme:

https://github.com/Netflix/zuul/blob/2.1/README.md

> Will new version be included in Spring Cloud?

For Zuul 2 specifically, see: Netflix/zuul#298.

**Comment by qiangdavidliu** [comment]
To comment on this specifically for eureka, we are not moving away or deprecating eureka any time soon. Internally, we do have some extensions (e.g. a readonly replica tier) that we use, but these are extensions and not replacements for the existing system.

The open source future for our internal extensions are as yet uncertain, however if there are any active movement on that front, we will involve Spring Cloud in the discussion.
