### ISSUE TITLE
the Domain Name Resolution is wrong, there will be get a extra “

### ISSUE THREAD

**Issue by wangwenyao** [Netflix/eureka#1049]
when i user useDnsForFetchingServiceUrls，i found the problem, the Domain Name Resolution is wrong, there will be get a extra “.  i think the problem of code is here.
`   
     String txtRecord = null;
        if (attr != null) {
            txtRecord = attr.get().toString();
        }

        Set<String> cnamesSet = new TreeSet<String>();
        if (txtRecord == null || txtRecord.trim().isEmpty()) {
            return cnamesSet;
        }
        String[] cnames = txtRecord.split(" ");
`

**Comment by wangwenyao** [comment]
![image](https://user-images.githubusercontent.com/19568152/38462848-c68b7f08-3b1f-11e8-9792-fd0b615425df.png)

**Comment by qiangdavidliu** [comment]
@wangwenyao I think your issue is similar to #1053. This has been resolved in merged PR #1054.
