### ISSUE TITLE
Eureka client registration fails when registering to a secure server

### ISSUE THREAD

**Issue by Bangic** [Netflix/eureka#1050]
I am using Spring Boot 2.0 and I have an Eureka server and and Eureka client. It is working fine. Here are the property files:

Server:

server.port=8082
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

Client:

server.port=8083
eureka.client.region = default
eureka.client.registryFetchIntervalSeconds = 5
eureka.client.serviceUrl.defaultZone=http://localhost:8082/eureka/

Now, I try to secure my Eureka server, I add the spring-boot-starter-security dependency and I change the property files:

Server:

server.port=8082

spring.security.basic.enabled=true
spring.security.user.name=eureka-user
spring.security.user.password=eureka-pass

eureka.instance.hostname=localhost

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
Client:

server.port=8083
eureka.client.region = default
eureka.client.registryFetchIntervalSeconds = 5
eureka.client.serviceUrl.defaultZone=http://eureka-user:eureka-pass@localhost:8082/eureka/
After these changes when I start the server and client the client throws this error:

com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/localhost:8083 - registration failed Cannot execute request on any known server

**Comment by spencergibb** [comment]
This is not the spring cloud Netflix issue tracker

**Comment by Bangic** [comment]
@beastovest thanks! it's works

**Comment by Bangic** [comment]
@spencergibb  thanks!

**Comment by Dhruvjava** [comment]
getting error while configure gateway with eureka in spring boot 3 and spring cloud 2022.0.3
DiscoveryClient_UNKNOWN/localhost: registering service..

**Comment by shivaprasadyanala** [comment]
I could about to login to to server with the credentials.
But when the client trying to register with the server with the credentials it is throwing 401
