### ISSUE TITLE
overriddenstatus changed to overriddenStatus breaks json parsing

### ISSUE THREAD

**Issue by ryanjbaxter** [Netflix/eureka#1051]
In Spring Cloud we give the option for Eureka clients to not use Jersey and instead use a Spring `RestTemplate` as their HTTP client.  We noticed that when this change is made and we use Eureka Server 1.8.7 that the client can no longer parse the JSON response into an `InstanceInfo` class.  The reason seems to be a change in the case of the `overriddenstatus` property to `overriddenStatus`.  The variable in `InstanceInfo` is still `overriddenstatus`.  Looks like the change was made in this commit https://github.com/Netflix/eureka/commit/939957124a8f055c7d343d67d0842ae06cf59530#diff-1e0de94c9faa44a518abe30d94744178L63

**Comment by ryanjbaxter** [comment]
The same problem does not show up when you look at the XML response

**Comment by qiangdavidliu** [comment]
@ryanjbaxter version 1.8.8 released with the fix.

**Comment by ryanjbaxter** [comment]
Awesome thanks, I will bump the version in Spring Cloud Netflix.

**Comment by dosdebug** [comment]
@ryanjbaxter Is this added in `Finchley.RC1`, because I am still facing issue with mentioned release.

**Comment by dosdebug** [comment]
Nevermind, `Finchley.RC1` still uses 1.8.8

**Comment by ryanjbaxter** [comment]
@qiangdavidliu We are using Eureka 1.9 but I can still reproduce this

**Comment by spencergibb** [comment]
Our non-jersey implementation doesn't use the Jackson codec do we still see the error
