### ISSUE TITLE
Dns resolver not compatible txt format "host1 host2 host3"

### ISSUE THREAD

**Issue by moxnet** [Netflix/eureka#1053]
https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2
if more than one hostname per zone, space delimit, for example txt value:

> "host1" "host2"

**but some dns provider only support:**
> "host1 host2"

and split the value by space to:
> ["\\"host1", "host2\\""]

then, make request to 
> http://"host1

so, got a exception:
> java.lang.IllegalArgumentException: Illegal character in authority at index 7: http://"eureka-2.eureka.springcloud.svc.cluster.local:8761/eureka

**Comment by qiangdavidliu** [comment]
Thanks @moxnet have merged in your PR.
