### ISSUE TITLE
 Virtual host like rabbitmq

### ISSUE THREAD

**Issue by zjh-coder** [Netflix/eureka#1055]
I have some experience on using rabbitmq and I'm a newer on eureka. I think one of its most interesting feature on rabbitmq is virtual host. With this feature, our team can share one mq server when developing on personal pc.
I think service discovery service like eureka is also a kind of middleware or infrastructure just like rabbitmq, so is it reasonable and possible to add this feature on eureka?

**Comment by qiangdavidliu** [comment]
@zjh-coder do you mean to add support for advertising rabbitmq brokers via eureka?
