### ISSUE TITLE
How do you forcefully refresh Eureka client cache?

### ISSUE THREAD

**Issue by vidurananayakkara** [Netflix/eureka#1063]
I have the requirement of refreshing the Eureka client cache forcefully. The reason for this is that,
Assuming I have a service registered to Eureka with name "A" and the "A"s information is outdated, I do not want to stay until Eureka automatically refreshes its cache.

How do I refresh the Eureka client cache forcefully?

**Comment by holy12345** [comment]
Hi @vidurananayakkara 
AFAIK Eureka have two cache, so which one you want refresh? In default eureka use two cache, one is `guava` cache the other is `Map`
In normal like this

```
Client --- > mapCache ---> guave cache
```
