### ISSUE TITLE
Not able to access the service through gateway

### ISSUE THREAD

**Issue by simion76** [Netflix/eureka#1065]
I have employee-service which is registered to Eureka Service (I can see that in Eureka page), I wnat to add load balancer using Zuul, but its not working, following are my application .yml files.

employee-service
*******************

spring:
  application:
    name: employee-service

server:
  port: 8301

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8300/eureka}
  instance:
    preferIpAddress: true
    

eureka-server
**************

spring:
  application:
    name: eureka-server

    
server:
  port: 8300
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      waitTimeInMsWhenSyncEmpty: 0
      maxThreadsForPeerReplication: 0 

gateway-server(Zuul Proxy)
*****************************
server:
  port: 8080

spring:
  application:
    name: zuul-server
    
eureka:
  client:
   serviceUrl:
    defaultZone: http://localhost:8300/eureka

zuul:
  prefix: /api
  routes:
    employee-service:
      path: /employee/**
      serviceId: employee-service

(In Zull proxy application.yml, STS shows "unknown property 'eureka')

Please let me know , whats wrong with this configuration

**Comment by spencergibb** [comment]
this is not the spring cloud netflix issue tracker
