### ISSUE TITLE
Instances currently registered with Eureka

### ISSUE THREAD

**Issue by jsntghf** [Netflix/eureka#1067]
The list of Instances currently registered with Eureka cant be refreshed, I started 3 instances, and showed me UP(3), and then stopped 1 instance, but always showed me UP(3), I hope it showed me UP(2), on developer environment, it is ok, on production environment, it is wrong, why?

**Comment by narenchoudhary** [comment]
When the number of instances are less, `eureka.server.renewalPercentThreshold` can cause this behavior. You have not provided your Eureka server and client configurations. 

Please provide configuration and check out [this ](https://github.com/spring-cloud/spring-cloud-netflix/issues/202)similar issue.

**Comment by qiangdavidliu** [comment]
Hi @jsntghf please see if this updated wiki document answers your question. Thanks.
https://github.com/Netflix/eureka/wiki/Server-Self-Preservation-Mode
