### ISSUE TITLE
not able to register eureka client with ip address 

### ISSUE THREAD

**Issue by vikrantch-hk** [Netflix/eureka#1068]
please let me know if there is any configuration for registering eureka client with IP instead of hostname. Like in case of spring boot we can use preferIpAddress: true and give ipAddress.

**Comment by narenchoudhary** [comment]
`eureka.instance.preferIpAddress=true` will make instance register to Eureka server with IP address. You do not need  to provide IP address in any configuration as that will be automatically picked up from system by the application.

**Comment by vikrantch-hk** [comment]
@narenchoudhary it works with Spring boot, is there any similar property for eureka-client in non spring boot applications

**Comment by narenchoudhary** [comment]
This configuration is not related to spring boot. Netflix OSS libraries (at least netflix-eureka) do not have any dependency on spring-boot.

[examples folder](https://github.com/Netflix/eureka/tree/master/eureka-examples) has an example project which does not use spring-boot.
[This SO question](https://stackoverflow.com/questions/35409492/eureka-service-discovery-without-spring-boot) is also very similar to your query.

**Comment by Sanisy** [comment]
you can do this by declearing your own custom config by extend the MyDataCenterInstanceConfig.
`DynamicPropertyFactory configInstance = com.netflix.config.DynamicPropertyFactory.getInstance();
        ApplicationInfoManager applicationInfoManager = initializeApplicationInfoManager(new CustomInstanceConfig ());
        EurekaClient eurekaClient = initializeEurekaClient(applicationInfoManager, new DefaultEurekaClientConfig());`
`public class CustomInstanceConfig extends MyDataCenterInstanceConfig{
	/**
     * prefer ip instant of hostname
     * @param refresh
     * @return
     */
    @Override
    public String getHostName(boolean refresh) {
        try {
            return InetAddress.getLocalHost().getHostAddress();
        } catch (UnknownHostException e) {
            return super.getHostName(refresh);
        }
    }
}`

**Comment by qiangdavidliu** [comment]
Thanks @narenchoudhary and @Sanisy for answering the question.
