### ISSUE TITLE
Wrong error handling in DiscoveryJerseyProvider.readFrom

### ISSUE THREAD

**Issue by mayras** [Netflix/eureka#1070]
This problem already exists long time and makes debugging as mess:

        try {
            return decoder.decode(inputStream, serializableClass);
        } catch (Throwable e) {
            if (e instanceof Error) { // See issue: https://github.com/Netflix/eureka/issues/72 on why we catch Error here.
                closeInputOnError(inputStream);
                throw new WebApplicationException(createErrorReply(500, e, mediaType));
            }
            LOGGER.debug("Cannot parse request body", e);
            throw new WebApplicationException(createErrorReply(400, "cannot parse request body", mediaType));
        }

This row "if (e instanceof Error) " makes a lot of problem, may be better handling?

**Comment by qiangdavidliu** [comment]
@mayras the reason this is done is documented at https://github.com/Netflix/eureka/issues/72 . That may no longer be a valid case, but would you mind commenting on what the issues you have seen with catching the Error here? Thanks.
