### ISSUE TITLE
Add some feature about dashboard

### ISSUE THREAD

**Issue by holy12345** [Netflix/eureka#1076]
This topic is not issue, I want to know can we add some button on the eureka dashboard. such as add a cancel button, if custome want removie from eureka server  Immediately。

**Comment by zhao41654828** [comment]
I have the same need...

add a remove button for micro service out of service.

**Comment by qiangdavidliu** [comment]
Hi @holy12345 this is not a feature we would need internally at Netflix (we use spinnaker for our needs), but we would be more than happy to support any PRs that add these features to the existing eureka dashboard.
