### ISSUE TITLE
Error in EurekaClientAutoConfiguration while running Eureka Server

### ISSUE THREAD

**Issue by RagavanRevature** [Netflix/eureka#1084]
Error creating bean with name 'org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.core.env.ConfigurableEnvironment' available: expected at least 1 bean which qualifies as autowire candidate. 
Spring Boot - 2.0.2
Cloud - Finchley.RC2

**Comment by spencergibb** [comment]
This is not the spring cloud Netflix issue tracker

**Comment by qiangdavidliu** [comment]
Thanks @spencergibb . Closing this issue.
