### ISSUE TITLE
New feature: get connected applications

### ISSUE THREAD

**Issue by jeromevdl** [Netflix/eureka#1086]
It would be a great feature to know who is connected to who. 

When a service retrieve information about another one (discovery, GET /apps/appid), it could be interesting to register this in order to know that the service is connected to the other. 

Thus, we could build the complete graph of service dependencies. Eureka have all the information, It would be a great pity not to take advantage of it.

I know this is not based on real connections (logs) but it would provide pretty good information for nothing.

What do you think ?

**Comment by qiangdavidliu** [comment]
It would be nice to have :).
