### ISSUE TITLE
1.X 持续更新么？

### ISSUE THREAD

**Issue by weir2010** [Netflix/eureka#1090]
1.X 持续更新么？

**Comment by neoremind** [comment]
1.X is pretty stable and in production-level, spring-cloud relies on 1.X. If there is demand I think community would play a big role in maintaining this. For your question, I think @qiangdavidliu might be the right person to answer.

**Comment by qiangdavidliu** [comment]
Hi. The 1.x branch of eureka still form the core of the service discovery ecosystem at Netflix and will continue to be maintained.
