### ISSUE TITLE
1.x Continue to update?

### ISSUE THREAD

**Issue by ThinOfSnowDance** [Netflix/eureka#1091]

**Comment by neoremind** [comment]
same concern. https://github.com/Netflix/eureka/issues/1090

**Comment by spencergibb** [comment]
Though I'm not part of netflix, I'm fairly confident eureka will live on for quite a while.

**Comment by neoremind** [comment]
@spencergibb thumb up!

**Comment by qiangdavidliu** [comment]
the 2.x work (on the 2.x branch) have been abandoned, but the 1.x branch of eureka still form the core of the service discovery ecosystem at Netflix and will continue to be maintained.

**Comment by icestari** [comment]
But now I'm confused about "extension work on eureka 1.x has moved internally within Netflix.".
