### ISSUE TITLE
com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server

### ISSUE THREAD

**Issue by jayzc1234** [Netflix/eureka#1094]
i do as "https://github.com/Netflix/eureka/wiki/Building-Eureka-Client-and-Server" told to do,but when i start tomct server and get a exception "Cannot execute request on any known server".but that demo guide page tells not to edit eureka-server.properties.so why is that?

**Comment by wayilau** [comment]
because your server is registering to other eureka server. you may config as below：
registerWithEureka: false
