### ISSUE TITLE
Stopping TimedSupervisorTasks

### ISSUE THREAD

**Issue by AlbertoImpl** [Netflix/eureka#1109]
Hi! We have a scenario where our Eureka server can be shut-down after some conditions. 
We still would like to leave the applications talking to the server up and running but it's causing on each client application several:
```
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT 2018-07-20 18:38:22.349 ERROR 15 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_GREETER-MESSAGES/greeter-messages-cs.apps.mydomain.com:[GUID] - was unable to send heartbeat!
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
   2018-07-20T11:38:22.35-0700 [APP/PROC/WEB/0] OUT     at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar!/:1.9.2
```
We were wondering if there is a way to disable the three `TimedSupervisorTask` or if is there any better way to stop retrying on the client side if the server is down.

If not, is there any recommendation you could give us to handle this situation?

Thanks!

**Comment by holy12345** [comment]
HI @AlbertoImpl 
Have you configured several eureka servers on your client side? I assume that your client configuration is as follows
```
defaultZone = eurekaServer1, eurekaServer2, eurekaServer3
```
In my mind if your shut-down `eurekaServer1` then client will sent heartbeat will failed, but client will auto choose next one(`eurekaServer2`)

Hope can help you 

Thanks

**Comment by AlbertoImpl** [comment]
Hi @holy12345 thanks for commenting.
However, we are not running it with multiple servers. 
We want to go from 1 working instance to 0 working instances avoiding the client apps to keep sending requests indefinitely when there are no working instances.

Thanks!

**Comment by holy12345** [comment]
Hi @AlbertoImpl 

In my mind there is no such mechanism, because the eureka client does not know whether the eureka server is down or the heartbeat fails due to network problems.

Your thoughts?

Thanks

**Comment by AlbertoImpl** [comment]
Hi @holy12345  thanks again.

For context:
We have a scenario where we have multiple client apps that intentionally can be connected to one eureka server that can be shut down.
Once that server is intentionally shut down, client apps keep sending the requests every couple of seconds and failing with the exception posted before.

What about having a max-retry that defaults to 0 been keeping the same default retry-forever functionality and be able to configure that number for having a more fine-grained retry policy?

Wondering if that makes sense, and if it does, if it's the `DiscoveryClient` responsibility or if it should be a different handling in the `RetryableEurekaHttpClient`

Thanks

**Comment by holy12345** [comment]
Hi @qiangdavidliu  : )

Could you please give some suggestion?

**Comment by qiangdavidliu** [comment]
Hi @AlbertoImpl @holy12345 from an architectural pov, eureka is designed so that eureka servers being down is considered a disaster scenario. Having clients that can potentially stop trying to re-register is not an expected part of eureka client/server interaction.

@AlbertoImpl is your use case here purely driven by the logs generated? If so, they can be turned of via the necessary log4j log level configuration.

**Comment by holy12345** [comment]
@qiangdavidliu  Thanks : )

**Comment by AlbertoImpl** [comment]
Hi @qiangdavidliu thanks for responding!
It isn't because of the logs.
Imagine the eureka-server is secured and it goes down. Now our client app has to go and authenticate once a while trying to reach nothing.

However, if eureka is doing it so by design. I completely understand.

Thanks!
