### ISSUE TITLE
De-register application instance problem

### ISSUE THREAD

**Issue by yangpancode** [Netflix/eureka#1110]
i use the Eureka REST operations to De-register application instance, De-register successfully ！ but in a few seconds, the Eureka client instance re-register soon. how to prent the client instance re-register. because some times we want to find the client instance problem, do not want restart the  client instance soon.
use DELETE /eureka/v2/apps/appID/instanceID REST operations.

**Comment by mgtriffid** [comment]
@yangpancode , even if you DELETE instance from Eureka via REST API, your instance still continues to send heartbeats, and when server receives heartbeat for instance it does not know about, server registers it. I'd suggest to set status OUT_OF_SERVICE instead DELETE, if you just want to stop routing traffic to problematic instance.
