### ISSUE TITLE
[Question] Reading metadata from recently closed instance

### ISSUE THREAD

**Issue by hashstax** [Netflix/eureka#1117]
I need to read metadata from recently closed instance (e.g. I'd like evictTask to trigger propagation of the metadata before instance is cancelled). Is there a good way to do so?

**Comment by mgtriffid** [comment]
@hashstax, I'm not sure if this fit your needs, but as you probably know, clients fetch apps/delta to renew local registry, and in particular they return removed instances with `<actionType>DELETED</actionType>`. Try to experiment with this.
