### ISSUE TITLE
Get InstanceInfo with StatusChangeEvent

### ISSUE THREAD

**Issue by michael-pratt** [Netflix/eureka#1118]
Using Eureka Client, is it possible to get full instance information when a change occurs? Right now the `StatusChangeEvent` only sends current and previous instance status, but as far as I can tell there is no way to correlate that back to the actual instance that changed. I have to query the client again for my application and manually sort what has changed.

Would it be possible to create a new listener interface that passes the old and new `InstanceInfo` objects whenever a status change occurs?

**Comment by qiangdavidliu** [comment]
@michael-pratt you are correct that the current implementation does not offer what you ask out of the box. We welcome community contributions if you would like to provide a PR for your functionality.
