### ISSUE TITLE
Eureka status refresh problem

### ISSUE THREAD

**Issue by rickywu** [Netflix/eureka#1121]
I enabled pause, restart, shutdown for endpoints 

When I post to pause for resume for service, the status refresh immediately in Eureka home page 
But the status keep for seconds in /eureka/apps/app-id, 

status changed in home page:
![image](https://user-images.githubusercontent.com/442398/45369887-882eb480-b619-11e8-8159-2e836f1edc0c.png)

but rest api result not changed and will be refreshed in about 5 seconds automatically
![image](https://user-images.githubusercontent.com/442398/45369873-7a792f00-b619-11e8-84e3-af45a59113ad.png)

How can I keep them always as the same, I use SprintBoot 1.5.9

**Comment by rickywu** [comment]
OK, so I have to wait for seconds till cache refreshed?

**Comment by qiangdavidliu** [comment]
@rickywu @mgtriffid is correct. Information propagation through eureka is eventual consistent (up to 30s max latency by default).
