### ISSUE TITLE
on my platform,service run in docker and can register in Eureka but cant found it cause docker ip.

### ISSUE THREAD

**Issue by iver3on** [Netflix/eureka#1123]
every service has its own domain name ,how can I register my service in Eureka by domain name 

or other solutions?
Help?

**Comment by iver3on** [comment]
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekacenter.witcloud.huawei.com/eureka/
  instance:
    hostname: http://xxxx.xxx..com
    instance-id: http://xxxx.xxx.com

not working

**Comment by thinker8581** [comment]
using prefer-ip-address: false, then try again.
