### ISSUE TITLE
[DiscoveryClient-0] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out  java.util.concurrent.TimeoutException: null

### ISSUE THREAD

**Issue by rajgoothy** [Netflix/eureka#1128]
-- spring boot version is 1.5.10 and cloud version is edgware-SR2

2018-10-08 16:44:00.039  INFO [gpbs-api-gateway,,,] 11908 --- [AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2018-10-08 16:47:42.782 ERROR [gpbs-api-gateway,,,] 11908 --- [DiscoveryClient-0] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205) [na:1.8.0]
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:63) ~[eureka-client-1.7.0.jar:1.7.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]

**Comment by rajgoothy** [comment]
can any body help us..

**Comment by mgtriffid** [comment]
@rajgoothy , not enough information here. Could you provide all your eureka-related configuration parameters?

**Comment by rajgoothy** [comment]
Ok.. will provide here ...

**Comment by rajgoothy** [comment]
-- api gate way of application.yml
spring:
  application:
    name: gpbs-api-gateway

logging:
  level:
    root: INFO
    org:
      springframework:
       web: INFO
      hibernate: INFO
      apache: ERROR
  path:  C:/gpbs_logs/
  file: C:/gpbs_logs/gpbs-api-gateway.log    
  
#spring.cloud.config.fail-fast=true
server:
  port: 8760
  tomcat:
    max-threads: 20

    
eureka: 
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://127.0.0.1:9000/eureka
      healthcheck: 
        enabled: true
  instance:
    leaseExpirationDurationInSeconds: 30000000
    leaseRenewalIntervalInSeconds: 300000
    preferIpAddress: true
  #fetchRegistry: true

==================

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.annotation.Bean;

import com.scb.gpbs.filter.GpbsLoggingFilter;

@SpringBootApplication
@EnableZuulProxy
@EnableEurekaClient
public class ApiGatewayApplication {

	public static void main(String[] args) {
		SpringApplication.run(GpbsApiGatewayApplication.class, args);
	}
	
	@Bean
	public GpbsLoggingFilter simpleFilter() {
	    return new GpbsLoggingFilter();
	  }

}

=======

My Proxy interface: 

import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.cloud.netflix.ribbon.RibbonClient;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import com.scb.gpbs.json.vo.ProductMapVO;

@FeignClient(name="gpbs-api-gateway")
@RibbonClient(name="gpbs-rules-service")
public interface GpbsRulesServiceProxy {
	
	@PostMapping(value = "/gpbs-rules-service/gpbs/v1/product",produces="application/json",consumes="application/json")
	public String  getProduct(@RequestBody ProductMapVO productMapVO);
		
	@PostMapping(value = "/gpbs-rules-service/gpbs/v1/product2",produces="application/json",consumes="application/json")
	public String  getProduct2(@RequestBody ProductMapVO productMapVO);
	
	@GetMapping(value = "/gpbs-rules-service/test")
	public String test();
	
	
		

}
zull MS pom.xml:
==============

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Edgware.SR2</spring-cloud.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>
		
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-sleuth</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
		</dependency>
		

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.16.22</version>
		</dependency>
	</dependencies>
	

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by rajgoothy** [comment]
@mgtriffid,

I have provided all the details . Please verify and suggest.

**Comment by mgtriffid** [comment]
@rajgoothy , all I can suggest is to assure that your Eureka server is actually running on 127.0.0.1:9000. Please consider asking Spring Cloud developers, they may know more about your setup.

**Comment by rajgoothy** [comment]
@mgtriffid , Thanks for the update and suggestion.. 

is any body able to verify this?

**Comment by qiangdavidliu** [comment]
Thanks @mgtriffid . @rajgoothy Spring Cloud Netflix would be the best place to ask Spring Cloud integration specific question. As a general comment, issues to do with the TimedSupervisorTask tasks are typically caused by initialization issues (e.g. bad start up config etc) and not typically related to the actual TimedSupervisorTask itself (which are just periodic background tasks that the eureka-client executes).
