### ISSUE TITLE
React on Spot Instance interruption notifications

### ISSUE THREAD

**Issue by krutsko** [Netflix/eureka#1131]
If Spot Instance is marked for termination , then this termination info will be available in ec2 instance metadata.
More info at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html#spot-instance-termination-notices

Eureka Client should be able to check EC2 instance metadata and publish termination info to Eureka Client metadata. So, the interested parties could react accordinantly.

**Comment by krutsko** [comment]
PR #1132

**Comment by qiangdavidliu** [comment]
Closing in favour or PR.

**Comment by krutsko** [comment]
@qiangdavidliu It will be great to have this released sooner than later. Thanks!
