### ISSUE TITLE
Can I add extra fields to eureka dashboard?

### ISSUE THREAD

**Issue by jishamenon2207** [Netflix/eureka#1133]
I understand I can add extra parameters as part of the metadataMap of instance for any eureka client. Is it possible for me to modify/ tweak the eureka dashboard so that it displays these extra parameters also on the dashboard.

Basically is there any way I can edit the existing eureka dashboard to show some user defined variables for each of the eureka client I onboard?

**Comment by holy12345** [comment]
Hi @jishamenon2207 

I think is issues has same request #1076 
So far there is no way can edit the eureka dashboard : ( but if you will you can submit a PR : )

thanks

**Comment by qiangdavidliu** [comment]
Thanks @holy12345. @jishamenon2207 we are happy to look at any PRs that can improve on the usability of eureka.

**Comment by jishamenon2207** [comment]
@qiangdavidliu @holy12345 : Would love to try it out. Do you have any guidance for me? 😄

**Comment by qiangdavidliu** [comment]
@jishamenon2207 The eureka dashboard code is super old, you can find them here:
https://github.com/Netflix/eureka/tree/master/eureka-resources/src/main/resources/jsp
