### ISSUE TITLE
replicas still unavailable  bug,  server.content-path  is deprecated!!

### ISSUE THREAD

**Issue by leonayx123** [Netflix/eureka#1136]
When I configured spring boot, I found it always failed.

Control interface prompt "unavailable-replicas ".

When I read the source code, I found a bug here.

The org.springframework.cloud.net flix. Eureka. EurekaClientAutoConfiguration 125 lines.

`
String serverContextPath = this.env.getproperty (" server.content-path ", "/");`

**"Server.content-path"** is outdated code

The latest spring-boot context configuration is **"server.servlet.content-path"**

This configuration item affects the default address such as healthCheckUrl.

HealthCheckUrl address will use context-path but is '/'  , 

so even if I configured 'server.servlet.content-path'.

eureka will still not be able to get client heartbeats.

please fix it ~

**Comment by mgtriffid** [comment]
Anyway, please try to ask in [Spring Cloud](https://github.com/spring-cloud/spring-cloud-netflix) project. Spring brings many new variables to the equation. This Github project is specifically for Eureka, and what you are using is some integration made by Spring Cloud developers. So, they very likely know more about your question.

**Comment by leonayx123** [comment]
> Anyway, please try to ask in [Spring Cloud](https://github.com/spring-cloud/spring-cloud-netflix) project. Spring brings many new variables to the equation. This Github project is specifically for Eureka, and what you are using is some integration made by Spring Cloud developers. So, they very likely know more about your question.

Ok, thanks for your patient reply

**Comment by troshko111** [comment]
Thanks @mgtriffid
