### ISSUE TITLE
How many Euraka-Server instances deployed in a cluster?What's the best number,2 or 3 or ....?

### ISSUE THREAD

**Issue by andyzhaozhao** [Netflix/eureka#1142]
like this: https://github.com/spring-cloud/spring-cloud-netflix/issues/3222

**Comment by holy12345** [comment]
HI @andyzhaozhao 

You say you have 21 clients so in my experience you can start 3 eureka server(One Eureka server obviously not reasonable)

For you question whats the BEST number I think maybe no accurate answer.

@qiangdavidliu  Any thoughts?

**Comment by qiangdavidliu** [comment]
Eureka does not do paxos style consensus, so there is no need to deploy at odd numbers. Having said that, I would recommend 3+ servers as a general rule of thumb. The reason being eureka server deployments will often bring you under par (i.e. to 2 available when running 3).
