### ISSUE TITLE
ServiceUrlRandomizer based on hostname may lead to uneven distribution of clients

### ISSUE THREAD

**Issue by mgtriffid** [Netflix/eureka#1149]
Back in 2013 (here 3767d56efbabc8cf5e26fc442c7b008c841bbf19) randomizer for list of available Eureka nodes was introduced. And in this implementation reordering service URLs in fact depends on host name.
This implementation is still the only one present in Eureka client. However, if number of services per host is big, but number of hosts is not, it leads to uneven distribution of load on Eureka. For example, if there are some big hosts running numerous Docker containers.

Hence, 3 questions:
1) Why does this implementation depends on host name, why not just use random seed calculated once?
2) If reason is hard to find since the implementation is 5yo, would you mind if we support random seed?
3) And if you don't mind that we support random seed, do you want us to leave hostname-dependent implementation as default one and add config parameter to enable random-based, or we may just replace hostname-dependent one with random-based?

Thanks!

**Comment by pparth** [comment]
Any comment here guys?

**Comment by elandau** [comment]
@mgtriffid From your description it sounds like you are need a different randomization mechanisms for clients to find fetch or registration eureka nodes.  Or do you need different randomization for eureka nodes to find each other?  Or both?  The PR you submitted only modified the behavior for inter node communication of the eureka cluster and has no effect on client side randomization.  That change would need to be wired into ZoneAffinityClusterResolver.

**Comment by mgtriffid** [comment]
@elandau , we need different randomization for clients to choose Eureka nodes. And actually with my changes if I do
```java
        ResolverUtils.setRandomizer(new Randomizer() {
            private final int seed = new Random().nextInt();
            @Override
            public void randomize(List randomList) {
                if (randomList.size() < 2) {
                    return;
                }
                Random random = new Random(seed);
                int last = randomList.size() - 1;
                for (int i = 0; i < last; i++) {
                    int pos = random.nextInt(randomList.size() - i);
                    if (pos != i) {
                        Collections.swap(randomList, i, pos);
                    }
                }
            }
        });
```
somewhere before Eureka Guice module is configured, this does the trick for me: seed is different every time, but order of preference remains the same. This implementation of `Randomizer` just uses random number instead of local IP hashcode.

> That change would need to be wired into ZoneAffinityClusterResolver.

As you can see, `ZoneAffinityClusterResovler` just calls `ResolverUtils.randomize`, so logic is actually wired into there.

Am I missing something else?

**Comment by elandau** [comment]
Sorry, you are correct.  Not sure why I wasn't making that connection.

**Comment by pparth** [comment]
Anything new about this guys? Are we ok to proceed with the PRs we submitted?
