### ISSUE TITLE
Eureka REST operation CORS(Cross-origin resource sharing)

### ISSUE THREAD

**Issue by xcbeyond** [Netflix/eureka#1159]
When other systems call the Eureka Rest api，it will Cross-domain access problem。Is there any good way，except the modified Eureka Rest api interface.

**Comment by halower** [comment]
i met, too.  version >2.0

**Comment by brharrington** [comment]
Most servlet containers have CORS filters you can use (see for example [Tomcat](https://tomcat.apache.org/tomcat-9.0-doc/config/filter.html#CORS_Filter) and [Jetty](https://www.eclipse.org/jetty/documentation/9.4.x/cross-origin-filter.html) filters). So if you need that functionality you should be able to enable it.

**Comment by xcbeyond** [comment]
@halower @brharrington thank you.I rewrite rest api to call the rest api directly.

**Comment by EffNox** [comment]
Insert this in your main class:
-------------------------------

	public @Bean FilterRegistrationBean<?> corsFilter() {
		UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
		CorsConfiguration config = new CorsConfiguration();
		config.setAllowCredentials(true);
		config.addAllowedOrigin("http://localhost:4200");
		config.addAllowedMethod("*");
		config.addAllowedHeader("Accept");
		source.registerCorsConfiguration("/**", config);
		FilterRegistrationBean<Filter> bean = new FilterRegistrationBean<Filter>(new CorsFilter(source));
		bean.setOrder(Ordered.HIGHEST_PRECEDENCE);
		return bean;
	}

Full example: https://github.com/EffNox/spring_eureka-rest-operations-angular
