### ISSUE TITLE
Manual instance registration with EurekaHttpClient

### ISSUE THREAD

**Issue by stovocor** [Netflix/eureka#1161]
I am trying to register application instances manually using the Eureka Client (version 1.9.3):

```
EurekaHttpClient registrationClient = new RestTemplateEurekaHttpClient(new RestTemplate(), "http://localhost:8080/eureka");
InstanceInfo instanceInfo = InstanceInfo.Builder.newBuilder()
[...]
.build();
registrationClient.register(instanceInfo);
```

The result is an HTTP error (400) because of a `MismatchedInputException`: `Root name 'instanceId' does not match expected ('instance') for type [simple type, class com.netflix.appinfo.InstanceInfo]`

It seems that the generated JSON does not contain a root "instance" field. Am I using the API correctly or is there another way for manual instance registration? The Eureka server is running in version 2.0.2.

**Comment by O70** [comment]
Have you solved your problem?

**Comment by O70** [comment]
You can try the following:

```java
final String serviceUrl = "http://localhost:8762/eureka/";

TransportClientFactory factory = new RestTemplateTransportClientFactory();
EurekaEndpoint defaultEndpoint = new DefaultEndpoint(serviceUrl);
EurekaHttpClient eurekaHttpClient = factory.newClient(defaultEndpoint);

InstanceInfo info = InstanceInfo.Builder.newBuilder()
        [...]
        .build();

eurekaHttpClient.register(info);
```

**Comment by longfeiXie** [comment]
Hello, have you solved the problem?

**Comment by stovocor** [comment]
Sorry for the late response. The suggested code works perfectly, thank you.

**Comment by softreaver** [comment]
I still have HTTP Error 400 using the given solution

**Comment by troshko111** [comment]
> @softreaver I still have HTTP Error 400 using the given solution

It's likely something different, please open a separate issue in this case and provide the relevant details (minimal repro).

**Comment by ettorezamponi** [comment]
I'm trying to register my Maven/Jakarta EE app with this method but it doesn't work.. 
The micro service based app is the [TeaStore](https://github.com/DescartesResearch/TeaStore/tree/master), application for testing and benchmark.
Anyone can help me?
