### ISSUE TITLE
Mem raised after I call api everytime.

### ISSUE THREAD

**Issue by zhaodageng** [Netflix/eureka#1165]
current-memory-usage | 74mb (7%)
will increase every time after you call the api http://ip:port/eureka/apps

**Comment by mgtriffid** [comment]
Well, I can't say this is surprising - Eureka allocates objects when you call this API, but most are supposed to be collected by GC. Does memory utilization continue to grow steadily even after garbage collection? In other words, do you experience a memory leak? Also please let us know what's the version you are using.
