### ISSUE TITLE
Configuration of Eureka Server in Eureka Client on AWS ECS

### ISSUE THREAD

**Issue by dersteve** [Netflix/eureka#1166]
How do you address the Eureka Server on AWS ECS?

My requirements/current setup:
- Eureka Server Deployed as ECS Service with Launch Type EC2
-- Service Discovery (from ECS) enabled, which creates a Route53 DNS entry for the Eureka Server (e.g. eureka.local)
- Eureka Server is only for mid-tier Services, hence no external address of Eureka Server needed/wanted
- Eureka Server deployed in multiple AZs in one region
- Eureka Client needs to configure (address) the Eureka Server somehow

**Addressing via DNS from Route53:** 
When I set the `eurekaServerDNSName: service-registry.local` like this, then I get the following exception, because it can't find the txt record for the DNS entry. Is there a way to create the TXT record also and if yes, how shall I set this for ECS Service Discovery?

Exception:
`
Caused by: java.lang.RuntimeException: Failed to initialize DiscoveryClient!
`

`
ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'eurekaAutoServiceRegistration'; nested exception is java.lang.NullPointerException
`

`
c.n.d.s.r.aws.ConfigClusterResolver : Resolving eureka endpoints via DNS: txt.eu-west-1.service-registry.local
`

In addition when I want to create the txt record in Route53 for my services, I get the error message that I can't actually change this record, like "The resource hostedzone/yyy can only be managed through servicediscovery.amazonaws.com". So I wonder how I could use DNS configuration with AWS ECS for Eureka configuration.

**Elastic IPs as an alternative**
Since Elastic IPs (EIP) expose a public IP this is no possible solution for us.

**Comment by HieronymusLex** [comment]
@dersteve did you manage to find a solution to this?

I tried without ECS Service Discovery since it creates only SRV or A records. Instead I associated a private hosted zone with the VPC and had a subset of private IP addresses dedicated for the instances Eureka is being launched on (bridge mode being used in ECS), then I have a separate process which keeps the txt records up to date with these private IPs. was running into issues with hostname mismatches in the containers

**Comment by dersteve** [comment]
@HieronymusLex No, I actually didn't manage to do it. We were thinking about a solution along your lines, but were a bit afraid of all the necessary stuff. We are now close to finish a version where we don't use Eureka on ECS. 

Instead we use a private hosted zone and a A-Record for each service so we can address a service in a resttemplate with its name, e.g. "customer" (as we did with Eureka/Ribbon/LoadBalanced Resttemplate before) and have the A-Record in the private zone pointed to a ALB that distributes the load between the service instances.

**Comment by carlosbpf** [comment]
@HieronymusLex and @troshko111 I have the same problem. Is there a way to properly setup the dns discovery?

**Comment by bsushant-athena** [comment]
I'm trying to register a service with eureka which is using ecs service discovery(instead of using ribbon). Is SRV record supported by eureka?

**Comment by troshko111** [comment]
No, the SRV records aren't implemented.
