### ISSUE TITLE
How do I More instance to App ？

### ISSUE THREAD

**Issue by pkwenda** [Netflix/eureka#1168]
We company some features want use Eureka instead of zookeeper , I check out this WIKI:[Eureka REST operations](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations), I do packaging Eureka-client , but only has register instanceId REST , And I get an error when I keep AppId and replace InstanceId. how to add instances into App's REST ? It should be exit ！
because：

![image](https://user-images.githubusercontent.com/14212375/50760492-f4a58180-12a2-11e9-9583-82cdd9fbf7e9.png)

It is Array like zookeeper ！ How do I register multiple instances？Now, i only can register one instance into one App。

![image](https://user-images.githubusercontent.com/14212375/50761610-cbd2bb80-12a5-11e9-934c-67e327e8d368.png)

I register like this.

**Comment by troshko111** [comment]
Have each instance of the app register with Eureka and it will be merged server-side and all will be addressable.
