### ISSUE TITLE
Rest endpoint /eureka/apps/delta is not returning delta correctly 

### ISSUE THREAD

**Issue by piyushkumar13** [Netflix/eureka#1173]
I am updating the eureka metadata with key `weight` and `some value` using endpoint `/eureka/apps/${app-name}/${app-id}/metadata?weight=40`. I am calling this update metadata api **once** for each of my registered service instances(eureka client registered with eureka) in a **loop**(registered instances are two and it can be more). Simultaneously, I am hitting the endpoint `/eureka/apps/delta` but this endpoint sometimes returning the response with the updates I have done using update metadata api and sometimes its not.  <br/>
Just to re-verify my above result, I have deployed zuul application, registered it with eureka and customized the Ribbon configuration- getting the **servers from loadbalancers** and **from returned server fetching InstanceInfo** object and printing **InstanceInfo.getMetadata** . This also sometimes giving the correct updated metadata and sometimes not.

**Note** : I am using Spring cloud version `Edgware.SR4`. 

Have a look at this snapshot Response of /eureka/apps/delta after update metadata call

<img width="1332" alt="screen shot 2019-01-15 at 10 06 08 pm" src="https://user-images.githubusercontent.com/13505531/51197849-9e76b500-1918-11e9-896e-759d6b5b5e46.png">

**Comment by piyushkumar13** [comment]
Any updates on this ??

**Comment by piyushkumar13** [comment]
@qiangdavidliu @tbak could you please provide ome help on this.

**Comment by piyushkumar13** [comment]
Thanks @qiangdavidliu

**Comment by troshko111** [comment]
Thanks for the report, it'd be helpful if you could come up with a minimal repro, not sure what the problem you're facing may be.

**Comment by piyushkumar13** [comment]
I was able to resolve the issue by using diabling delta : `disableDelta: true` .  Thought, it might be helpful for someone else.
**A word of caution** : disabling delta will increase the traffic b/w eureka clients and eureka server.
