### ISSUE TITLE
Allow 'immediate' registerRuntimeMetadata instead of waiting for the next heartbeat

### ISSUE THREAD

**Issue by entonio** [Netflix/eureka#1176]
My understanding is that changes made by a client to its InstanceInfo (namely, the metadata) are only sent to the server in the next heartbeat. With a default heartbeat of 30s, that will be, on average, 15s after they are made.

This is fine for most of my metadata, but for some of it - that changes very rarely - I'd really want the changes to be as immediate as possible. They wouldn't have to be immediate, but preferably within an interval of 5 seconds or less, which is much sooner than the average heartbeat.

Reducing the heartbeat interval is not only against the advice, as it's also overkill for what I want, since the changes that do need immediate updates are very rare. So I thought of 2 possibilities:

1. Having a high-frequency thread to check if updates have to be sent, and send them f the next heartbeat is still far away. That would require callers to *not* request updates if they aren't high priority (I currently have a thread periodically requesting those 'lesser priority' updates).
2. Add a `boolean immediately` to `registerRuntimeMetadata` according to which the update is really performed at call time.

Option 2 seems pretty unobtrusive to me, but I'm unsure if this feature fits your philosophy at all, or if it doesn't do the same breakage that is said to be an issue with small interval heartbeats. I'd add that all I'd need would be a 'best effort' thing to provide some functionality, rather than some flawless, edgecaseless, wonder.

**Comment by troshko111** [comment]
Thanks for describing the use case. The proposed solutions do not seem like a perfect design fit into a naturally eventually consistent model of Eureka as there's no "immediate" anywhere anyway and the underlying replication may be delayed even if you heartbeat more often. Based on the info provided it'd say we're unlikely to implement this / merge a PR.

The use case seems to be trying to utilize Eureka as a config store which it isn't, if that's the case I suggest trying ZooKeeper, etcd or similar.

Hope this makes sense.
