### ISSUE TITLE
Ereka 1.9.8 Renews threshold is correct for the first time, and then this value will automatically grow, resulting in automatic opening of protection mode. What is the reason?

### ISSUE THREAD

**Issue by yikangfeng** [Netflix/eureka#1178]
Ereka 1.9.8 Renews threshold is correct for the first time, and then this value will automatically grow, resulting in automatic opening of protection mode. What is the reason?

**Comment by mgtriffid** [comment]
Hi @yikangfeng , please check if your Eureka server has property `eureka.shouldFilterOnlyUpInstances` configured as `false`. See #1127 for details. Please read the first post there and see if it describes your situation.

**Comment by yikangfeng** [comment]
> Hi @yikangfeng , please check if your Eureka server has property `eureka.shouldFilterOnlyUpInstances` configured as `false`. See #1127 for details. Please read the first post there and see if it describes your situation.

Well, thank you very much.

**Comment by troshko111** [comment]
Thanks @mgtriffid.
