### ISSUE TITLE
Missing cache invalidation for remote region requests

### ISSUE THREAD

**Issue by NiteshKant** [Netflix/eureka#118]
In situations where a discovery client is configured to fetch registry information also from remote region(s), [the cache within the REST endpoint](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/resources/ResponseCache.java) is not invalidated for any change in the local registry information. Instead it expires after the configured cache expiry time (defaults to 3 mins)

The reason for this behavior is that [on invalidate() callback](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/resources/ResponseCache.java#L203) the keys it invalidates does not include the region names. Since, for the API calls that include the region parameter, the cache key is created with the region string, the invalidate call does not match that key. Hence, the cache does not get invalidated which results in no changes to the registry being visible to the client.

**Comment by bmpattanaik** [comment]
This issue is close . But how to change this default behavior **(defaults to 3 mins)**.
I am facing issue with invalidating when it runs locally with one eureka server.
https://github.com/spring-cloud/spring-cloud-netflix/issues/3652
