### ISSUE TITLE
client start failed : Ignoring onDemand update due to rate limiter

### ISSUE THREAD

**Issue by Tneciv** [Netflix/eureka#1181]
I use **spring boot 2.1.2.RELEASE** and **spring cloud Greenwich.RELEASE**

Other services use most of the same libs works fine except 2 services use **spring-boot-starter-amqp** cannot be registered to eureka .

Warn log is : **Ignoring onDemand update due to rate limiter**

**Comment by troshko111** [comment]
Trying Spring support may be a better option in this use case, seems unrelated to Eureka.
