### ISSUE TITLE
Excuse me, Eureka version 1.9.8 configures preferSameZone when configuring to get zones from DNS and service urls, so as to register under the same zone? Look at the source code or need to configure availability Zones. Is there any problem? Thank you.

### ISSUE THREAD

**Issue by yikangfeng** [Netflix/eureka#1182]
Excuse me, Eureka version 1.9.8 configures preferSameZone when configuring to get zones from DNS and service urls, so as to register under the same zone? Look at the source code or need to configure availability Zones. Is there any problem? Thank you.

![image](https://user-images.githubusercontent.com/6268253/52897418-1e8d8480-320f-11e9-9972-45a66abd1e9f.png)

**Comment by troshko111** [comment]
This is related to preferring the local availability zone, I suggest to check out say AWS docs on availability zones to better understand what this is and why it may be useful.
