### ISSUE TITLE
http://localhost:8761/ opens but http://localhost:8761/eureka doesn't

### ISSUE THREAD

**Issue by RajneeshDubey** [Netflix/eureka#1183]
While setting up discovery server on local -

eureka server dashboard opens at "http://localhost:8761/" but "http://localhost:8761/eureka" doesn't. And i need it to register my services on to that.  
![image](https://user-images.githubusercontent.com/15822150/53089384-73443e80-3532-11e9-8932-3771db4023dd.png)

![image](https://user-images.githubusercontent.com/15822150/53089424-8f47e000-3532-11e9-91e8-f5e3ea9e1ae8.png)

**Comment by troshko111** [comment]
Sorry this is likely unrelated to Eureka, if you feel otherwise please provide more details and a minimal repro, then feel free to reopen.

**Comment by 534614481** [comment]
http://localhost:8761/eureka/eureka put url in client property file like this.It worked for me
