### ISSUE TITLE
build fail-what are the right versions?

### ISSUE THREAD

**Issue by abhishek-anand13** [Netflix/eureka#1184]
I just cloned and tried build. I am getting following error. My java version is "1.8.0_191" and gradle version "5.2.1". Are these the right versions to build and use? Or there is another workaround I need to follow?

![image](https://user-images.githubusercontent.com/20058829/53261199-6de52080-36f9-11e9-8e9e-e493aa49e760.png)

**Comment by spencergibb** [comment]
You should use the gradle wrapper (`./gradlew`) rather than a gradle install.

**Comment by abhishek-anand13** [comment]
yup..got it..thanks
