### ISSUE TITLE
Eureka Server Ignoring Client Hostname while registration

### ISSUE THREAD

**Issue by msalmanST** [Netflix/eureka#1188]
Hey guys,

I am facing an same issue when running eureka server and eureka client on two different domains (both hosted on AWS), in this case eureka server always use its own domain name for the registered instance and not using the client hostname. I also try to set the client domain name by setting inside bootstrap.properties i.e eureka.instance.hostname=my.domain.com but it is not reflecting inside "/eureka/apps"

Any help is much appreciated.

Updated:
Both my eureka server and the client service running inside docker container in two different servers with two different domains.

**Comment by somnath157** [comment]
I am facing the same issue. did you find any solution for this?

**Comment by msalman** [comment]
Do check what is the hostname set for your machine using command `hostname`, eureka used the returned value as the hostname of the machine. Do update the hostname with your machine hostname and it will work fine.
