### ISSUE TITLE
How to inject com.netflix.discovery.DiscoveryClient

### ISSUE THREAD

**Issue by huangry999** [Netflix/eureka#1193]
With org.springframework.cloud.client.discovery.EnableDiscoveryClient annotation I could only inject org.springframework.cloud.client.discovery.DiscoveryClient. Anyway I want to register EurekaEventListener to eureka client, so I neet the com.netflix.discovery.DiscoveryClient.
How could I do? please.

**Comment by troshko111** [comment]
Seems more of a Spring question than Eureka, can you try searching through Spring issues to see if this has been asked? (and the docs)
