### ISSUE TITLE
Persistence Backed Registry

### ISSUE THREAD

**Issue by sandy-adi** [Netflix/eureka#1197]
I'm trying to setup a eureka registry backed by a persistence store. I don't see any documentation around this topic. 
Would it be possible to configure a persistence to store all the registered applications?

**Comment by troshko111** [comment]
Definitely not impossible but not something immediately pluggable into the current design. Look into "registries". The value of the data stored decreases exponentially over time so this has very low value in the first place. What's your use case?

**Comment by sandy-adi** [comment]
> Definitely not impossible but not something immediately pluggable into the current design. Look into "registries". The value of the data stored decreases exponentially over time so this has very low value in the first place. What's your use case?

The use case is that we are using eureka in a stand alone mode, the eureka cluster might die at any time and then come back up. At this point we want the eureka cluster to hydrate itself with the previously registered services.

**Comment by troshko111** [comment]
I'm not sure of the value of such feature as I mentioned the data is essentially worthless as it gets stale, focus on making the cluster available so it does not die all at once and rely on heartbeats to restore the data vs preloading some stale cache.

**Comment by sandy-adi** [comment]
The heartbeats are applicable only when your services have a eureka client right? our services are not all on Java and we will have to end up writing a eureka client for every stacke which IMO is not the best way to go about it. 

 Also it's not a stale cache, we actually have an abstraction API over eureka that updates the persistent store in addition to eureka. We were exploring use of archaius to keep eureka in sync with the persistent store but havent made  progress with that approach yet.

Isnt it risky to assume that your whole cluster will never go down?

**Comment by troshko111** [comment]
> The heartbeats are applicable only when your services have a eureka client right? our services are not all on Java and we will have to end up writing a eureka client for every stacke which IMO is not the best way to go about it.

I agree this is not the best way to do it, I would personally recommend to implement a sidecar which registers services in discovery instead, i.e. have a small process on localhost which hits your service healthcheck endpoint and if that returns success, heartbeats to discovery on your behalf. This way you don't have to implement Eureka clients in every stack, it has other benefits like proper startup sequence order, network connectivity check (loopback but still), etc.

> Also it's not a stale cache, we actually have an abstraction API over eureka that updates the persistent store in addition to eureka. We were exploring use of archaius to keep eureka in sync with the persistent store but havent made progress with that approach yet.
> 
> Isnt it risky to assume that your whole cluster will never go down?

I look at this differently, say everything crashes, the entire Eureka cluster:

- The clients still have the Eureka data, it's going stale but there's no outage (yet).
- Make sure when Eureka nodes crash new ones start up in their place fast, ideally under a minute.
- New node(s) came up.
- Your services started to heartbeat to the new Eureka nodes, Eureka data is fresh again and the service is fully restored.

In this absolutely disastrous scenario (all nodes went down) you did not even have an outage and had slightly stale Eureka data for couple minutes while the new nodes were coming up.

Is it worth it to add a bunch of complexity to replicate the data somewhere just to mitigate couple minutes of stale data once a couple months (this is pessimistic)?
