### ISSUE TITLE
java.net.URISyntaxException: Illegal character in authority - Eureka with AWS ECS 

### ISSUE THREAD

**Issue by jitesh-prajapati123** [Netflix/eureka#1200]
I have successfully registered AWS ECS containers with Eureka. When I run service discovery, it errors that there is an illegal character in URL.

java.net.URISyntaxException: Illegal character in authority at index 7: http://10.0.4.75 :32922/volvo-survey/tags [Check space/hidden special char after IP address].

Check the attached screenshot.

![error](https://user-images.githubusercontent.com/19203741/56721800-45ae8800-6763-11e9-9d77-852cf1f3a167.png)

**Comment by troshko111** [comment]
Please provide a minimal repro if possible and reopen.
