### ISSUE TITLE
"eureka" does not support "ipv6"?

### ISSUE THREAD

**Issue by zhuozl** [Netflix/eureka#1201]

**Comment by troshko111** [comment]
Please elaborate. What is the specific issue you're experiencing?

**Comment by huangleilz** [comment]
registry spring-config-server and spring-config-client in ipv6 environment , config-client get error config-server rui ,the rui lack of "[]". I follow spring-config-client code,find this maby spring-config-client bug.

**Comment by huangleilz** [comment]
> Please elaborate. What is the specific issue you're experiencing?

registry spring-config-server and spring-config-client in ipv6 environment, spring-config-client get error spring-config-server uri ,the rui lack of "[]". I follow spring-config-client code , find this maby config-client bug .

**Comment by troshko111** [comment]
You may want to include the setup and the specific error you're getting together with the full stack trace, otherwise hard to even localize the issue to any component.
