### ISSUE TITLE
Euraka server warning in java 11

### ISSUE THREAD

**Issue by zhaokejin** [Netflix/eureka#1205]
`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/D:/Java/m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by troshko111** [comment]
The project is largely Java 8 at this point but we're open to PRs for better Java 11 compatibility.
