### ISSUE TITLE
RetryableEurekaHttpClient candidateHosts size may improve to avoid quarantineSet not be cleared

### ISSUE THREAD

**Issue by izdt** [Netflix/eureka#1208]
Assume we have a same url in two zone(some reasons, although it's not reasonable), simply the configuration file as flows:

```
eureka.client.region=region1
eureka.client.availability-zones.region1 = zone1,zone2
eureka.client.serviceUrl.zone1=http://localhost:8080/eureka
eureka.client.serviceUrl.zone2=http://localhost:8080/eureka
eureka.client.transport.retryableClientQuarantineRefreshPercentage=1
```
If eureka server is not available, then the url will be added to quarantineSet. Client will not be able to re-register to eureka server when eureka server restarted (Always throw throw exception "There is no known eureka server; cluster server list is empty").

I analyse the code of RetryableEurekaHttpClient in the eureka-client:
```
  private final Set<EurekaEndpoint> quarantineSet = new ConcurrentSkipListSet<>();

  ...

	 if (currentEndpoint != null) {
                quarantineSet.add(currentEndpoint);
         }
  ...

  private List<EurekaEndpoint> getHostCandidates() {
        List<EurekaEndpoint> candidateHosts = clusterResolver.getClusterEndpoints();
        quarantineSet.retainAll(candidateHosts);

        // If enough hosts are bad, we have no choice but start over again
        int threshold = (int) (candidateHosts.size() * transportConfig.getRetryableClientQuarantineRefreshPercentage());
        //Prevent threshold is too large
        if (threshold > candidateHosts.size()) {
            threshold = candidateHosts.size();
        }
        if (quarantineSet.isEmpty()) {
            // no-op
        } else if (quarantineSet.size() >= threshold) {
            logger.debug("Clearing quarantined list of size {}", quarantineSet.size());
            quarantineSet.clear();
        } else {
            List<EurekaEndpoint> remainingHosts = new ArrayList<>(candidateHosts.size());
            for (EurekaEndpoint endpoint : candidateHosts) {
                if (!quarantineSet.contains(endpoint)) {
                    remainingHosts.add(endpoint);
                }
            }
            candidateHosts = remainingHosts;
        }

        return candidateHosts;
  }
```

The problem is: threshold use ```candidateHosts.size()``` (Use ```List```), but only ```quarantineSet.size() >= threshold``` the quarantineSet can be cleared.
Although two zones is diferent ```AwsEndpoint```, they are the same ```EurekaEndpoint```. At this time quarantineSet size is 1, but threshold is 2, quarantineSet.size() will always smaller than threshold. QuarantineSet will never be cleared, so client will not be able to re-register to eureka server when eureka server restarted.

My solution is translate candidateHosts list to set, and then use the candidateHostsSetSize:
```
    private List<EurekaEndpoint> getHostCandidates() {
        List<EurekaEndpoint> candidateHosts = clusterResolver.getClusterEndpoints();
        quarantineSet.retainAll(candidateHosts);

	 // Use Set to remove the same EurekaEndpoint in the List to prevent threshold always larger than quarantineSet size
        int candidateHostsSetSize = (new ConcurrentSkipListSet<>(candidateHosts)).size();
        // If enough hosts are bad, we have no choice but start over again
        int threshold = (int) (candidateHostsSetSize * transportConfig.getRetryableClientQuarantineRefreshPercentage());
        //Prevent threshold is too large
        if (threshold > candidateHostsSetSize) {
            threshold = candidateHostsSetSize;
        }
	if (quarantineSet.isEmpty()) {
            // no-op
        } else if (quarantineSet.size() >= threshold) {
            logger.debug("Clearing quarantined list of size {}", quarantineSet.size());
            quarantineSet.clear();
        } 
   ...
  }
```

**Comment by troshko111** [comment]
> Assume we have a same url in two zone

I think this is not reasonable and does not make sense to "support" in this way or any other way except for maybe better validation.

**Comment by izdt** [comment]
Yes,  putting a same url in two zone is meaningless. However, in actual use, in order to be highly available, there may be an additional edge address in two zone (after all, there is no document to point out it is forbidden), but once we do this, it will be dangerous. Because if eureka server network is shortbale unavailable, it will not be able to recover since the quarantineSet cannot be cleared.
Therefore, I personally not agree it's an additional validation, after all, it is not reasonable to compare the size of ```Set``` with the size of ```List```. Of course, I have considered other solutions, but the smallest and easiest way to change is to compare size with the same structure. So I hope to solve this issuse to avoid the risk, maybe there is a better way?

**Comment by izdt** [comment]
> I think this is not reasonable and does not make sense to "support" in this way or any other way except for maybe better validation.

Yes, putting a same url in two zone is meaningless. However, in actual use, in order to be highly available, there may be an additional edge address in two zone (after all, there is no document to point out it is forbidden), but once we do this, it will be dangerous. Because if eureka server network is shortbale unavailable, it will not be able to recover since the quarantineSet cannot be cleared.
Therefore, I personally not agree it's an additional validation, after all, it is not reasonable to compare the size of Set with the size of List. Of course, I have considered other solutions, but the smallest and easiest way to change is to compare size with the same structure. So I hope to solve this issuse to avoid the risk, maybe there is a better way?

**Comment by troshko111** [comment]
> Yes, putting a same url in two zone is meaningless.

My point exactly. The url cannot be the same by definition, otherwise that's just the same zone, two urls which are the same point to the same thing.

> in actual use, in order to be highly available, there may be an additional edge address in two zone (after all, there is no document to point out it is forbidden), but once we do this, it will be dangerous

Can you elaborate? Could you give an example maybe?

As for the document, there's no strict requirements doc for everything so some things are assumed where reasonable (like here).

I understand the bug you observed and understand the potential fix you proposed, the thing is that the system should not work around bad data and hide potential issues, this can manifest in other places and the system should fail early not continue pretending "it's fine" if two servers point to the same address. In this case I'd rather reject the configuration as fundamentally invalid.

**Comment by izdt** [comment]
> Can you elaborate? Could you give an example maybe?
> 
> As for the document, there's no strict requirements doc for everything so some things are assumed where reasonable (like here).
> 
> I understand the bug you observed and understand the potential fix you proposed, the thing is that the system should not work around bad config and hide potential issues, this can manifest in other places and the system should fail early not continue pretending "it's fine" if two servers point to the same address. In this case I'd rather reject the configuration as fundamentally invalid.


Thanks for your reply and explain. It's much reasonable to check the config first and prevent the potential issues.
I gave a bad example, actually, we never config like this. This is a simple example to explain this issue. 
I found this issue at a high-available exercise, and I spent few hours to find out why eureka servers alaways not available.
We use eureka with a large-scale nodes, to make the server more high available, we use multi-zone config, and we want use a smart DNS to resolve serviceUrls:
```
eureka:
 client:
   region: abc
   useDnsForFetchingServiceUrls: true
   eurekaServerPort: 10101
   eurekaServerDNSName: demo.com
   eurekaServerURLContext: eureka
```
and the DNS txt is:
```
txt.abc.demo.com -> aregion.abc.demo.com bregion.abc.demo.com
txt.aregion.abc.demo.com to 10.0.0.1 10.0.0.2
txt.bregion.abc.demo.com to 10.0.1.3 10.0.1.4
```
It works fine, but when bregion is down, the DNS will dynamic to resolve bregion address to aregion address.The problem comes... then I thought could we fix this.  Now I think we shouldn't let the Smart DNS to resolve urls dynamically, just let eureka client do by itself.
Thanks for your time to discuss this issue with me.
