### ISSUE TITLE
RestTemplate call "I/O error on GET request for" - PCFDEV - Eureka

### ISSUE THREAD

**Issue by mkpraveen** [Netflix/eureka#1215]
I'm getting below error when I make resttemplate call as below.
To me it looks like random generated hostname is not accessible.

I use pcfdev-v0.30.2+PCF1.11.0-windows ,  pcfdev-v1.2.0-windows. spring-boot.2.1.3.

// Get movie details
MovieDetails movieDetails = 
restTemplate.getForObject("http://movie-details-service/jpamovies/" + movieId, MovieDetails.class);

"message": "I/O error on GET request for \"http://movie-details-service/jpamovies/2\": 7c6b7bdc-36ca-4b0f-77d9-f2f2; nested exception is java.net.UnknownHostException: 7c6b7bdc-36ca-4b0f-77d9-f2f2",

I'm having Eureka server registration as below.

Application | AMIs | Availability Zones | Status
-- | -- | -- | --
MOVIE-CATALOG-SERVICE | n/a (1) | (1) | UP (1) - bdd136c3-c3e6-4333-4840-fcd0
MOVIE-DETAILS-SERVICE | n/a (1) | (1) | UP (1) - 7c6b7bdc-36ca-4b0f-77d9-f2f2

Please help to resolve the issue.

**Comment by troshko111** [comment]
This does not seem to be related to Eureka (as shown above the registration data seems fine), consider checking the docs for the client used (Spring).
