### ISSUE TITLE
Rigisting hava some wrong

### ISSUE THREAD

**Issue by Aronlele** [Netflix/eureka#1225]
Now i deploy client service app and config serviceurl  http://xx.xx.xx.102:8761/eureka/,http://xx.xx.xx.103:8761/eureka/
ps, defaultZone 
but register-center have not register each other, so is not syc
issue:
service app only registered in one center,hope have a resolution

**Comment by troshko111** [comment]
Please provide detailed setup and detailed analysis (logs at least).
