### ISSUE TITLE
Eureka microservices on load testing giving, com.sun.jersey.api.client.clienthandlerexception:java.net.connectexception:connection refused

### ISSUE THREAD

**Issue by amir-ansari** [Netflix/eureka#1228]
We are load testing our application. we have eureka naming server in cluster(replica).All services registers with eureka without any issue. But when we start hitting the api's in for loop, after some time (2,3 minutes) it gives com.sun.jersey.api.client.clienthandlerexception:java.net.connectexception:connection refused.

Here are my yml for naming server 1

eureka:
  instance:
    hostname: 10.0.60.49
  server:
    enableSelfPreservation: false
   
  client:
    serviceUrl:
      defaultZone: http://10.0.60.50:8762/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8761

Here are my yml for naming server 2

eureka:
  instance:
    hostname: 10.0.60.50
  server:
    enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: http://10.0.60.49:8761/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8762

Any help will be appriciated, thanks.

**Comment by troshko111** [comment]
Need more info, set up, test script, metrics during test, etc.
