### ISSUE TITLE
Examples with rest services

### ISSUE THREAD

**Issue by DareUrDream** [Netflix/eureka#1234]
I have trying to use Eureka to deploy rest services, but then the current examples are standard main method [eureka-examples](https://github.com/Netflix/eureka/tree/master/eureka-examples) ones. Are they are neat tricks so that deploying rest services are easy. Would appreciate if an example is shared for the benefit of all users.

Cheers !!
DareUrDream

P.S - I know spring integration can do it but am trying to achieve this without using the integration projects.

**Comment by troshko111** [comment]
We don't have guidelines for that, use whatever you're most comfortable with. We internally leverage Spring for Java services, see https://www.youtube.com/watch?v=mln3_o6qlBo
