### ISSUE TITLE
Application service not able to register to the Eureka server

### ISSUE THREAD

**Issue by shaezard** [Netflix/eureka#1239]
Hi

I launched a eureka-server using spring-boot. I have a non spring-boot application service. Can a non spring-boot application register to a spring-boot eureka-server. If yes, how to do that?

**Comment by troshko111** [comment]
Absolutely yes, if that app is in Java, you can use the `EurekaClient`, if not, check its heartbeat protocol (wiki, source code) and mimic the behavior.
