### ISSUE TITLE
Eureka Client not working

### ISSUE THREAD

**Issue by gpugems** [Netflix/eureka#1241]
import { logger } from '../common/logging';
import { ExpressConfig } from './Express';
import { Eureka } from 'eureka-js-client';

export class Application {

  server: any;
  express: ExpressConfig;

  constructor() {
    this.express = new ExpressConfig();
    
    const port = 3001;
    this.server = this.express.app.listen(port, () => {
      logger.info(`Server Started! Express: http://localhost:${port}`);
});
  
  let client=new Eureka({
    instance: {
      app: 'hello-world-chapter-6',
      hostName: 'localhost',
      ipAddr: '127.0.0.1',
      statusPageUrl: `http://localhost:${port}`,
      healthCheckUrl: `http://localhost:${port}/health`,
      port: {
        '$': port,
        '@enabled': true,
      },
      vipAddress: 'myvip',
      dataCenterInfo: {
        '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
        'name': 'MyOwn',
      },
    },
    eureka: {
      host: 'localhost',
      port: 8761,
      servicePath: '/eureka/apps/',
    }
  });
  client.start();

  process.on('SIGINT', ()=>{
    this.server.close();
    client.stop();
  });
  
}

}

Error starting the Eureka Client { Error: connect ECONNREFUSED 127.0.0.1:8761
    at Object._errnoException (util.js:1031:13)
    at _exceptionWithHostPort (util.js:1052:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1195:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8761 }

**Comment by troshko111** [comment]
I don't know what client this is, but even ignoring the fact it's not part of the repository and is likely a wrong place to report, looks to me nothing's wrong with it per se, clearly nothing's listening on the port you're trying to connect to: see https://linux.die.net/man/2/connect.
