### ISSUE TITLE
Regression in Eureka server 1.8.0 (and above)

### ISSUE THREAD

**Issue by GFriedrich** [Netflix/eureka#1242]
I've just updated from Eureka 1.7.2 to the latest Eureka version and ended up with a regression due to the PR #970 
More specifcally the InstanceInfo now contains a lowercase app name even though it shouldn't.
Reason: One of my apps registering at Eureka uses a lowercase app name. But normally Eureka itself should do an "uppercase" call to have this fixed.
This is expected to happen for the deserialization at https://github.com/Netflix/eureka/blob/9d07ac4aaba90876d89a691521c128c9c59bcce8/eureka-client/src/main/java/com/netflix/discovery/converters/EurekaJacksonCodec.java#L516-L526
But the thing is: The cache already contains the string in the lowercase variant and the value transformer is not even called, resulting in the lowercase variant to be used.
My idea would be to overwrite the source of the underlying ArrayCharBuffer at https://github.com/Netflix/eureka/blob/9d07ac4aaba90876d89a691521c128c9c59bcce8/eureka-client/src/main/java/com/netflix/discovery/util/DeserializerStringCache.java#L320
by calling the value transformer to make sure that the source already has the right value (offset and length need to be set accordingly). No need to keep the value transformer anymore.
@troshko111 what do you think?

**Comment by troshko111** [comment]
Fixed by #1245
