### ISSUE TITLE
Eureka Register service with RESR API

### ISSUE THREAD

**Issue by gpugems** [Netflix/eureka#1244]
Hi,

I am trying to register a microservice in eureka with the following input. 

curl -X POST -i http://localhost:8761/eureka/apps --data '{
    instance: {
        hostName: "WKS-SOF-L011",
        app: "com.automationrhapsody.eureka.app",
        vipAddress: "com.automationrhapsody.eureka.app",
        secureVipAddress: "com.automationrhapsody.eureka.app",
        ipAddr: "10.0.0.10",
        status: "STARTING",
        port: {$: 8080, @enabled: true},
        securePort: {$: 8443, @enabled: true},
        healthCheckUrl: "http://WKS-SOF-L011:8080/healthcheck",
        statusPageUrl: "http://WKS-SOF-L011:8080/status",
        homePageUrl: "http://WKS-SOF-L011:8080",
        dataCenterInfo: {
            @class: "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo", 
            name: "MyOwn"
        },
    
}'

And got the following error message : 

{"timestamp":1568974209215,"status":405,"error":"Method Not Allowed","message":"Method Not Allowed","path":"/eureka/apps/"}

**Comment by troshko111** [comment]
https://github.com/Netflix/eureka/wiki/Eureka-REST-operations
