### ISSUE TITLE
why expectedNumberOfRenewsPerMin not reduce after Eureka client shutting down unexpectedly ?

### ISSUE THREAD

**Issue by githubyong** [Netflix/eureka#1247]
I have a standalone eureka server(not self register) and a eureka client.
1.set  enable-self-preservation =true
2. kill eureka client process.
3. start eureka client.
Repeat step 2-3, the ekreua server "Renews threshold" will increment very fast, and eureka server enter self preservation after a while. I had to restart the eureka server to recover it.
it seems that it won't call server method 'com.netflix.eureka.registry.PeerAwareInstanceRegistryImpl#cancel' when Eureka client shutting down unexpectedly . is it proper ?

**Comment by troshko111** [comment]
By design to protect against mass information loss in case of a wide range is potential issues.
