### ISSUE TITLE
Whitelist/BlackList

### ISSUE THREAD

**Issue by franciscopalos** [Netflix/eureka#1248]
Hi all,

Is there any way to stablish a whitelist or blacklist in order to enable registry only microservices deployed in several hosts? 
I know that we could use AWS zones, but currently we have deployed all microservices in our internal intranet.

Thanks & Regards

**Comment by troshko111** [comment]
You mean like create a whitelist of services are allowed to talk to Eureka?

**Comment by smtdev** [comment]
> You mean like create a whitelist of services allowed to talk to Eureka?

Yes, that's exactly what we are looking for but it seems there is no way to perform it. Isn't it?

Thanks!

**Comment by mattnelson** [comment]
There are two properties that control if the instance should register with eureka and if the instance should fetch the registry. These can be flexed on those hosts you do not want to participate with eureka.

https://github.com/Netflix/eureka/blob/743af8be0fa37118a3a9ee0d39f3ba8a89621119/eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java#L273-L284
https://github.com/Netflix/eureka/blob/743af8be0fa37118a3a9ee0d39f3ba8a89621119/eureka-client/src/main/java/com/netflix/discovery/EurekaClientConfig.java#L451-L456

**Comment by troshko111** [comment]
> @troshko111 Yes, that's exactly what we are looking for but it seems there is no way to perform it. Isn't it?
> 
> Thanks!

In addition to what @mattnelson has mentioned, depending on your requirements and reliability of the solution I'd suggest to explore:

- If deployed to a cloud provider infra, look into network control like security groups on AWS and equivalent on Azure/GCP.
- Put on a reverse proxy in front of Eureka instances and require mTLS (terminating it at the reverse proxy), make the proxy verify the client identities against the whitelist or just use special certs.
- Use a firewall of some sort, iptables should do.

This is really outside of the service concerns.

**Comment by smtdev** [comment]
Hi both,

Thanks for your help. We will check it now.
