### ISSUE TITLE
Why Eureka Servers do not exchange instances each other?

### ISSUE THREAD

**Issue by yuanxuzhang** [Netflix/eureka#1253]
Hi,There is two Eureka Servers named ServerA and ServerB, a part of services with Eureka Client named ClientA,ClientB were setted eureka.client.serviceUrl.defaultZone value to ServerA, the rest of services with Eureka Client named ClientC,ClientD were setted eureka.client.serviceUrl.defaultZone value to ServerB. ServerA and ServerB defaultZone were setted each other. I expected ServerA and ServerB could replicate client instances,ServerA has all clients, the same as ServerB, but ServerA only has ClientA,ClientB(ServerB only has ClientC,ClientD). Even ServerA and ServerB were started with fetchRegistry=true setting had all clents, ServerA would lost clientC and clientD later(no heate beat). Why Eureka Servers do not exchange instances each other? Need the Client must set eureka.client.serviceUrl.defaultZone value to all eureka servers(ServerA and ServerB)?

**Comment by troshko111** [comment]
Hard to tell much without a minimal repro with config samples, looks like a misconfiguration to me. Make sure you correctly set up the Eureka cluster first.
