### ISSUE TITLE
Ask a conceptual question, different regions can not access each other, right?

### ISSUE THREAD

**Issue by startjava** [Netflix/eureka#1254]
Ask a conceptual question, different regions can not access each other, right?
different zone can access each other？
zone inner servers can access each other？

3 ask ...

hope answer:
（1）？
（2）？
（3）？

thank you very much!

**Comment by troshko111** [comment]
Yes to all 3.

Regions do not communicate among themselves due to regional isolation model, i.e. to support fail out and cookie cutter region expansion.
