### ISSUE TITLE
Stack for i-xxx does not exist (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: xxx

### ISSUE THREAD

**Issue by lucasobsidiam** [Netflix/eureka#1255]
We are trying to move our local micro-service architecture to Amazon Web Services with my little experience.

I have added the ConfigBean line, Maven Dependency and am trying to compile in an EC2 instance which then is sent to ECR and deployed on Fargate. I have attached an IAM role so that when I load Eureka with AWS Autoconfigure it doesn't throw an access key error as adding it to the config did not work. Now I am having the following error appear, which I can't figure out what it's trying to do in CloudFormation:

> Stack for i-0d6112770e8cb97b2 does not exist (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: e1ac5b22-8b1c-43a5-b93c-e469a541fe46)

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.aws.core.env.ResourceIdResolver.BEAN_NAME': Invocation of init method failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stackResourceRegistryFactoryBean' defined in class path resource [org/springframework/cloud/aws/autoconfigure/context/ContextStackAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.aws.core.env.stack.config.StackResourceRegistryFactoryBean]: Factory method 'stackResourceRegistryFactoryBean' threw exception; nested exception is com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Stack for i-0d6112770e8cb97b2 does not exist (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: e1ac5b22-8b1c-43a5-b93c-e469a541fe46)`

Where should I be looking at?

**Comment by troshko111** [comment]
Try to ask at Spring, this is unrelated to Eureka, looks to me like you're missing the value for stack property.
