### ISSUE TITLE
How to delay eureka client registration eureka server?

### ISSUE THREAD

**Issue by kinsey-jian** [Netflix/eureka#1256]
In K8S, I have a Spring Boot application which is also a Eureka client. The normal behavior of the application is to register with Eureka server on start up as UP. I have a requirement that the application shouldn't register with the Eureka server until k8s readiness finished

**Comment by troshko111** [comment]
This is more of a Spring question, in short you should not call the `.register()` until ready to do so. You may also look into supplying a healthcheck preventing it from going to UP unless your conditions are met.
