### ISSUE TITLE
How to register a go microservice in spring eureka server

### ISSUE THREAD

**Issue by kushankavinda** [Netflix/eureka#1257]
I tried many ways to register go microservice in eureka can you please let me know what is the end point that  i neet to call to register a microservice

**Comment by troshko111** [comment]
Follow the logic in `DiscoveryClient`, you need to heartbeat to
`/discovery/v2/apps/$APP/$INSTANCE_ID?status=$STATUS&lastDirtyTimestamp=$LAST_REGISTRATION` with the appropriate content.

**Comment by troshko111** [comment]
We do not ship non-Java clients but it should be pretty trivial to implement a sidecar registering with Eureka and use it in all non-Java services.
