### ISSUE TITLE
maybe this is a bug in eureka-client in class com.netflix.discovery.shared.transport.jersey.ApacheHttpClientConnectionCleaner

### ISSUE THREAD

**Issue by chaichunyang** [Netflix/eureka#1259]
in class com.netflix.discovery.shared.transport.jersey.ApacheHttpClientConnectionCleaner
the method cleanIdle is for clean idle connections from the pool
the parameter is in MILLISECONDS, but use connectionManager. closeIdleConnections in SECONDS

    public void cleanIdle(long delayMs) {
        Stopwatch start = executionTimeStats.start();
        try {
            apacheHttpClient.getClientHandler().getHttpClient()
                    .getConnectionManager()
                    .closeIdleConnections(delayMs, TimeUnit.SECONDS);
        } catch (Throwable e) {
            logger.error("Cannot clean connections", e);
            cleanupFailed.increment();
        } finally {
            if (null != start) {
                start.stop();
            }
        }
    }

**Comment by chaichunyang** [comment]
no one reply this？

**Comment by troshko111** [comment]
This appears to be a typo, this is constructed via `EurekaJerseyClientBuilder` all usages of which read a config property explicitly suffixed with `seconds`, i.e. there's no bug but the parameter name should be `delayS` instead of the current `delayMs`.

**Comment by chaichunyang** [comment]
> This appears to be a typo, this is constructed via `EurekaJerseyClientBuilder` all usages of which read a config property explicitly suffixed with `seconds`, i.e. there's no bug but the parameter name should be `delayS` instead of the current `delayMs`.

thank you for response, But I debug the code, the configuration property `eureka.client.service-url.eureka-connection-idle-timeout-seconds`  sure is `seconds` by default 30, But in `com.netflix.discovery.shared.transport.EurekaClientFactoryBuilder` it has been multiplied 1000, so when call the build method, the connectionIdleTimeout param actually is `30 * 1000`.

EurekaClientFactoryBuilder:
    public B withClientConfig(EurekaClientConfig clientConfig) {
        withClientAccept(EurekaAccept.fromString(clientConfig.getClientDataAccept()));
        withAllowRedirect(clientConfig.allowRedirects());
        withConnectionTimeout(clientConfig.getEurekaServerConnectTimeoutSeconds() * 1000);
        withReadTimeout(clientConfig.getEurekaServerReadTimeoutSeconds() * 1000);
        withMaxConnectionsPerHost(clientConfig.getEurekaServerTotalConnectionsPerHost());
        withMaxTotalConnections(clientConfig.getEurekaServerTotalConnections());
        **withConnectionIdleTimeout(clientConfig.getEurekaConnectionIdleTimeoutSeconds() * 1000);**
        withEncoder(clientConfig.getEncoderName());
        return withDecoder(clientConfig.getDecoderName(), clientConfig.getClientDataAccept());
    }
when writting this comment I found the newest version 1.9.14 has fix this bug already.
but the newest spring cloud still depend on 1.9.13. so finally i need update my depends.
