### ISSUE TITLE
Instance is OUT_OF_SERVICE in service registry, still traffic flowing to this instance 

### ISSUE THREAD

**Issue by ganeshcbhanage** [Netflix/eureka#1260]
I was trying out eureka endpoints as mentioned [here](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations)

After doing PUT /eureka/v2/apps/appID/instanceID/status?value=OUT_OF_SERVICE for 1 instance, it is going out of service in service registry, but still I see traffic flowing through this instance.

Any help here is appreciated.

**Comment by troshko111** [comment]
The state is eventually consistent, if you're sure all the servers` registries have it as OOS but the traffic is still going there, it must be an issue on the client side, do the clients see the changes? If no, why? Are there any connectivity issues? What's the impact duration (1m, 30m, hours, persistent?) Anything over 1-2m would indicate an issue with propagation and needs to be localized to the server/client first.

**Comment by ganeshcbhanage** [comment]
I got to know, it is because of PCF. The way PCF handles routes registry using GO router

**Comment by troshko111** [comment]
Can you elaborate? Was there an actual issue or a misconfiguration?
