### ISSUE TITLE
Release 1.9.14 Fails to Build

### ISSUE THREAD

**Issue by copperlight** [Netflix/eureka#1263]
Steps to reproduce:

1. Download the `tar.gz` file from the [1.9.14 Releases page](https://github.com/Netflix/eureka/releases/tag/v1.9.14).
1. Extract the tarball.
1. `./gradlew build`

Error:

```
./gradlew build

...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/matthewj/Downloads/eureka-1.9.14/build.gradle' line: 10

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '3.6.0']
> Failed to apply plugin [id 'nebula.netflixoss']
   > Cannot set property 'defaultVersionStrategy' on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.677 secs
```

The issue is that the Nebula plugin depends on the existence of tags within a Git repo.

If you clone the repo, checkout the v1.9.14 tag and build from there, then it succeeds.

**Comment by ltsstar** [comment]
I run into the same error. Any updates on this?

**Comment by troshko111** [comment]
No changes, PRs are welcome, otherwise you can use the workaround:

> checkout the v1.9.14 tag and build from there, then it succeeds.

**Comment by copperlight** [comment]
After thinking about it, I am fine with the build process as it is.

It may be worth a doc update mentioning that tags should be checked out to perform a build.
