### ISSUE TITLE
How to delay eureka-client registration without set leaseRenewalIntervalInSeconds?

### ISSUE THREAD

**Issue by mengnanpanghu** [Netflix/eureka#1264]
Hi, I have already set ```eureka.client.initialInstanceInfoReplicationIntervalSeconds``` ,but it's not work for me because the ***heartbeat*** task still run the ```register()```  

So I have to set the ```eureka.instance.leaseRenewalIntervalInSeconds``` which also have an impact on the heartbeat interval, and it finally works.  

Is there a way to delay eureka-client registration without set leaseRenewalIntervalInSeconds?

**Comment by troshko111** [comment]
Have you considered utilizing the status for this? i.e. do not report yourself as "UP" until you're ready, would that do it?

**Comment by mengnanpanghu** [comment]
My bad, I should have found this solution earlier, It works
Thanks for your help
