### ISSUE TITLE
Where to update the "expectedNumberOfClientsSendingRenews" when we evict a instance?

### ISSUE THREAD

**Issue by barrywangmeng** [Netflix/eureka#1266]
When I look at eureka has been a source of confusion in "selfPreservationMode", I saw the sorce code with mater branch,
when we see register or cancel method, there will be update "expectedNumberOfClientsSendingRenews", just like the code:

```java
// The lease does not exist and hence it is a new registration
synchronized (lock) {
    if (this.expectedNumberOfClientsSendingRenews > 0) {
        // Since the client wants to register it, increase the number of clients sending renews
        this.expectedNumberOfClientsSendingRenews = this.expectedNumberOfClientsSendingRenews + 1;
        updateRenewsPerMinThreshold();
    }
}
```

i have read the code with "evict" method in "AbstractInstanceRegistry" class, but i didn't find where to update the "expectedNumberOfClientsSendingRenews" when we evict a instance according to a timed task. 

can you tell me where to update the "expectedNumberOfClientsSendingRenews" when we evict a instance ?

**Comment by barrywangmeng** [comment]
I saw the same question, but it seems that the problem has not been solved。
see detail：https://github.com/spring-cloud/spring-cloud-netflix/issues/2407

**Comment by troshko111** [comment]
Trying to understand whether this was intentional (and why) but so far it looks like a bug to me.
