### ISSUE TITLE
How to recover from self preservation mode under auto scaling

### ISSUE THREAD

**Issue by larryxuzhen** [Netflix/eureka#1267]
I have a k8s cluster with several auto scaling deployments. When the number of instance decrease sharply, Eureka may enter the self preservation mode and can not recover automatically. Cuz the those instances actually disappeared and would not reappear, and the renew threshold keeps high for nonexistent instances... 
Is there any recommended way to deal with it other than decreasing the renewalPercentThreshold?

**Comment by mgtriffid** [comment]
Hi, in this case you may try to change configuration parameter `eureka.enableSelfPreservation` to `false` temporarily, wait until Eureka picks up new value, then wait for it to evict the instances, then set this property back to `true`.
