### ISSUE TITLE
Spring netflix Zuul Connection Refused

### ISSUE THREAD

**Issue by amin224** [Netflix/eureka#1270]
Hi,

I have eureka server discovery for my microservice connected to eureka as client, in addition i added an api gateway netflix zuul in order to load balance multiple instances run on different machines ( different IP addresses). My question is how can i enable Zuul to load balance between the instances. I am aware of these properties for Zuul that will do the job but i don't know how to add additional IP addresses to be connected to Zuul as i am getting connection refused for different machines.

Zuul server application.properties
```
zuul.routes.microservice.url=http://{1 of the machine IP address}/8100/
zuul.routes.microservice.path=/microservice/**
zuul.routes.microservice.serviceID=microservice1
zuul.routes.microservice.sensitiveHeaders=
eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://{eureka IP address machine}:8761/eureka
```
Thank you

**Comment by amin224** [comment]
Turns out i left an important note that proved i was not load balancing by using the above property `zuul.routes.microservice.url=http://{1 of the machine IP address}/8100/`

https://cloud.spring.io/spring-cloud-netflix/reference/html/#router-and-filter-zuul

Below properties worked for me

    zuul.routes.microservice.path=/microservice/**
    zuul.routes.microservice.serviceID=microservice1
    microservice1.ribbon.listOfServers=http://{machine 1 ip address}:8100/,http://{machine 2 ip address}:8100/,http://localhost:8100/
    microservice1.ribbon.eureka.enabled=true

**Comment by amin224** [comment]
Can someone please forward me a link where they discuss about these properties in details or try to explain as i could not find detailed explanation. Thank you

```
zuul.host.time-to-live=
zuul.host.connect-timeout-millis=
zuul.host.socket-timeout-millis=
zuul.semaphore.max-semaphores=
ribbon.ServerListRefreshInterval=
ribbon.ConnectTimeout=
ribbon.ReadTimeout=
ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServ
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=
```

**Comment by troshko111** [comment]
Have you checked out https://github.com/Netflix/ribbon and https://github.com/Netflix/zuul yet?

**Comment by amin224** [comment]
Thank you for the links that you have sent me, I will look them up and much appreciated.
