### ISSUE TITLE
Time for Eureka 3?

### ISSUE THREAD

**Issue by rotilho** [Netflix/eureka#1272]
Eureka 2 was discontinued but are there any plans to build a Eureka 3?

Push notification and subscribe in a subset of the registry are killing features that I heavily miss in Eureka 1.

**Comment by troshko111** [comment]
We don't have a timeline or any specifics to share, but as soon as we do, we'll definitely engage the community.

**Comment by deepu105** [comment]
Hello team, given the last commit and release on the main branch was almost a year ago, it would be nice to discuss the future of Eureka. Is there some plan for maintenance?

**Comment by error0702** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
