### ISSUE TITLE
The renew method of class Lease in eureka-core why add duration

### ISSUE THREAD

**Issue by zxm812** [Netflix/eureka#1277]
when the Lease renew, lastUpdateTimestamp = System.currentTimeMillis() + duration;
but method of isExpired add the duration another:
public boolean isExpired(long additionalLeaseMs) {
        return (evictionTimestamp > 0 || System.currentTimeMillis() > (lastUpdateTimestamp + duration + additionalLeaseMs));
}

**Comment by barrywangmeng** [comment]
This may be an officially known bug，you can see the code comments in `Lease.isExpired()`，just like this：
```java
/**
 * Checks if the lease of a given {@link com.netflix.appinfo.InstanceInfo} has expired or not.
 *
 * Note that due to renew() doing the 'wrong" thing and setting lastUpdateTimestamp to +duration more than
 * what it should be, the expiry will actually be 2 * duration. This is a minor bug and should only affect
 * instances that ungracefully shutdown. Due to possible wide ranging impact to existing usage, this will
 * not be fixed.
 *
 * @param additionalLeaseMs any additional lease time to add to the lease evaluation in ms.
 */
public boolean isExpired(long additionalLeaseMs) {
    return (evictionTimestamp > 0 || System.currentTimeMillis() > (lastUpdateTimestamp + duration + additionalLeaseMs));
}
```

In the end, they said "Due to possible wide ranging impact to existing usage, this will not be fixed."
