### ISSUE TITLE
Can a newer version of Eureka client(e.g. 1.9.2) be used with an older version of the server(e.g. 1.6.2)?

### ISSUE THREAD

**Issue by kaoyahuigui2018** [Netflix/eureka#1280]
We are planning to upgrade springboot1.5.6 to 2.x, which contains
springcloud-eureka will also be upgraded from 1.3.1 (eureka 1.6.2) to 1.4.x (eureka 1.9.2),
But now there are many different projects (non-springboot projects) registered on the eureka server, so we don't want to upgrade the eureka server and only upgrade the client. Is there any problem in this?

**Comment by troshko111** [comment]
Should be no problem, the API is compatible.
