### ISSUE TITLE
How to prevent unwanted clients register to the eureka server?

### ISSUE THREAD

**Issue by KomaBeyond** [Netflix/eureka#1285]
As the title description, is there any way that i can do in the eureka server side to prevent client registration?

**Comment by troshko111** [comment]
This really depends on your situation (how exposed the server is, what guarantees you're looking for), I suggest you explore these options (order desc by reliability/guarantees):

1) `mTLS`, reject not whitelisted clients
2) `iptables`, reject not whitelisted subnets
2) If deployed to a public cloud, look into the cloud offerings for network security (e.g. security groups on AWS) and create a VPC for trusted clients and only allow traffic from there

Best to do 1 + 2, require mTLS and limit the traffic to an internal VPC.

**Comment by KomaBeyond** [comment]
@troshko111 

Thanks for ur reply and u given a very good ideas. But because some of reasons, we expected to do this work just only in the eureka server application inside. 

So is there any extension way that i can use to? 

I saw there is a class named PeerAwareInstanceRegistryImpl and it has a register method responsibility to the client registration. 

So if i can extension this class and override the register method then i can prevent client registration in this method though the instance metaDataMap attribute.

**Comment by KomaBeyond** [comment]
@troshko111 

Thanks for ur reply and u given a very good ideas. But because some of reasons, we expected to do this work just only in the eureka server application inside.

So is there any extension way that i can use to?

I saw there is a class named PeerAwareInstanceRegistryImpl and it has a register method responsibility to the client registration.

So if i can extension this class and override the register method then i can prevent client registration in this method though the instance metaDataMap attribute.

**Comment by troshko111** [comment]
Yeah as I said it depends on what kind of guarantees you're looking for, if you don't care about doing it securely than you absolutely can override some registry methods and just reject registrations of instances you don't like.

Just note that this is trivial to game, as the traffic is plaintext and the registration info is self-reported, anyone can report any nonsense until you accept it. If you're in some sort of trusted environment that may be ok, but probably worth mentioning.

**Comment by KomaBeyond** [comment]
Yeah, thanks for your reply, and finally we are using the spring-security to do this work.
