### ISSUE TITLE
Eureka Discovery + Zuul Gateway as one app

### ISSUE THREAD

**Issue by Blarc** [Netflix/eureka#1291]
I am wondering if it is possible to run both eureka discovery and zuul gateway on the same microservice? Thanks.

(This is my first time making an issue on open source project, so I hope this is not the wrong place and I am sorry if it is.)

**Comment by troshko111** [comment]
Hey, they do different things, Zuul is an edge proxy and Eureka is a service registry, you totally can use both together, if by "together" you mean a single logical "platform" you deploy your microservices to. Are you trying to figure out if you can run both on the same host?

**Comment by Blarc** [comment]
Yes, I was wondering if you can run them both on the same host and I managed to do it by now. It's probably not the proper way to do it, but I needed to do this, because of the 5 apps restriction on Heroku. Thanks anyway :)

**Comment by troshko111** [comment]
Sure, no worries. You may want to look into containers (may be easy to tap into `systemd` features for namespacing/cgroups) to get some level of isolation.
