### ISSUE TITLE
DiscoveryManager failed to lookup latest application instances.

### ISSUE THREAD

**Issue by alexchoi-git** [Netflix/eureka#1302]
Environment:
Module eureka-client
Version: 1.0.3.RELEASE (inherent from spring-cloud-starter-parent, version Angel.SR3)

Issue:
DiscoveryManager not returns the latest application instances even if new comers are registered to the service. No error found, looks like the cache never refresh. 

Invoked method:
DisoveryManager.getInstance().getLookupService.getApplication("applicationName").getInstances();

**Comment by spencergibb** [comment]
That's a very old client, have you tried updating?
