### ISSUE TITLE
Why eureka client register so quickly ?

### ISSUE THREAD

**Issue by lvyunpeng** [Netflix/eureka#1305]
when eureka client starting, I do not want it register right now, because some other work should to do, such as run test,  and i do not want it accept traffic once it start. So the InitialInstanceInfoReplicationIntervalSeconds is 40s default ,but it not works. For  statusChangeListener found that client transfer status starting to UP, and it register soon. what should i do

**Comment by lvyunpeng** [comment]
why not ignore first status changes ? it make config  InitialInstanceInfoReplicationIntervalSeconds  meaningless. And i think once it start, it is not best state to handler external request, it need time to connect to downstream service

**Comment by troshko111** [comment]
Setup your healthcheck handler in the way it won't report healthy until you're all ready, see https://github.com/Netflix/eureka/blob/cac06f4b431ef3c099719dd3ee9af7d8bb2d3bae/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L1426-L1427

**Comment by lvyunpeng** [comment]
> Setup your healthcheck handler in the way it won't report healthy until you're all ready, see
> 
> https://github.com/Netflix/eureka/blob/cac06f4b431ef3c099719dd3ee9af7d8bb2d3bae/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L1426-L1427



> Setup your healthcheck handler in the way it won't report healthy until you're all ready, see
> 
> https://github.com/Netflix/eureka/blob/cac06f4b431ef3c099719dd3ee9af7d8bb2d3bae/eureka-client/src/main/java/com/netflix/discovery/DiscoveryClient.java#L1426-L1427

thanks  ! 
   you means that set eureka.client.healthcheck.enabled: true ?
   I  do it. But It also confuse me , when eureka client starting , the Starting status transfer to UP status in several seconds. then it register to eureka service.  A large number of requests flooded into the eureka client， because it need to connect to downservice, create mysql connnection and so on.... so it fuse soon. So i need enough time to trigger some test to  connect to downservice before  it register

**Comment by troshko111** [comment]
> you means that set eureka.client.healthcheck.enabled: true ?
Not that, the code I pointed to allows to supply custom logic to determine whether your instance should be hearbeating as `UP`, what I suggested was you *do not* report `UP` until you're ready to take traffic. Basically this functionality is already supported and used.
