### ISSUE TITLE
InstanceInfoReplicator.onDemandUpdate() violate java semantics

### ISSUE THREAD

**Issue by Yufeng0918** [Netflix/eureka#1306]
Hi 

I try to understand the eureka client service registration process and go through InstaneInfoReplicator class.  [InstanceInfoReplicator.](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java)onDemandUpdate method contains code "**InstanceInfoReplicator.this.run()**"

```java
public void run() {
       logger.debug("Executing on-demand update of local InstanceInfo");
       Future latestPeriodic = scheduledPeriodicRef.get();
       if (latestPeriodic != null && !latestPeriodic.isDone()) {
                            logger.debug("Canceling the latest scheduled update, it will be rescheduled at the end of on demand update");
                            latestPeriodic.cancel(false);
       }
    
       InstanceInfoReplicator.this.run();
}
```

I think this violate java semantics. run method should run in this way. Runnable should be either run in a new thread which is created on fly or submit Runnable as task into created ThreadPool. Basically, run method should be call asynchronous way.

Please review this session and advice accordingly, thanks.

**Comment by kevinSakura** [comment]
I think it is already running in a thread. `scheduler.submit(new Runnable() {}).`
