### ISSUE TITLE
In the logic of registration, the timeliness of data is not very good. I feel that the time is a little long. Later versions can be optimized

### ISSUE THREAD

**Issue by pengzhengfa** [Netflix/eureka#1315]
In the logic of registration, the timeliness of data is not very good. I feel that the time is a little long. Later versions can be optimized

**Comment by troshko111** [comment]
Can you please elaborate (with some examples ideally)?

**Comment by pengzhengfa** [comment]
@troshko111 You can use the ideas of copyon worite

**Comment by troshko111** [comment]
The action required / problem statement is not clear to me, feel free to reopen if you could please clarify what the issue is, and what is the suggestions.
