### ISSUE TITLE
Missing useage of instance status in InstanceResource.renewLease()

### ISSUE THREAD

**Issue by melochin** [Netflix/eureka#1320]
I'm confused about parameter ``status`` because i can not find any usage about ``status`` in this method.
https://github.com/Netflix/eureka/blob/f84299eada39b422061399d6de5ea98bd9c1e503/eureka-core/src/main/java/com/netflix/eureka/resources/InstanceResource.java#L105-L110

``renewLease`` calls the method ``AbstractInstanceRegistry.renew``. Then, in the method ``renew``, the ``instanceInfo`` is from the eureka server, of course the instance status is also from the eureka server. But i think the ``instanceInfo`` passed into ``getOverriddenInstanceStatus`` should take the ``status`` (the parameter in the renewLease) from the eureka client. 
https://github.com/Netflix/eureka/blob/f84299eada39b422061399d6de5ea98bd9c1e503/eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java#L363-L367

**Comment by troshko111** [comment]
Status is not modified during a lease renewal, it's simply a heartbeat, for any instance info changes, including the status, the client would call
`eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationResource.java:145` -> `eureka-core/src/main/java/com/netflix/eureka/registry/AbstractInstanceRegistry.java:193` which would update the info retaining the existing lease if present.

I believe it could have been used to change the status in the past, but seems to be a super old thing.
