### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Netflix/eureka#1336]
https://github.com/Netflix/eureka/blob/21b4529acf4a4f18db3b2fada3a40e15be9792cf/eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/Jersey2ApplicationClientFactory.java#L200

The program can potentially fail to release a system resource.

**Comment by abracadv8** [comment]
I can submit a quick pr - is there a corporate CLA?

I'll just wrap it in a `finally` similar to how it's done in other sections of the code like here: https://github.com/Netflix/eureka/blob/master/eureka-client-jersey2/src/main/java/com/netflix/discovery/shared/transport/jersey2/EurekaJersey2ClientImpl.java#L313

**Comment by troshko111** [comment]
Nope, no CLA, PRs welcome!
