### ISSUE TITLE
Will Eureka fix instance expired judgement code in 2.X

### ISSUE THREAD

**Issue by kyangcmXF** [Netflix/eureka#1341]
Hi,
I found eureka comment about expired judgement code in lease.java. The judgement uses double duration to judge whether it is expired. I'd like to know whether eureka will fix it in newest milestone version such as 2.0 ?

**Comment by troshko111** [comment]
Hi, the `2.x` has been abandoned and will not be getting any investment in its current form. This does not mean the development can't continue by the community.
