### ISSUE TITLE
Integrating Angular 8 with Paystack payment gateway

### ISSUE THREAD

**Issue by Raghavanbn** [Netflix/eureka#1348]
I am new to payment gateway integration with Angular. In my project, I need to integrate angular 8 with Paystack API. I could not see any Paystack module available in angular8, but it is in Angular4. Could anyone suggest whether this has been deprecated or I can use the Angular4 module in Angular8?

**Comment by Raghavanbn** [comment]
I didn't get you sorry!

**Comment by spencergibb** [comment]
Why are you asking about angular and paystack in eureka? They seem unrelated

**Comment by Raghavanbn** [comment]
it is not related to eureka, wrongly posted in this repo. that's my bad
