### ISSUE TITLE
non-java server register to eureka

### ISSUE THREAD

**Issue by DEVINccp** [Netflix/eureka#1364]
Can a non-java server register to eureka?
My server is  a go server, I want to register to eureka? Can I do this?

**Comment by tomartarun89** [comment]
Yes, it is possible.

**Comment by DEVINccp** [comment]
> Yes, it is possible.

Ok, I will hava a try. thank you.

**Comment by troshko111** [comment]
You can implement a lightweight client / sidecar, only these APIs are necessary for registration:

Register, update (including state): `POST $ADDR/discovery/v2/apps/$APP`
Heartbeat: `PUT "$ADDR/discovery/v2/apps/$APP/$INSTANCE_ID?status=${current_status}&lastDirtyTimestamp=$last_reg"`
Gracefully de-register (optional): `DELETE $ADDR/discovery/v2/apps/$APP/$INSTANCE_ID`

Status transitions are:
`STARTING` -> `UP` (should not do `STARTING` -> `DOWN`, keep in `STARTING` until becomes healthy)
`UP` <-> `DOWN`

Hope this helps.

**Comment by DEVINccp** [comment]
ok, I completed the work through your hint, Thx
