### ISSUE TITLE
what is the param app-group-name in Eureka use for?

### ISSUE THREAD

**Issue by qushihaoji** [Netflix/eureka#1368]
now in same zone， we have same business but with different profile. like test and prod environment, and I want to use same eureka, how can I do that ?  
I know I can give a different name for test and prod enviromnet, but besides this ,is any other ways to do that ?I see the source code, found param app-group-name ,what the param use for?

[another disscuss can be saw here](https://github.com/spring-cloud/spring-cloud-netflix/issues/3512)
[here](https://github.com/spring-cloud/spring-cloud-netflix/issues/3141)

**Comment by troshko111** [comment]
`appGroupName` does not seem to serve any specific purpose any more and looks to be largely unused. Looks like an artifact from the past to me.

I did not fully get the first question though, can you elaborate?
