### ISSUE TITLE
Introduce rate limiting for eureka server

### ISSUE THREAD

**Issue by NiteshKant** [Netflix/eureka#137]
Eureka servers assumes well behaving clients, i.e.:

- Clients do not aggressively query the servers for data.
- Clients do not do full registry calls but do delta updates.

Although most of the clients use the provided eureka client but there may be some offending clients which do not behave well. These clients can potentially bring down the server by throwing a high amount of load on the server and hence penalizing the other well behaved clients.

Eureka servers should apply quotas for clients based on different criterions:

- Same client.
- Same application.

**Comment by tbak** [comment]
Rate limiter functionality was implemented for Eureka 1.0. The rate limiting is performed only for full/delta/application fetches. There are two quotas. One for all query types, and a dedicated one for the full registry fetch.
