### ISSUE TITLE
Help me to see a problem，Multiple Eureka deployed on one server

### ISSUE THREAD

**Issue by eighthw** [Netflix/eureka#1373]
I deployed multiple Eureka on a server, one 8761 and one 7001. I started a microservice and configured to register with 7001, but 8761 will also be registered by default. How can I make it not register port 8761 by default.

server.port: 7002      #Change the built-in server port#
spring:
  application:
    name: configserver
  profiles:
    active: native     

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address:${spring.cloud.client.ip-address}}:${spring.application.instance_id:${server.port}}:${spring.application.name}

**Comment by troshko111** [comment]
Set the port/secure port on the client explicitly to the one you're registering.
