### ISSUE TITLE
Eureka connectionIdleTimeout assignment error!!!

### ISSUE THREAD

**Issue by UFO-Coder** [Netflix/eureka#1374]
In eureka-client version 1.9.3 or old version,I'm not sure if this problem still exists in the new version. com.net flix. Discovery. Shared. Transport. EurekaClientFactoryBuilder# connectionIdleTimeout field assignment to transform the default 30 s to ms.But in com.net flix. Discovery. Shared. Transport. Jersey# cleanIdle in use, it is to use as the seconds, cause connectionIdleTimeout values be enlarged 1000 times, long connection cannot receive timely detection of destruction.

**Comment by UFO-Coder** [comment]
![image](https://user-images.githubusercontent.com/53501500/103216863-0d0c7c00-4952-11eb-9d01-ab5fd3e0091f.png)
![image](https://user-images.githubusercontent.com/53501500/103216886-1bf32e80-4952-11eb-92ee-f60eb9a7855d.png)

**Comment by holy12345** [comment]
Hi
try use the lastest version

**Comment by holy12345** [comment]
Hi
I checked the source code of version `1.9.25` . In the `Eurekaclientfactorybuilder` class, the code has been fixed, and the above problem does not appear. 
```
    public B withClientConfig(EurekaClientConfig clientConfig) {
        withClientAccept(EurekaAccept.fromString(clientConfig.getClientDataAccept()));
        withAllowRedirect(clientConfig.allowRedirects());
        withConnectionTimeout(clientConfig.getEurekaServerConnectTimeoutSeconds() * 1000);
        withReadTimeout(clientConfig.getEurekaServerReadTimeoutSeconds() * 1000);
        withMaxConnectionsPerHost(clientConfig.getEurekaServerTotalConnectionsPerHost());
        withMaxTotalConnections(clientConfig.getEurekaServerTotalConnections());
        withConnectionIdleTimeout(clientConfig.getEurekaConnectionIdleTimeoutSeconds());
        withEncoder(clientConfig.getEncoderName());
        return withDecoder(clientConfig.getDecoderName(), clientConfig.getClientDataAccept());
    }
```

Any thoughts?
