### ISSUE TITLE
Ignore interfaces in eureka service

### ISSUE THREAD

**Issue by Rex-Legor** [Netflix/eureka#1382]
**Is this a bug: No, just a question, possibly a new feature suggestion**

**Problem:**
is there a way to ignore or exclude clients in my eureka server based on their ip address? or something like this?

currently we have 100+ services up and running connecting to different eureka servers,
and we would like to avoid registering client services if they are running locally,
since we have a lot of services with a lot of people working with them removing their `@EnableEurekaClient` annotation every time we run it locally can be annoying, or any similar workaround.

**So I'm looking for a way to prevent services from getting registered in the eureka server by modifying my eureka server, not my clients,**

Thanks.

**Comment by mattnelson** [comment]
If the config can be flexed locally, the `eureka.registration.enabled` property can be used to skip client registration.
