### ISSUE TITLE
eureka-client: JsonParseException while getAndStoreFullRegistry() triggered by contextRefresher

### ISSUE THREAD

**Issue by jianbo-chen** [Netflix/eureka#1384]
env and dependence desc

- eureka-client version: 1.4.5.RELEASE

- JDK version: 1.8.202

- spring-cloud-netflix-eureka-client version: 2.1.0.RELEASE

On eureka-server side  we have 2 servers and they belong to a same zone ;

it happened about 5 times exception in this month, 
we found some errors from logs ,  DiscoveryClient tried both 2 eureka-server but it both tuned out to print this error log.

this is the one of  exception messages :
![image](https://user-images.githubusercontent.com/23950694/112313094-72b69d00-8ce2-11eb-8f78-36f962832f79.png)

according to this error log, it happens on this line of code :
eureka/eureka-client/com.netflix.discovery/DiscoveryClient.java
Line 1050 

this error doesn't always get thrown , so we are unable to debug locally. 

according to the error logs on prod envirement,
we found out that the error hadn't happened, however, while we push the apollo(https://github.com/ctripcorp/apollo) configs which we have written a refreshListener to refresh config bean, the error may happen. The codes of the Listener are shown below:
![image](https://user-images.githubusercontent.com/23950694/112314097-94fcea80-8ce3-11eb-9c65-2d71e0f2f826.png)

this refresh event would refresh the DiscoveryClient bean and sometimes
would throw the JsonParseException while request the fullRegistry.

Can you please advice me, are we doing something wrong or could this be a bug?

**Comment by troshko111** [comment]
It gets aborted if loading the full Discovery state and parsing it takes over 30s (the default value I believe), so you need to hunt down whatever is causing this to be so slow (local CPU thrashing, slow network, etc.)

**Comment by jianbo-chen** [comment]
> It gets aborted if loading the full Discovery state and parsing it takes over 30s (the default value I believe), so you need to hunt down whatever is causing this to be so slow (local CPU thrashing, slow network, etc.)

Thanks for your answer,  we added an monitor to eureka server  and  upgraded my eureka server version to 2.1.0.RELEASE  which is the same as client eureka version, then this error has never showed again for now.
