### ISSUE TITLE
Action execution failed Parameters:

### ISSUE THREAD

**Issue by usmanbinnaeem** [Netflix/eureka#1423]
Hey!  I created a pipeline for my cdk-backend in which i am using APIGateway, lambda functions and dynamodb.
I am getting this error in my deploying stage:

Action execution failed
Parameters: [AssetParameters74e1c940fa063c9ea88baaaa5bc6287dd4ee1ff6bb7cd9c66f2afb92067be00dS3Bucket3DC33554, AssetParameters74e1c940fa063c9ea88baaaa5bc6287dd4ee1ff6bb7cd9c66f2afb92067be00dS3VersionKey27AA43A8, AssetParameters74e1c940fa063c9ea88baaaa5bc6287dd4ee1ff6bb7cd9c66f2afb92067be00dArtifactHash4EED51D1] must have values (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 8733cfcc-6c3f-4260-a968-9ecb546c972a; Proxy: null)

![Screenshot from 2021-08-30 14-27-42](https://user-images.githubusercontent.com/61014982/131318253-5b06a01d-5cc8-40a1-924a-5eb8d2c03efd.png)
![Screenshot from 2021-08-30 14-28-03](https://user-images.githubusercontent.com/61014982/131318261-1ae5f5ee-cc6d-4626-9673-04fcabc28c4a.png)

**Comment by troshko111** [comment]
I don't see how this is related to Eureka, and even if this were, given 0 details it won't be possible to help.
