### ISSUE TITLE
Can Eureka server hold N number of crashed instance's details? - Question

### ISSUE THREAD

**Issue by hariraogotit** [Netflix/eureka#1435]
Team,

   I am using Eureka server and clients are registering to the server. 

1. After each client registering to eureka server, it uses the instance id given by Eureka server as lock in Redis
2. When one of the client (or instance) crash a new one is spun up but
3. I want to inform new instance that the previous instance crashed and it has to now process previous instance's work from Redis.
4. In order to perform I can employ an external tool but would like to know if Eureka some how holds say N crashed instance's details?
5. If it holds then that will make my job easy.

Kindly confirm.

**Comment by troshko111** [comment]
This use case is likely a poor fit for Eureka, Eureka is eventually consistent and even the "crash" won't be immediately recorded by Eureka, the crashed instance will miss 2 heartbeats and will get evicted, that's also the answer to your question on if Eureka holds crashed instances (no).

Based on the description you posted here, it sounds to me like you're sharding some work and want the shard leader to be the sole processor at any given time.

I suggest you partition the work and elect the leader within each partition for processing, look into distributed locking, depending what type of guarantees you want it may be totally doable with Redis itself.
