### ISSUE TITLE
REST documentation fix

### ISSUE THREAD

**Issue by dmakvh** [Netflix/eureka#1436]
please see [this link](https://github.com/Netflix/eureka/compare/master...dmakvh:bugfix/REST-documentation?diff=unified), the current documentation forgets to mention that the HTTP ACCEPT header also needs to be set ... otherwise XML is returned on every occasion.

Also : you guys should allow branches and pull-requests for everyone - as long as the master is protected your work will never be in danger.

**Comment by troshko111** [comment]
SGTM, want to send a quick PR?

**Comment by dmakvh** [comment]
it is impossible to create branches, hence noone can create PRs ... like i mentioned.

**Comment by brharrington** [comment]
You do not need to be able to create a branch in this project for a PR. Fork the project and then create the PR from your fork:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by dmakvh** [comment]
it is impossible to create a pull request for a **wiki**-repository : https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by troshko111** [comment]
Never bumped into this, let me try to repro.

**Comment by troshko111** [comment]
huh, you're right, this is pretty terrible, I have not used this feature much before, for some reason I thought this was just a special recognized folder in the repo GH built a wiki off, but no, it's a separate thing which does not support any collab. Now I understand why people don't use it much. I will cherry pick your changes, thanks.
