### ISSUE TITLE
Benchmarking eureka service discovery performance

### ISSUE THREAD

**Issue by sahith** [Netflix/eureka#1438]
Can someone point me to the documentation/blog where eureka performance is measured? In specific, I want to know the answer for the following questions

1. What is the response time from server when eureka client makes a read/write request?
2. How many service instances can be supported by Eureka?
3. How many concurrent requests can be supported from eureka client to server?
4.  How much memory/CPU is consumed by Eureka host?
5. What are the network bandwidth constraints/limits of Eureka?

I believe above are the important questions to be answered and included in the documentation for comparing performance against other service discovery solutions out there

**Comment by troshko111** [comment]
We don't publish such thing, rough answers:

> What is the response time from server when eureka client makes a read/write request?

Depends on the request, your server config and your hardware config.

> How many service instances can be supported by Eureka?

The only real limitation is the client registry sync/polling which would use some net bandwidth and mem, if that's not required you can go orders of magnitude higher. Even if it is, millions of instances is fine as long as you're willing to spend some JVM heap space (single digit GBs) on clients following such registry.

> How many concurrent requests can be supported from eureka client to server?

However many your server setup supports, there's nothing inherently blocking horizontal scalability in Eureka itself, your bottleneck should be network.

> How much memory/CPU is consumed by Eureka host?

Which host, the client or the server? Regardless, linearly proportionate to the registry size.

> What are the network bandwidth constraints/limits of Eureka?

Your network bandwidth assuming the server is adequately setup.

> I believe above are the important questions to be answered and included in the documentation for comparing performance against other service discovery solutions out there


This may be the first time somebody asked this, so arguably this is rather unimportant. Service Discovery is an inherently async system, and I would say that metrics such as change propagation and failure modes are much more important than any of the above questions (which you would not need to even worry about until you get into millions of instances, which not everyone does).
