### ISSUE TITLE
bridging eureka and archaius configs

### ISSUE THREAD

**Issue by cfregly** [Netflix/eureka#17]
is there a way to avoid the following code snippet used to bridge the archaius and eureka configs:

https://github.com/cfregly/fluxcapacitor/blob/master/flux-edge/src/main/java/com/fluxcapacitor/edge/server/EdgeServer.java

i understand the desire to let eureka run standalone without requiring an archaius configuration, but is there a best-of-both-worlds approach where archaius will be used if these properties don't exist, maybe?

lemme know.

-chris

**Comment by qiangdavidliu** [comment]
Closing old issue. Please re-open if the issue is still not resolved.
