### ISSUE TITLE
Guaranteed instance id uniqueness 

### ISSUE THREAD

**Issue by tbak** [Netflix/eureka#181]
Current Eureka design assumes that clients choose their instance id, and submit it to the Eureka server during registration process. It has some pros/cons versus reversed process, where the server assigns an id to a client and sends it back in a reply to a registration request.

**Client side instance id assignment**
Pros:
* client can choose their own naming schema (use instance id in AWS, or IP address or a descriptive name like backend-server-X)

Cons:
* client is responsible for instance id uniqueness, across multiple applications
* Eureka server must be able to detect situations where the same id is used by multiple different clients (when the id uniqueness contract is violated by clients)

**Server side instance id assignment**
Pros:
* clients are relieved from assigning globally unique ids
* no problem with misbehaving clients

Cons:
* it is difficult to generate compact, descriptive and unique ids in a distributed system. For example ip address itself is not enough (can be reassigned).
* using UUIDs would solve the uniqueness problem, but would leave us with long and cryptic ids

**Comment by futurely** [comment]
Why not both ids?
```
class GloballyUniqueIDs {
  String clientID;
  String serverID;
   ...
}
```

**Comment by qiangdavidliu** [comment]
Thanks for the suggestion @futurely . That's an interesting idea and we will look into it.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
