### ISSUE TITLE
Client usage parity between 1.x and 2.x

### ISSUE THREAD

**Issue by NiteshKant** [Netflix/eureka#184]
#### Problem

How do we want people using eureka, primarily from the point of view of using eureka client, move from 1.x to 2.x stack?

#### Scope

- This obviously does not cover things that we are improving i.e. new APIs.
- This applies to things like InstanceInfo, DatacenterInfo, InstanceStatus, Healthcheck, etc which are plugin points for users and cause pain when changed.

**Comment by futurely** [comment]
Sync API over async implementation may not be beneficial.
[Should I expose synchronous wrappers for asynchronous methods?](http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx)
[Good practice - Use the sync-over-async invocation pattern with caution](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W7b59e5e25210_4b56_9b7e_69dab379734a/page/Good%20practice%20-%20%20Use%20the%20sync-over-async%20invocation%20pattern%20with%20caution)

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
