### ISSUE TITLE
Hostname reused as InstanceId disallows multiple service instances on 1 host

### ISSUE THREAD

**Issue by danielkwinsor** [Netflix/eureka#24]
Original thread is at https://groups.google.com/forum/#!topic/eureka_netflix/Rntihgo1i50

My usecase is that I'd like to have 1 service with multiple instances running on the same host.  Since they are the same service, they should have the same app name.  And since they are on the same host, they have the same hostname.  The problem is that in a non-AWS datacenter, the instanceID is populated by the hostname.  Same app name and same instanceId leads to overwriting in the service registry.  I would appreciate it if the EurekaInstanceConfig interface had a getId() method that I can implement.

Thank you.

**Comment by qiangdavidliu** [comment]
This is possible by implementing a DataCenterInfo that also implement UniqueIdentifier.
