### ISSUE TITLE
2.x Servo Dependency - Separate as Plugin

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/eureka#262]
The Servo dependency should be removed from Eureka 2 and replaced instead with an optional Metrics Publisher plugin since many companies don't use Servo and it should not be a requirement or compile time dependency.

Instead a plugin should be usable to use alternatives such as Yammer/Codahale Metrics or Servo via a plugin implementation.

Example plugins:

- https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-servo-metrics-publisher
- https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-yammer-metrics-publisher
- https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-codahale-metrics-publisher

**Comment by tbak** [comment]
Eureka 2.0 comes now with set of interfaces for metrics integration. 
There are two implementations provided:
- NoOp - void implementation, set by default for eureka-client
- spectator plugin

**Comment by benjchristensen** [comment]
+1
