### ISSUE TITLE
java.lang.String cannot be cast to org.gradle.api.artifacts.Configuration

### ISSUE THREAD

**Issue by ddatsh** [Netflix/eureka#321]
------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Windows 7 6.1 amd64

=================================
when run gradle,then 

FAILURE: Build failed with an exception.

* Where:
Script 'E:\git\eureka\gradle\convention.gradle' line: 24

* What went wrong:
A problem occurred evaluating script.
> java.lang.String cannot be cast to org.gradle.api.artifacts.Configuration

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tbak** [comment]
Eureka was built previously with gradle 1.x. It has just been upgraded to gradle 2.x with a new nebula plugin. All scripts in gradle folder have been removed.
Please, try it again. Do not run your system installed gradle, but call ./gradlew which will execute configured gradle wrapper for Eureka.

**Comment by tbak** [comment]
@ddatsh Have you tried to build Eureka using the provided wrapper? If there were no other problems with that I would like to close this issue.
