### ISSUE TITLE
Eureka2 BasicDataCenterInfo typo

### ISSUE THREAD

**Issue by futurely** [Netflix/eureka#380]
https://github.com/Netflix/eureka/blob/2.x/eureka2-core/src/main/java/com/netflix/eureka2/registry/datacenter/BasicDataCenterInfo.java

```
public NetworkAddress getDefaultAddress() {
        if (defaultAddress != null) {
            return defaultAddress;
        }
        if (addresses == null | addresses.isEmpty()) {
```
The last line should be ` if (addresses == null || addresses.isEmpty()) {`.

**Comment by qiangdavidliu** [comment]
Thanks for the catch.

**Comment by qiangdavidliu** [comment]
fixed
