### ISSUE TITLE
2.x Client API Re-organisation

### ISSUE THREAD

**Issue by qiangdavidliu** [Netflix/eureka#409]
# Problem to Address
The current eurekaClient public API exposes registrations and interest discovery in the following way:
* registration and updates are handled by sequential calls to register(info), and unregistration by a separate unregister(info) method. Both of these methods return an Observable<Void> that denotes the success/failure of the given operation. The problem with this API is that callers are more interested in the lifecycle of the instance's overall registration as opposed to the success/failure of individual calls.

* forInterest today returns a stream of ChangeNotifications that contain instance level data. In practical use, it is common for consumers to want to wait and buffer this data into lists of suitable size before consumption. As of today, we are missing both a mechanism to detect suitable buffer windows, as well as an API and/or suitable default operators to do the buffering.

# Proposal
## Registration API
```java
    /**
     * Given an Observable of InstanceInfo that represent the register and subsequent updates of the instance to be
     * registered, registers and updates this instance.
     * 
     * @param instanceToRegister an Observable that emits an InstanceInfo whenever relevant information for this
     *                           instance has changed and need to be updated server side.
     * @return an Observable RegistrationResponse that starts the registration when subscribed to, and unregisters
     *         when unsubscribed to. The RegistrationResponse is an Observable<Void> that represent the registration
     *         lifecycle of the instance, and will onError if the instance registration is disconnected from the
     *         server due to client errors.
     *         The RegistrationResponse optionally contains an Observable<Void> that can be subscribed to for
     *         onCompleted (success) or onError (failure) of the initial registration.
     */
    public RegistrationResponse register(Observable<InstanceInfo> instanceToRegister) {

    }
```

## Interest API
The current API should remain unchanged, however hint markers should be emitted by the stream for batching hints (issue #384). Additionally, standard operators should be provided for the stream to achieve buffering (see below for operators to be provided.).

## Registration Helpers
* The [SelfRegistrationService and SelfInfoResolver](https://github.com/Netflix/eureka/tree/2.x/eureka2-server/src/main/java/com/netflix/eureka2/server/service) currently used by the servers should be generalised for client use, so that we can componentize the creation of different parts of an InstanceInfo (e.g. user provided fields, network auto-discovery, health monitoring) and then merge these together for registration.

## ForInterest Operators
(Some of these operators may be straightforward enough that we should just provide a best practice example using standard operators).
* A buffer(long time, TimeUnit unit) operator that return a stream of ChangeNotifications, such that nothing is emitted until a buffer marker is received, then all notifications buffered up to the marker is emitted. A timeout is provided for the length of time to wait between each marker.
* A CollectToSnapshot() operator that transforms the stream of ChangeNotifications into a stream of Lists, where the lists returned contain snapshots of interest data. When any member of the interest set changes, a new snapshot list emitted.
* A GroupBy(Key) operator should be provided that groups the single ChangeNotification stream to a set of streams based on the groupBy key (e.g. groupBy VipAddress).

**Comment by NiteshKant** [comment]
@qiangdavidliu the changes look good to me. I do have a few questions:

> The SelfRegistrationService and SelfInfoResolver currently used by the servers should be generalised for client use, so that we can componentize the creation of different parts of an InstanceInfo

Does this mean that a client will have a to use a helper class for registration?
I am not convinced that we should go that route. If `InstanceInfo` is complex to create, we should provide ways in `InstanceInfo` to make it easier to use, as opposed to having a separate class that does so. The reason being intuitiveness of the API if a user has to look at a bunch of classes to do registration.

Since, we are on the topic of Client API changes, do you intend to create another issue for creating complex Interest sets. eg: How does one create a cumulative interest for a VIP + an app + secure VIP (of course this is hypothetical)?

I remember us briefly discussing the need of a DSL for that, somewhat like:

```java
client.forInterest(Interests.forVip("vip1"))
        .andApplication("app1").orInstance("I1")
```

The above DSL is capturing a modifiable interest set which can be subscribed at any branching point.

**Comment by qiangdavidliu** [comment]
This issue is still pending a part 2 clean up of the client builder.

**Comment by qiangdavidliu** [comment]
Issue resolve per pull requests #426 and #444
