### ISSUE TITLE
getDispatcherType() is undefined for the type HttpServletRequest

### ISSUE THREAD

**Issue by ddatsh** [Netflix/eureka#414]
eureka-server-1.1.148-SNAPSHOT
tomcat 8

org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [jsp] in context with path [/eureka] threw exception [Unable to compile class for JSP: 

An error occurred at line: [53] in the generated java file: [D:\dev\java\server\tomcat\8\work\Catalina\localhost\eureka\org\apache\jsp\jsp\status_jsp.java]
The method getDispatcherType() is undefined for the type HttpServletRequest

Stacktrace:] with root cause
 org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: [53] in the generated java file: [D:\dev\java\server\tomcat\8\work\Catalina\localhost\eureka\org\apache\jsp\jsp\status_jsp.java]
The method getDispatcherType() is undefined for the type HttpServletRequest

**Comment by qiangdavidliu** [comment]
@ddatsh are you running this in an IDE or on the command line?

**Comment by ddatsh** [comment]
run it in tomcat 8

**Comment by tbak** [comment]
We have transitive dependency that includes servlet-api 2.5 jar into eureka.war. The one eureka depends on directly (version 2.4) is marked as provided. I have just fixed that, and now I am able to run Eureka UI on tomcat 8.

**Comment by tbak** [comment]
I have just pushed a PR for this bug (#416).
