### ISSUE TITLE
Gradle build fails for ZIP file

### ISSUE THREAD

**Issue by teeratpitakrat** [Netflix/eureka#425]
The build fails when building the downloaded zip file:
```
$ unzip eureka-master.zip
$ cd eureka-master
$ ./gradlew clean build

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/eureka-master/build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.4']
> repository not found: /tmp/eureka-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
The problem seems to be the missing .git folder. Building the clone with .git removed results in the same problem.
Tested on Ubuntu 12.04.5 LTS and Archlinux.

**Comment by qiangdavidliu** [comment]
Hi @teeratpitakrat unfortunately our new build process requires git pull if you are building from source. Is this a blocking issue for you w.r.t. using eureka?

**Comment by teeratpitakrat** [comment]
Hi @qiangdavidliu, I was trying to add eureka as a submodule inside another git project. Then, git modified .git folder of eureka and caused this problem.

My temporary solution is to clone eureka and put it inside that git project without committing (which is a little inconvenient).
It would be great if eureka can be built without the dependency to git.

**Comment by qiangdavidliu** [comment]
@teeratpitakrat do you need to edit source code? If not, why not just depend on the published eureka artifacts?

**Comment by teeratpitakrat** [comment]
@qiangdavidliu Unfortunately, I need to edit the source code.

**Comment by qiangdavidliu** [comment]
@teeratpitakrat unfortunately it looks our new build process does not allow eureka to be used as a git submodule inside another project. If your changes to eureka are not domain specific for your case, feel free to send us pull requests. If you would like to make changes to the build files to enable submoduling, that would be appreciated also.

**Comment by tbak** [comment]
As there was no follow up on this issue for long time, I am closing it.
