### ISSUE TITLE
CloudBees embedded build status showing 'unknown'

### ISSUE THREAD

**Issue by charleswhchan** [Netflix/eureka#431]
The embedded build status defined in README.md is currently showing 'unknown'.

Performs a configuration issue? According to the Embeddable Build Status Icon page:
https://netflixoss.ci.cloudbees.com/job/eureka-master/badge/
> If you want the status icons to be public readable/accessible, just grant the ViewStatus permission globally to anonymous.

**Comment by tbak** [comment]
Thank you for spotting this. We created recently a new Jenkins build job for Eureka at different location. I have pushed fix for this (#432).

**Comment by charleswhchan** [comment]
Thanks!
