### ISSUE TITLE
2.x Eureka server health monitoring

### ISSUE THREAD

**Issue by tbak** [Netflix/eureka#439]
Eureka 2.0 health monitoring

# Concept

Each Eureka component manages its own health information, which is aggregated in one place where overall system health status is derived.

A component that wishes to provide its health status must implement:
```java
public interface HealthStatusProvider<SUBSYSTEM> {

   Observable<HealthStatusUpdate<SUBSYSTEM>> healthStatus();
}
```
```healthStatus``` method returns an observable of health status changes. The returned observable shall never emit an error, and should complete when the subsystem is shut down. Status value represents internal state of the component.  The health status information is captured in ```HealthStatusUpdate``` object:

```java
public class HealthStatusUpdate<SUBSYSTEM> {

    public HealthStatusUpdate(Status status,
                              SubsystemDescriptor<SUBSYSTEM> description) {
      ...
    }

    public STATUS getStatus() { }

    public SubsystemDescriptor<SUBSYSTEM> getDescriptor() { }
}
```

```SubsystemDescriptor``` JavaBean provides static, supplementary information primary for UIs.

The aggregation logic is captured in ```HealthStatusAggregator``` class, which itself extends ```HealthStatusProvider```. Apart for returning the aggregated state, it provides access to its underlying components:
```java
public interface HealthStatusAggregator<SUBSYSTEM extends HealthStatusAggregator<SUBSYSTEM>>
        extends HealthStatusProvider<SUBSYSTEM> {
    List<HealthStatusProvider<?>> components();
}
```

# Eureka server self registration

Eureka self registration service subscribes to ```HealthStatusAggregator```, and updates its own ```InstanceInfo.status``` accordingly, which gets immediately propagated to Eureka registry.

# External Health check API 

## REST API

Current Eureka health status can be accessed via REST GET method call:
```
curl -X GET http://eureka.host/eureka/health

HTTP/1.1 200 OK
HEALTHY
```

## WebSockets API

Clients wishing to receive live updates about Eureka health status, can connect to WebSocket endpoint:
```
open ws://eureka.host/eureka/ws/health

text-message: {
    "descriptor":{
        "title":"Client interest channel",
        "description":"...",
        "type":"InterestChannel"
    },
    "status":"DOWN"
}
text-message: {
	"descriptor":{
		"title":"Aggregated health check status",
		"description":"...",
		"type":"EurekaHealthStatusAggregator"
	},
	"status":"DOWN",
}
...
text-message: {
	"descriptor": {
		"title":"Client interest channel",
		"description":"..."
	},
	"status":"UP",
}
text-message: {
	"descriptor":{
		"title":"Aggregated health check status",
		"description":"...",
		"type":"EurekaHealthStatusAggregator"
	},
	"status":"UP",
}

```

# Karyon Admin UI

Aggregated and component level health check status values are exposed via a new Karyon admin UI tab. The associated ```SubsystemDescriptor``` objects provide descriptive information about each component, and possible states.

**Comment by NiteshKant** [comment]
>> For example channel might be in { Idle, Connected, Closed } states. These states must be mapped to Eureka InstanceInfo.State.

Is there a value in having these as two different Status? IOW, why not have the components return `InstanceInfo.State`?

>> SubsystemDescriptor JavaBean provides static, supplementary information primary for UIs

I think we are conflating the health status with this granular information. 

Bigger question: "Can the subsystem status better be exposed via metrics and have the system health as _a_ status, potentially aggregated over multiple sources?"

>> Clients wishing to receive live updates about Eureka health status can connect to WebSocket endpoint

In absence of subsystem statuses, Is this just the `forInterest` endpoint otherwise available for any interest in eureka?

**Comment by qiangdavidliu** [comment]
This proposal, taken from a more generic perspective, seems like something that would be an interface in Karyon and services built on top should provide specific implementations. It should then be Karyon's responsibility to feed the aggregated status back to eureka for eureka status.

**Comment by tbak** [comment]
> Is there a value in having these as two different Status? IOW, why not have the components return InstanceInfo.State?

I would like to expose internal system health, so having original status values is beneficial.

> I think we are conflating the health status with this granular information.

It is not health status in a sense we have it for external application monitoring. The point here is to have access to this granular information.

> Bigger question: "Can the subsystem status better be exposed via metrics and have the system health > as a status, potentially aggregated over multiple sources?"

Metrics are a must, and they are orthogonal to current status monitoring. Metric values could be collected from local counters (not remote monitoring system), and exposed as an additional insight information.

> In absence of subsystem statuses, Is this just the forInterest endpoint otherwise available for any interest in eureka?

Using forInterest would incur additional delay, and if read node is disconnected from write server, it would  never provide up to date value. But the whole point of my proposal is to expose internal component status, as an additional insight information.

**Comment by tbak** [comment]
Following the discussion I am removing component specific STATE type parameter. Each component will emit InstanceInfo.Status values. This will simplify API and implementation. If we find it too restrictive (we are now limited practically to DOWN/UP status values with no way to express partial component failures), we may consider putting it back in the future.
