### ISSUE TITLE
Is it possible to use a generic data synchronization framework?

### ISSUE THREAD

**Issue by futurely** [Netflix/eureka#450]
For example, "AeroGear data synchronization project is an implementation of Google's Differential Synchonrization by Neil Fraser".
https://github.com/aerogear/aerogear-sync-server
https://aerogear.org/sync/
https://aerogear.org/docs/specs/aerogear-data-sync/

**Comment by qiangdavidliu** [comment]
@futurely we will take a look into this. Thanks for the links.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
