### ISSUE TITLE
Eureka2 DP Release

### ISSUE THREAD

**Issue by benjchristensen** [Netflix/eureka#462]
The last release DP4 was in December, are you in a position to provide another release? I'm interested in doing further testing with it in the ReactiveLab project.

**Comment by qiangdavidliu** [comment]
We are pretty close to doing an RC1 release. We were hoping to do this this week but wanted to double check some server-side metrics so right now RC1 is looking to be next week. Would that be soon enough for you?

**Comment by benjchristensen** [comment]
Next week is good. Thank you.

**Comment by qiangdavidliu** [comment]
@benjchristensen rc.1 is now released and we have updated wiki documentation as well for configuration and use. Please take a look at: 
* https://github.com/Netflix/eureka/wiki/Eureka-2.0-Client-Configuration-And-Use
* https://github.com/Netflix/eureka/wiki/Eureka-2.0-Server-Configuration-And-Use
