### ISSUE TITLE
2.x Replace replication channel with Interest channel

### ISSUE THREAD

**Issue by qiangdavidliu** [Netflix/eureka#485]
The current replication channel connections are very similar to the interest channels, with the exception that interest channels are client initiated and replication channels are server initiated. This needs not be the case. Related to issue #484, if all channels provide an initial handshake, we can remove replication channels completely and just use the interest channels for write server replication needs.

**Comment by NiteshKant** [comment]
>> The current replication channel connections are very similar to the interest channels, with the exception that interest channels are client initiated and replication channels are server initiated.

Are you referring to the similarity as the data that flows on the channel or how the Channel is implemented on client and server? 
Semantics of storage, heartbeats and expiries are very different for a replication channel, isn't?

**Comment by qiangdavidliu** [comment]
Correct, however the semantic differences can be either merge in the future (e.g. in the case of expiry with a better eviction mechanism) or are better applied at a higher level (such as in the case of storage).

**Comment by NiteshKant** [comment]
May be it will be better to see the implementation to better understand your thoughts. So, let me hold on till then :)

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
