### ISSUE TITLE
Wrong enum in documentation

### ISSUE THREAD

**Issue by dmelani** [Netflix/eureka#498]
There is an error with one of the examples on the wiki page where the REST operations are listed.

The page in question is https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

The erroneous example is "Take instance out of service". The problem here is that this example uses the enum OUT_OF_SERVICE, which is not defined in the XSD.

**Comment by tbak** [comment]
XSD documentation was incomplete. I have added missing two states (OUT_OF_SERVICE and UNKNOWN).
Thank you for spotting this.
