### ISSUE TITLE
2.x Named Eureka Server Groups

### ISSUE THREAD

**Issue by qiangdavidliu** [Netflix/eureka#502]
## Problem To Solve
Eureka2 write is designed so that a full network can be partitioned into several eureka2 sub-networks, where each sub-network contains an eureka2 write cluster taking registrations from all instances from their sub-network. One example of such a setup is deployment in AWS's regional model, where an eureka2 write cluster need to exist per region to service registrations from all instances in that region.

In normal cases an eureka2 read cluster that exist in sub-network A (e.g. us-east-1) only need to connect to it's local write cluster for interest information. However there are cases where read clusters may need to (in addition to the local write cluster) also connect to one or more remote write clusters for informations, and/or to one or more remote read clusters for information (since interest subscriptions can be served from write or read servers analogously).

Per the above, for interest subscription, read clusters should not really care about whether it is connecting to a write cluster or a read cluster, or whether it is connecting to a local cluster or a remote cluster. Rather it needs to have some way to specify a set of source "clusters" that are available to provide interest data to this read cluster.

## Named clusters and multiplexing read servers
A proposal to the above problem is to define global unique names for each cluster (write and read), which can then be shared at bootstrap time for a new read cluster as sources of data.

**(Read) Server Side**
When a read server boots up, it will load configuration that specifies all it's known data sources, and for each data source associate an EurekaRegistry and EurekaInterestClient. All the individual named registries will then be proxied by a registry that understands names and can route interest subscriptions to specific registries. The read server need at least one data source defined that is used as the default data source for this read server.

**Configuration example**
<pre>
eureka.interest.dataSource.names=[write-useast1, read-uswest2]  // first one defined in the list is the default

eureka.interest.dataSource.write-useast1.resolverType=dns
eureka.interest.dataSource.write-useast1.serverList=[dnsName:interestPort]
eureka.interest.dataSource.write-useast1.lazyLoad=false

eureka.interest.dataSource.read-uswest2.resolverType=eureka
eureka.interest.dataSource.read-uswest2.serverList=[dnsName:interestPort for west2 write cluster]
eureka.interest.dataSource.read-uswest2.lazyLoad=true
</pre>

**Client Side**
When an eureka2 client communicates with a read server for interest subscription, it can optionally specify a dataSource as well. When the interest subscription is received by the read server, it will attempt to route the interest subscription to the correct registry for the specified dataSource. If no dataSource is specified, the default dataSource is used.

**Client API Change**
Extend Interest to be able to optionally specify a source.
```java
public abstract class Interest<T> {

    public enum Operator {Equals, Like}
    private final String sourceName;

    protected Interest() {
        this(null);
    }

    protected Interest(String sourceName) {
        this.sourceName = sourceName;
    }

    public abstract boolean matches(T data);
}
```
The Interests DSL will need to change to accomodate optionally specifying a dataSource, for example
```java
public final class Interests {
    public static class InterestsWithSource {
        private final String sourceName;

        InterestsWithSource(String sourceName) {
            this.sourceName = sourceName;
        }

        // contain all static methods in Interests.java as instance methods, but obeys sourceName
    }

    private static final InterestsWithSource WITH_DEFAULT_SOURCE = new InterestsWithSource(null);
    
    // change all static methods to reference WITH_DEFAULT_SOURCE's equivalent methods.
    
    public InterestsWithSource fromDataSource(String sourceName) {
        return new InterestsWithSource(sourceName);
    }
}
```

Usage would be
```java
Interest interest = Interests.forVip("someVip");  // use default source
Interest interestFromAnotherSource = Interests.fromDataSource("someSource").forVip("someVip");
```

**Comment by NiteshKant** [comment]
Could an alternate be to initialize multiple interest client instances and merge the interest stream if/when required? I do not quiet understand the need of adding this to the client & interest DSL when it can easily be solved by having a client per server group.

**Comment by tbak** [comment]
I think it is more about transport optimization. If we access cross region data via read cluster, we minimize inter-region traffic + improve bootstrap latency.

**Comment by NiteshKant** [comment]
@tbak I am just questioning the change in the client via introduction of data sources. 

Multiple server groups inside the _same_ client does not sound the correct abstraction to me. I see the following usecases:

- Read server configured to read from multiple regions: This is a server level configuration and the decision to use which client should be split at the time of query for an interest, choosing an appropriate client for the query. This does not require introducing the data source concept at the client level.
- Users querying for cross-region data. This should be an attribute of the interest and should not need any configuration on the client. I do not think "datasource" is the correct terminology for this. We should be explicit that it is a cross-region query, something like `Interests.forVip("vip").inRegion("us-east-1")`. In this case it will be an out-of-band understanding for the user that whether the application is running in an environment which supports cross-region queries. If not, the interest should error out.

I can see from where the proposal is coming i.e. to generalize the implementation in the server to be available for all clients but I think the usage is pretty different for an end user vis-a-vis a eureka server.

**Comment by qiangdavidliu** [comment]
Per discussions, some confusion were around whether the configurations specified are for read servers only, or also for EurekaClient used by users. The configurations are only for the former and will not be for  clients exposed to end users.

There are also some discussions tbd on whether a more specific DSL should be used to specify the "dataSource" vs using strings.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
