### ISSUE TITLE
2.x SerializedTaskInvoker is not needed for EurekaInterestClient (and derivatives)

### ISSUE THREAD

**Issue by qiangdavidliu** [Netflix/eureka#512]
The SerializedTaskInvoker is current attached to the Eureka SourcedRegistry to guarantee synchronization of registrations and unregistrations from multiple sources into the registry. Synchronization is necessary for the write server as their input sources are from multiple channels, but for the EurekaInterestClient (including the read server) the input source is always from a single interest channel, so synchronization is not needed. Removing the SerializedTaskInvoker in these cases should lead to performance improvements.

**Comment by tbak** [comment]
SerializedTaskInvoker is no longer used
