### ISSUE TITLE
Lease renewal: inconsistency between Lease.renew() and Lease.isExpired()

### ISSUE THREAD

**Issue by brenuart** [Netflix/eureka#531]
There seems to be an inconsistency between the two following methods (from `com.netflix.eureka.lease.Lease`:

    public void renew() {
        lastUpdateTimestamp = System.currentTimeMillis() + duration;
    }

    public boolean isExpired() {
        return (evictionTimestamp > 0 || System.currentTimeMillis() > (lastUpdateTimestamp + duration));
    }

When the lease is renewed, the `lastUpdatedTimestamp` is set to `now()` + the expected client lease renewal period. It therefore represents _when the lease is about to expire_ and not when it was last renewed.

To check if the lease is expired, the `isExpired()` method adds again the duration to the `lastUpdateTimestamp` - hence the lease will expire only after two times the duration.

Finally, javadocs on the `getLastRenewalTimestamp()` clearly defines the actual meaning of the `lastUpdateTimestamp`:

    /**
     * Gets the milliseconds since epoch when the lease was last renewed.
     *
     * @return the milliseconds since epoch when the lease was last renewed.
     */
    public long getLastRenewalTimestamp() {
        return lastUpdateTimestamp;
    }

Conclusion: the `renew()` method seems to be broken: *it shouldn't add the duration to the current time.*

**Comment by qiangdavidliu** [comment]
@brenuart thanks for point this out, this indeed looks to be the case. We'll take a look at the impact of this and get back to you on whether we fix or update the comments (as this code is very old and been working in our production for a while, this unintended behaviour may be something that clients now expect, and is therefore potentially harmful to change). Thanks again.

**Comment by brenuart** [comment]
The self protection mode of our Eureka got activated for some reason so lease expiration was temporarily suspended. We then had a look at the registry lease data searching for instances that expired... and discovered that some had their `lastRenewalTimestamp` in the future... This is how we discovered the issue.

**Comment by qiangdavidliu** [comment]
Comments updated in #537
