### ISSUE TITLE
BelowRenewThreshold: isBelowRenewThreshold() & isLeaseExpirationEnabled() do not agree

### ISSUE THREAD

**Issue by brenuart** [Netflix/eureka#533]
Eureka activate its self protection mode when last minute's renewal rate is below the threshold.
The following two methods of `com.netflix.eureka.PeerAwareInstanceRegistry` do not agree on the condition:

     public int isBelowRenewThreshold() {
        if ((getNumOfRenewsInLastMin() < numberOfRenewsPerMinThreshold)
    ...

For that method, self protection should be activated when `renewsRate < threshold`. However, for the following method, the mode is activated if `renewsRate <= threshold`:

    public boolean isLeaseExpirationEnabled() {
        boolean leaseExpirationEnabled = (numberOfRenewsPerMinThreshold > 0)
                && (getNumOfRenewsInLastMin() > numberOfRenewsPerMinThreshold);
    ...

So we get unexpected behaviour when `renewsRate == threshold`.

As far as I can tell, `isbelowRenewThreshold()` is only used by Servo to report metrics, while `isLeaseExpirationEnabled()` is used by the eviction thread to perform the actual eviction of expired leases.

**Comment by qiangdavidliu** [comment]
fixed in #537
