### ISSUE TITLE
2.x Eureka2 home page

### ISSUE THREAD

**Issue by tbak** [Netflix/eureka#575]
Currently Eureka2 hasn't any home page, but instead provides two Karyon webadmin UI pages (registry insight and server status). These pages are strictly Eureka2 specific, as unlike in Eureka1 where there was always local full registry copy, in Eureka2 there might be multitude of different client subscriptions, dynamically changing over time. The latter may be tracked but only within a framework, which is out of scope of Eureka2 project itself (it is a good fit for Karyon).

I propose to convert the two Karyon webadmin UI pages into Eureka2 WEB app, and leave to Karyon admin the standard UI tabs that are there.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
