### ISSUE TITLE
Doc: AWS credentials obtained through InstanceProfileCredentials

### ISSUE THREAD

**Issue by jeffreymyers** [Netflix/eureka#590]
Minor issue with the wiki documentation here: https://github.com/Netflix/eureka/wiki/Configuring-Eureka-in-AWS-Cloud#eureka-aws-specific-properties

This section indicates that setting the AWS IAM keys via the configuration is required, but looking at the code, it falls back to using the AWS SDK's InstanceProfileCredentialsProvider to pick up the credentials dynamically from the EC2 Instance Metadata Service. We're much happier with leveraging this option rather than specifying the keys in the config, so I'd suggest amending the documentation to indicate that this is the fallback behavior if the keys are not specified in the config.

Here are the relevant lines in the code where this fallback behavior is used:
https://github.com/Netflix/eureka/blob/9711533554c62b472a7248b71764c56266ce0c8e/eureka-core/src/main/java/com/netflix/eureka/util/EIPManager.java#L353
https://github.com/Netflix/eureka/blob/329d104ceab914d186a54f3a8e61c23246cc5f2a/eureka-core/src/main/java/com/netflix/eureka/util/AwsAsgUtil.java#L472

**Comment by qiangdavidliu** [comment]
Fixed, thanks @jeffreymyers
