### ISSUE TITLE
InstanceInfo data loaded during server bootstrap should be evicted after some time

### ISSUE THREAD

**Issue by tbak** [Netflix/eureka#602]
Eureka write server can load initial registry content from an external source, prior to setting yourself into UP status. This data must have a well defined lifecycle, and ideally its corresponding instance info holders should be removed, as soon as regular registration updates are received. Stale data must be dropped after configurable amount of time.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
