### ISSUE TITLE
Updating Instance status for an Instance that doesn't exist returns 406

### ISSUE THREAD

**Issue by thepoofy** [Netflix/eureka#624]
This is an incorrect usage of http response codes.  `406` should indicate the wrong accept header was used.  This should respond with a `404` should be thrown indicating the resource is not found.

**Comment by tbak** [comment]
According to RFC2616:
"
 406 Not Acceptable
The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request.
"
This description fits the usage pattern.

**Comment by thepoofy** [comment]
The "resource identified" criteria hasn't been met.  In the event there is no resource identifiable by the correct response code is 404.  Going back to the RFC:

```
10.4.5 404 Not Found

   The server has not found anything matching the Request-URI. No
   indication is given of whether the condition is temporary or
   permanent.
```

So when an Instance has been removed from Eureka due to a timeout the URI doesn't match any values known to Eureka and should be spitting out a 404.

I was extra irked by this because using a `Accept: */*` still returned a 406.

**Comment by tbak** [comment]
You are right, status code 404 should be returned, and after checking the code it is implemented like that. In the latest release we added a filter that enforces GZIP replies for all GET requests. If you run GET with something like "Accept-Encoding: identity" you will get 406 in reply. If this is the case, your options would be:
* remove the filter from the reference web.xml (gzipEncodingEnforcingFilter)
* support gzip encoding in your client (either do not set Accept-Encoding header, which assumes gzip is supported, or add it explicitly)

**Comment by thepoofy** [comment]
Putting aside the gzip which is not relevant here; we're using version 1.1.141 and that is not the behavior we see.

**Comment by tbak** [comment]
Can you upgrade to latest version? 1.1.141 is quite old, and we have done quite a few updates.

**Comment by tbak** [comment]
As we have not received any more information about this issue, I am closing it.
