### ISSUE TITLE
Change status when the lease has expired.

### ISSUE THREAD

**Issue by Swierkowski** [Netflix/eureka#625]
When my service has crashed or killed -9 I would like to see that it is in DOWN status.

Currently when the lease has expired, the service can be evicted from the service registry. It happens when you configure enableSelfPreservation=false.

I would like to not evict the service from the registry, but instead change the status to DOWN.

This feature could be configured by new config parameter like goDownWhenLeaseExpired.

**Comment by tbak** [comment]
Eureka has pretty complex configuration already, and we prefer not adding more properties to it. What you are requesting here, could be implemented in a more generic way as:
* disabling heartbeats (not supported)
* overriding current status (supported)

Heartbeats/lease are essential concept in Eureka. Self preservation was provided to protect from loosing registry content during network failures or peer node crashes. You could try to set self preservation to 100%, which ideally would prohibit any node to be evicted. You can than override instance status with REST API call `PUT /eureka/v2/apps/appID/instanceID/status?value=DOWN`.

**Comment by Swierkowski** [comment]
In my case, my service has already crashed. Therefore, the service is not able to change the status using REST API.

My service is written in Java. I have already registered a JVM shutdown hook which changes the status of my service to DOWN. The problem is that when the service was not stopped gracefully the shutdown hook is not executed. It is e.g. kill -9 or OutOfMemoryError.

In my case the only thing that Eureka server knows is that it has stopped receiving heartbeats. I would like this to be interpreted as the service is DOWN.

**Comment by tbak** [comment]
This behavior would require bigger changes in the code, and is not directly in line with Eureka architectural principles.

What you want to achieve here is better handled by the health check poller mechanism. This is an external monitoring service that periodically calls each server of your fleet at a well know endpoint (Eureka provides healtcheck URL field for that in InstanceInfo), and if there is no successful reply marks an instance as down.
If you look at karyon3 (https://github.com/Netflix/karyon/tree/3.x), it provides a framework for application health evaluation + REST endpoint.

**Comment by NiteshKant** [comment]
>>> I would like this to be interpreted as the service is DOWN.

Leaving aside Eureka internals, how would you use this DOWN status differently than the instance not being available in Eureka registry?

**Comment by Swierkowski** [comment]
I have already implemented my own poller mechanism which is setting the status to down when there are no heartbeats. As I start Eureka server using spring boot, I have direct access to eureka registry.

**Comment by NiteshKant** [comment]
>>> I have already implemented my own poller mechanism which is setting the status to down when there are no heartbeats.

So, all servers that do not send an explicit remove, will stay in eureka registry forever?
