### ISSUE TITLE
Eureka 2.0 information propagation delay question

### ISSUE THREAD

**Issue by aivans** [Netflix/eureka#641]
Hi,

Will  the Eureka 2.0 push model improve the delay for broadcasting topology changes?
Right  now the Clients pull regularly hence the updates can take some time to the Client. I was wondering whether with the push model we will get closer to realtime.

Thanks

**Comment by tbak** [comment]
Yes, with the push model we are getting delays as low as ~5ms, depending of
course on the system load and network bandwidth.

**Comment by aivans** [comment]
Sounds great.

I know there is an RC available, is there a timeline for a Production ready release?

Thanks

**Comment by qiangdavidliu** [comment]
Hi @aivans there are some known bugs with rc.2 that we are fixing for a rc.3 release. As for 1.0, we don't have any timelines for this at the moment.

**Comment by aivans** [comment]
Thank you.

Looking forward!
