### ISSUE TITLE
Allow custom DataCenterInfo implementations

### ISSUE THREAD

**Issue by spencergibb** [Netflix/eureka#645]
Currently there is no way to have a custom implementation that implements `UniqueIdentifier`.

/cc @jkschneider

**Comment by tbak** [comment]
I understand that you have already custom serializer for your DataCenterInfo implementation. Can you tell us more about what is preventing you from implementing this interface?

**Comment by jkschneider** [comment]
@tbak @spencergibb this pull request solves the issue we have in Spring Cloud: https://github.com/Netflix/eureka/pull/646

**Comment by qiangdavidliu** [comment]
Closing w.r.t. #649
