### ISSUE TITLE
Eureka gives 500 when app registered without Datacenter info

### ISSUE THREAD

**Issue by diasjorge** [Netflix/eureka#647]
Hi,

I was testing Eureka and found that if I do a push to register and app to:

SERVER/v2/apps/APP_NAME and in the json data I only have something like:

```
{
    "instance": {
        "hostName":"eureka-testing.example.com",
        "app":"eureka-testing",
        "ipAddr": "127.0.0.1",
        "vipAddress":"eureka-testing",
        "status":"UP",
        "port":"8080"
    }
}
```

The status page then gives a 500.

I think the submitted data should be validated against the DTD shown in the wiki or at least the page should not fail.

**Comment by tbak** [comment]
We do not do any schema based validation (it is JSON), but the request should not fail with 500 in such case. As each instance record must have associated data center info, an HTTP response with status code 400 would be more meaningful here.
Thank you for reporting this.

**Comment by tbak** [comment]
Fixed in PR https://github.com/Netflix/eureka/pull/651
