### ISSUE TITLE
unresolvable documentation link inside XSD on "Eureka REST operations" page

### ISSUE THREAD

**Issue by hakanson** [Netflix/eureka#648]
When reading the XSD provided on https://github.com/Netflix/eureka/wiki/Eureka-REST-operations there is a comment with "instructions" that refers to what looks like an internal Netflix wiki (http://wiki.netflix.com/clearspace/docs/DOC-20965).

                <xsd:element name="hostName" type="xsd:string" />
                
                <xsd:element name="app" type="xsd:string" />

Can either the XSD example be updated or the linked documentation be made accessible?

**Comment by qiangdavidliu** [comment]
Thanks @hakanson. The internal document no longer exist and was likely for linkage with other internal tooling and not relevant for this xsd. Updated the wiki.
