### ISSUE TITLE
2.x AwsDataCenterInfo::getName is misleading

### ISSUE THREAD

**Issue by Crystark** [Netflix/eureka#679]
Hi,

I'm currently testing eureka2. I have 2 apps registering and sending "alive" events to eureka2. One of the app is supposed to listen for the other and react to the other being down. The thing is, i was hoping to filter the change notifications based on the datacenter as the app must not care about other apps from other datacenters not being alive. Using `DataCenterInfo` I thought `getName` would give me the datacenter name. It turns out that `AwsDataCenterInfo` provides the instanceId when I call that method so two apps in the same datacenter but on two different instances end up returning different values for getName().

So then I thought I must have understood this wrong and DataCenterInfo may actually mean "Information from the Datacenter" but that's not what the JavaDoc says:
```
DataCenterInfo encapsulates information about the data center where a given server is running, plus server specific information, like IP addresses, host names, etc.
```

I'll end up not using DataCenterInfo for now to do what I want and use MetaDatas instead but I thought you may want to clarify that.

Thanks ! :)

**Comment by tbak** [comment]
Thank you for your comment. The DataCenterInfo API is really misleading. Probably we would need to have both getName and getInstanceId methods, with the former returning the data center name. This is actually the behavior in Eureka1.

**Comment by qiangdavidliu** [comment]
archiving as eureka2 work is going through some larger internal changes.
