### ISSUE TITLE
Add Client Update Callback

### ISSUE THREAD

**Issue by jameskojo** [Netflix/eureka#69]
Add a callback to allow for listeners to be notified when the eureka client gets an update in it's poller.

I'm managing a connection pool to a set of instances in a cluster. I'd like to be able to react in a timely manner to status changes of those instances. E.G. mark-down, mark-up, instance termination and metadata changes. 

My current strategy is to poll the client periodically, but that introduces even more latency on top of the latency introduced by the polling thread.

**Comment by tbak** [comment]
It is supported via EventBus service, where discovery events are emitted (StatusChangeEvent and CacheRefreshedEvent).
