### ISSUE TITLE
Setting OUT_OF_SERVICE for one app causes all apps on same host to register as such

### ISSUE THREAD

**Issue by octonary** [Netflix/eureka#690]
If I send an OUT_OF_SERVICE request to a particular app on a given host that runs multiple apps, all Eureka enabled apps on that same host start registering an OUT_OF_SERVICE state.

For example... in my test environment I have a Eureka-server instance and 3 Eureka enabled apps running across 3 nodes. If I issue an OUT_OF_SERVICE to appA running on node1(curl -X PUT http://node1:9090/eureka/v2/apps/appA/node1/status?value=OUT_OF_SERVICE), all apps (including Eureka-server) on node1 start showing an OUT_OF_SERVICE state.

**Comment by qiangdavidliu** [comment]
@octonary thanks for raising the issue. The current implementation of OUT_OF_SERVICE does not work well with multi-tenant environments and uses the id as the key for OOS (which defaults to the hostname/aws instanceId). We will take a look at fixing this in a future release.

**Comment by spencergibb** [comment]
@octonary you can set `eureka.instanceId` for each instance to handle that case. It's what we do in [spring-cloud-netflix](https://github.com/spring-cloud/spring-cloud-netflix).

**Comment by octonary** [comment]
Thanks! I will start setting the instanceId.

**Comment by octonary** [comment]
FYI, I couldn't get eureka.instanceId to work but eureka.instance.metadataMap.instanceId seems to do the trick. Thanks again.

**Comment by ilayze** [comment]
@octonary I tried what you suggested but now I can't make the service OUT_OF_SERVICE... how did you invoke the put request? (curl -X PUT http://node1:9090/eureka/v2/apps/appA/metadataInstanceId/status?value=OUT_OF_SERVICE)?
