### ISSUE TITLE
Wiki - Configuring-Eureka - wrong link to default configuration

### ISSUE THREAD

**Issue by herau** [Netflix/eureka#694]
In the configuration part of the wiki page, the link to the example of default configuration isn't correct (404) : `You can take a look at the examples here for default configurations`

maybe the link should point to [https://github.com/Netflix/eureka/blob/master/eureka-server/src/main/resources/]() or [https://github.com/Netflix/eureka/tree/master/eureka-examples/conf]()

**Comment by tbak** [comment]
Thank you for spotting this. I have just fixed that.
