### ISSUE TITLE
Add documentation of config properties

### ISSUE THREAD

**Issue by liry** [Netflix/eureka#697]
It's really pita when you run example, add some metadata and when you getMetadata() in the client it returns empty map even if you see those metada when you query API directly. Then you search through documentation and other sources and there's no information anywhere, so one has to debug it to find out that there's some magic undocumented ```eureka.decoderName``` config property and when one has to set it to ```JacksonJson``` to make it work.

Please, improve your doc! It will make our lives easier! Thank you ;)

**Comment by tbak** [comment]
The example was setup with JacksonJsonMini codec, which omits all metadata
in InstanceInfo object. I have changed it to the standard codec.
Thank you for spotting this.
/Tomasz
