### ISSUE TITLE
Program does not shutdown after using EurekaClient

### ISSUE THREAD

**Issue by jylin** [Netflix/eureka#700]
I have a program that uses EurekaClient to find services, but it seems that if it runs for longer than say 30 seconds, then exiting the main thread (either gracefully or because of an exception) leaves the Java program hanging. I suspect Eureka might be spawning some user threads. Could they be changed to be daemon threads instead?

**Comment by tbak** [comment]
Thank you for spotting this. I have fixed this issue in this PR: https://github.com/Netflix/eureka/pull/701.
You should always call `EurekaClient.shutdown()`, which terminates all the allocated resources, including the thread pools.
