### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by alexandre-gauge** [Netflix/eureka#705]
```
.../eureka/eureka-client/src/main/java/com/netflix/discovery/util/ExceptionsMetric.java:54: error: cannot find symbol
            if (exceptionCounters.putIfAbsent(exceptionName, counter) == null) {
                                 ^
  symbol:   method putIfAbsent(String,Counter)
  location: variable exceptionCounters of type Map<String,Counter>
```

**Comment by qiangdavidliu** [comment]
@alexandre-gauge that is a java8 method. Can you try to update to java8 and try again? Thanks.

**Comment by brharrington** [comment]
@qiangdavidliu it might be a good idea to set the compatibility level explicitly on the build:

```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

That should make the error message a bit easier to follow than cannot find symbol. For example on one of mine when trying to build on java 7 it gives:

```
* What went wrong:
Execution failed for task ':spectator-api:compileJava'.
> invalid source release: 1.8
```

**Comment by qiangdavidliu** [comment]
Thanks @brharrington. That's a good suggestion.

**Comment by qiangdavidliu** [comment]
Updated as @brharrington suggested

**Comment by alexandre-gauge** [comment]
Thanks @qiangdavidliu and @brharrington
