### ISSUE TITLE
Status REST operation completely disables instance HealthCheckHandler?

### ISSUE THREAD

**Issue by abaculus** [Netflix/eureka#717]
Hi

I've noticed that when I call the REST API for status (e.g. PUT /eureka/v2/apps/appID/instanceID/status?value=UP) it makes Eureka to ignore the status updates from the instance HealthCheckHandler. Seems like the 'overriddenstatus' cannot be undone.

The only way to get Eureka to respect the HealthCheckHandler status updates from the instance HealthCheckHandler is to de-register and register again (i.e. by REST API calls or re-starting the instance).

I have a use case where we want to change the status for a specific instance to e.g. DOWN/OUT_OF_SERVICE and then put it back to UP but with Eureka respecting the instance HealthCheckHandler.

Is this possible somehow?

Kind regards,
Andreas

**Comment by brharrington** [comment]
You should be able to to a delete request to clear the override:

```
DELETE /eureka/v2/apps/appID/instanceID/status
```

**Comment by abaculus** [comment]
The only allowed methods for endpoint is OPTIONS and PUT.

**Comment by brharrington** [comment]
It looks like that was added in 1.1.148: https://github.com/Netflix/eureka/releases/tag/1.1.148

**Comment by abaculus** [comment]
Aah, that explain things...

Thank you for your very helpful support! 

Kudos
