### ISSUE TITLE
Why InstanceInfo.InstanceStatus can not be a interface?

### ISSUE THREAD

**Issue by andreaposadino** [Netflix/eureka#718]
Hi,

I'm working in a microservice in java using your code.
I wanted to add a custom InstanceStatus for monitoring through Eureka when my ms is working on a specific job. Something like a "RUNNING JOB A" status.
But InstanceStatus is a enum class, so I can't extend it.

I want to set my instanceStatus with this method:
ApplicationInfoManager.getInstance().setInstanceStatus(InstanceInfo.InstanceStatus)

But I can't for a custom InstanceStatus.

I think that there is a reason about this choice of a defined set of InstanceStatus but I don't get it.
Is there another way for what I want to do? 

Thanks in advance

**Comment by tbak** [comment]
InstanceStatus's purpose is to report an overall service state. You can still propagate this information using metadata field.

**Comment by andreaposadino** [comment]
Thank for your answer,

I just tried with ApplicationInfoManager.getInstance().registerAppMetadata(Map<String,String> appMetadata) method and worked. 

Thank you again.

**Comment by tbak** [comment]
glad to help
