### ISSUE TITLE
Question : Eureka never unregisters a service

### ISSUE THREAD

**Issue by pradeepkusingh** [Netflix/eureka#722]
I am running few test with Eureka and seeing the issue though I shut down the micoservices , it still shows services are up and running, ribbon got the server list and call failed with 404. I went through the eureka docs 85% rule, still this one is tricky. If I disabled the self preservation mode it works, but I don't want to do that as per recommendations in prod. so what is the best configuration to not face this issue?

**Comment by tbak** [comment]
If you shutdown single server, and it makes eureka enter self preservation mode, it means you have very few servers in the registry, and there is nothing else to do about it as to disable it. As you say it is in test, this should be probably ok with you. In prod, with more registry entries, self preservation should kick in only when there is  a serious issue causing massive registration expiries, like network failure.

**Comment by tbak** [comment]
I am closing this issue. Please, reopen it if you wish to continue this discussion.
