### ISSUE TITLE
can't run 2 instances using the same discovery manager

### ISSUE THREAD

**Issue by yairogen** [Netflix/eureka#725]
I am using eureka -client 1.1.147

I am both a server (using spring-cloud) and ribbon client (using rxnetty based client).

for the client to work I had to write this code:

 if (DiscoveryManager.getInstance().getDiscoveryClient() == null) {
            EurekaInstanceConfig eurekaInstanceConfig = new MyDataCenterInstanceConfig(getApiName());
            EurekaClientConfig eurekaClientConfig = new DefaultEurekaClientConfig(getApiName() + ".");
            DiscoveryManager.getInstance().initComponent(eurekaInstanceConfig, eurekaClientConfig);
        }

problem is that if this code runs before spring cloud initializes the server side discovery, my server doesn't register at all with eureka.

1. As DiscoveryManager is a singleton I can only register one instance.
2. For the client I don't want to register an instance just be able to lookup using 'com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList' class.

Is there another way to make my LB to lookup with eureka? Maybe initialize the eureka client on the client side differently?

**Comment by tbak** [comment]
You are using very old version with eureka. In later releases we improved DI support, so this should be no more an issue.

>For the client I don't want to register an instance just be able to lookup using 

I do not understand this question. The reason to register with discovery is to be able to load server list for load balancing purposes. If you do not want to use Eureka registry, you can always use another ServerList implementation (for example ConfigurationBasedServerList).

**Comment by yairogen** [comment]
@tbak Thanks for your reply.
The old version we use is coming from spring-cloud-netflix lib. I have no idea why but even thier latest version still uses eureka 1.1.147: https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-netflix/1.0.4.RELEASE/spring-cloud-netflix-1.0.4.RELEASE.pom.
Any idea why?

Regatding the second part: I thought the A eureka client can be used for 2 puposes:
- register a server
- as a client, lookup other servers.

So - I was asking is it possible to be a eureka client just for lookup purposes and not register the client itself with its own instance properties as the client may not be a server in it self?

**Comment by spencergibb** [comment]
In our Brixton milestones we use later versions of eureka. It was a major refactoring to use it.

**Comment by yairogen** [comment]
so - you recommend we try out this?

http://repo.spring.io/libs-milestone-local/org/springframework/cloud/spring-cloud-netflix/1.1.0.M4/

**Comment by tbak** [comment]
@yairogen Regarding your question:

>So - I was asking is it possible to be a eureka client just for lookup purposes and not register the client itself with its own instance properties as the client may not be a server in it self?

It is possible to configure eureka to only register (no registry fetch), or only do registry fetch (no registration). This is controlled via two properties:
* eureka.registration.enabled
* eureka.shouldFetchRegistry

**Comment by tbak** [comment]
I am closing this issue. Please, reopen it if you wish to continue this discussion.
