### ISSUE TITLE
DiscoveryClient throws Exception if no service is found

### ISSUE THREAD

**Issue by FabianHoltkoetter** [Netflix/eureka#732]
The DiscoveryClient throws an Exception when no service for the given ID is found. In my opinion thats not exceptional but infact totally possible. The method getNextServerFromEureka should return an java.util.Optional.

**Comment by tbak** [comment]
Can you point which methods have this behavior? Query by id is supported by this method:
```java
public List<InstanceInfo> getInstancesById(String id);
```
And it should return empty list if no instance with the given id is found.

**Comment by FabianHoltkoetter** [comment]
```java
public InstanceInfo getNextServerFromEureka(String virtualHostname, boolean secure) {
    List<InstanceInfo> instanceInfoList = this.getInstancesByVipAddress(
            virtualHostname, secure);
    if (instanceInfoList == null || instanceInfoList.isEmpty()) {
        throw new RuntimeException("No matches for the virtual host name :"
                + virtualHostname);
    }
    Applications apps = this.localRegionApps.get();
    int index = (int) (apps.getNextIndex(virtualHostname.toUpperCase(),
            secure).incrementAndGet() % instanceInfoList.size());
    return instanceInfoList.get(index);
}
```
This is the method I'm talking about. `getInstancesById` is of course a good replacement.

**Comment by qiangdavidliu** [comment]
@FabianHoltkoetter what you propose makes sense. I have a suspicion that had Optional been available prior to java8, this API would likely have been done that way. Unfortunately the getNextServerFromEureka() method is now a public API and for compatibility, it would be a breaking change to change it from returning an InstanceInfo to return an Optional<InstanceInfo>.

**Comment by qiangdavidliu** [comment]
@FabianHoltkoetter Thanks for raising this issue. Although it is valid, I'm going to close this for now as there are work around methods (e.g. get the full list of the vip and do a simple round robin on the list), and updating the method in question would leave to requiring an incompatible version bump.
