### ISSUE TITLE
Add a feature to tell the client which IP address to register in case of multiple IPs

### ISSUE THREAD

**Issue by mrumpf** [Netflix/eureka#737]
My office notebook uses a VPN/PPP connection into the corporate LAN for any kind of internet access.
My home LAN is using the network 192.168.0.1/255.255.255.0. The VPN client cuts any route into the 192.168... network and allows only connections into the PPP network (10.177.196.145/255.255.255.255), created by the VPN client.
The Eureka client, when I set the eureka.instance.preferIpAddress to true, registers with for example 192.168.0.125. This IP cannot be reached due to the restrictive VPN client, cutting all routes, except for the corporate PPP network.

There is a discussion on stackoverflow covering the topic:
http://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java

Making this work is an important developer feature. With the current implementation Eureka cannot be used for development in a corporate environment via a VPN (home office).

**Comment by mrumpf** [comment]
I just saw that there is an algorithm to prefer IPs from NICs whose name ends with a "0".
https://github.com/Netflix/eureka/blob/de24b9349fe579dba687f069f2bf495c8fe97c3f/eureka-client/src/main/java/com/netflix/discovery/util/SystemUtil.java

That does not work under Windows, but could be adapted to set the preferred NIC name instead of the network, as suggested above:
```
eureka.instance.preferredNetworkAdapter="PPP adapter Global Remote"
```
So the code tries to select eth0 under Windows ".*Local Area Connection.*" and additionally it should be possible to overide the default in case the defaults does not work.

My ipconfig output (truncated) looks like this:
```
Windows IP Configuration

PPP adapter Global Remote:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 10.177.196.145
   Subnet Mask . . . . . . . . . . . : 255.255.255.255
   Default Gateway . . . . . . . . . : 0.0.0.0

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : lan
   Link-local IPv6 Address . . . . . : fe80::f427:8c69:7f63:a33c%11
   IPv4 Address. . . . . . . . . . . : 192.168.0.125
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.0.5
```

**Comment by qiangdavidliu** [comment]
Thanks @mrumpf . We'll take a look at this.

**Comment by mrumpf** [comment]
The Spring Cloud Team claims to have this already fixed: https://github.com/spring-cloud/spring-cloud-netflix/issues/788

**Comment by cforce** [comment]
There is such function, see http://projects.spring.io/spring-cloud/spring-cloud.html#ignore-network-interfaces

**Comment by pcornelissen** [comment]
You need a recent brixton version for it BTW.

Then you can ignore all unwanded interfaces by:

```
spring:
  cloud:
    inetutils:
      ignoredInterfaces:
        - tun.*

```
