### ISSUE TITLE
Disable EIP binding calls based on config

### ISSUE THREAD

**Issue by maliksalman** [Netflix/eureka#740]
For our needs, we would like to run a eureka cluster in an AWS VPC. We would rely on DNS TXT records for the eureka servers and clients to discover each other. Furthermore, we would be running the eureka servers and all their client instances in VPC private subnets. Assigning EIPs to the eureka servers in this scenario makes no sense. 

Currently, there is no way of letting `com.netflix.eureka.EurekaBootStrap` know not to worry about EIPs. We tried playing with properties exposed by `com.netflix.eureka.EurekaServerConfig` - but they are not enough. Specifically, we tried to set the `eIPBindRebindRetries` to 0 and `eIPBindingRetryIntervalMs` to really large value (like Interger.MAX_VALUE). With these settings the `com.netflix.eureka.util.EIPManager` can be held at bay for about 24 days - it will then try to do its thing again. 

If we introduce a new property (like `disableEIPBinds`) in `com.netflix.eureka.EurekaServerConfig` and change the rest of code accordingly, we can easily circumvent the EIP binding altogether. We can make the properties default value to be `false` so it is backwards compatible. I am willing to submit a PR if this approach is appropriate.

**Comment by qiangdavidliu** [comment]
Hi @maliksalman thanks for the issue. For different deployment environments, we are aiming for a more custom strategy based on the AwsBinder (https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/aws/AwsBinder.java) interface and better DI support for the server (there are some work-in-progress code in the eureka-server-karyon3 package). The idea would be to be able to custom bind different components of eureka servers as needs arise. So in your case, you can bind your own (NoOp or specialised) AwsBinder to suit your use cases, whereas the default that works for us is the EIPBinder.

We are hoping to have this complete in the short term.

**Comment by maliksalman** [comment]
That must be new. I was working with spring-cloud-netflix-core 1.0.1 which includes eureka-client 1.1.147. I will look into this.

@qiangdavidliu, thanks for the pointer.

**Comment by spencergibb** [comment]
The next version of spring-cloud-netfix uses the latest version of eureka.

**Comment by qiangdavidliu** [comment]
Latest spring-cloud-netflix is on eureka 1.4.x, closing.

**Comment by vikrantch-hk** [comment]
@spencergibb has this feature been introduced

**Comment by bsushant-athena** [comment]
@maliksalman is it possible for you to share repo link? I also need to implement same feature set into our eureka which runs in same zone on aws vpc without ASG/DNS based peerawareness.
