### ISSUE TITLE
Could not determine if the replica is available exception

### ISSUE THREAD

**Issue by drax68** [Netflix/eureka#748]
Hi, I've noticed no active replicas on status page for eureka cluster consisting of 2 eureka servers. We use route53-based txt dns setup, both servers in different az.
All running replicas in *unavailable-replicas* list, though logs contains replication activity.
- What effect does it have for eureka cluster?
- Can it cause situations when cluster losts overriden registry data when new servers added?
Any help in finding reasons of such behaviour appreciated.
Currently we use eureka 1.1.151
Exceptions when new server added to eureka cluster:
```
Could not determine if the replica is available 
! java.lang.NullPointerException: null
! at com.netflix.eureka.resources.StatusResource.isReplicaAvailable(StatusResource.java:89)
! at com.netflix.eureka.resources.StatusResource.getStatusInfo(StatusResource.java:69)
! at sun.reflect.GeneratedMethodAccessor136.invoke(Unknown Source)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:497)
! at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:912)
! at freemarker.ext.beans.SimpleMethodModel.exec(SimpleMethodModel.java:107)
! at freemarker.core.MethodCall._eval(MethodCall.java:98)
! at freemarker.core.Expression.eval(Expression.java:111)
! at freemarker.core.Assignment.accept(Assignment.java:106)
! at freemarker.core.Environment.visit(Environment.java:265)
! at freemarker.core.MixedContent.accept(MixedContent.java:93)
! at freemarker.core.Environment.visit(Environment.java:265)
! at freemarker.core.Environment.process(Environment.java:243)
! at freemarker.template.Template.process(Template.java:277)
! at com.yammer.dropwizard.views.freemarker.FreemarkerViewRenderer.render(FreemarkerViewRenderer.java:56)
! at com.yammer.dropwizard.views.ViewMessageBodyWriter.writeTo(ViewMessageBodyWriter.java:74)
! at com.yammer.dropwizard.views.ViewMessageBodyWriter.writeTo(ViewMessageBodyWriter.java:22)
! at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
! at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
! at com.netflix.eureka.StatusFilter.doFilter(StatusFilter.java:68)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:66)
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
! at com.yammer.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
! at com.yammer.metrics.jetty.InstrumentedHandler.handle(InstrumentedHandler.java:200)
! at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
! at org.eclipse.jetty.server.Server.handle(Server.java:368)
! at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
! at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
! at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
! at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
! at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
! at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
! at org.eclipse.jetty.server.nio.BlockingChannelConnector$BlockingChannelEndPoint.run(BlockingChannelConnector.java:298)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
! at java.lang.Thread.run(Thread.java:745)
```

**Comment by qiangdavidliu** [comment]
Hi @drax68 eureka 1.1.51 is over 3 years old, and significant changes have gone into eureka since. I'm not sure if it will be easy to figure out what issue you might be running into given the age of the version. Are you able to upgrade to a more recent release?

**Comment by drax68** [comment]
@qiangdavidliu Correction, we currently use 1.1.151 version

**Comment by drax68** [comment]
Please advise, which version (1.2, 1.3) should we use to fix mentioned issue.

**Comment by qiangdavidliu** [comment]
Minor versions of servers should still be compatible. We are running with 1.3.8 servers as of this moment.

**Comment by pparth** [comment]
So, @qiangdavidliu is this actually a bug or something? Can you explain please more about the issue and its impact to Eureka availability, reliability etc.?

**Comment by qiangdavidliu** [comment]
@pparth from looking at your error log and comparing against source code, it looks like the status result you are seeing is due to an NPE in your StatusResource itself, not necessarily due to any actual system issues. Given that you are seeing replication logs, it's likely your servers are still connected. One way to check is to try to make a /v2/apps/<your discovery server app name> call to see what the registry data looks like.

As an aside regarding the NPE, are you using the provided war to deploy your server or customizing it? Using the provided artifacts there shouldn't be any NPEs.

**Comment by pparth** [comment]
Indeed, this has to do with the StatusResource and we do have a customised Eureka Service and do not use the original war. We were just wandering whether this error is not only about status and has a deeper root cause as we  have a replication issue. @drax68  please provide more info about this.

**Comment by drax68** [comment]
@qiangdavidliu we have reproducible test case, where changes in eureka cluster contents (addition/removal of eureka servers to/from txt dns records) causes loss of overriden data in registry on all eureka servers (overriden statuses, custom metadata). Is this something known, or will require separate issue to investigate?

**Comment by qiangdavidliu** [comment]
@drax68 that is a known issue. status overrides for eureka at an instance level are scoped for the lifetime of a registration. So for example when you remove a server, a previously registering client to that server (which was overridden) will switch registration to a different server, and reset the override. We have explored a few different ways of dealing with internally but it has not come up as a priority. Typically internally we set overrides at an (EC2) ASG level, and that is guarded by AwsAsgUtil.java.

**Comment by pparth** [comment]
@qiangdavidliu 
- Unfortunately, we think this issue raises its ugly head not only in a manual/administrative cluster upgrade but also in a standard failure pattern where a client cannot communicate with a server instance due to a network issue (e.g. for us, the ELB in front of the instance, croaked). This led all clients registered to this instance to switch to another server instance, which is what expected from the highly available Eureka setup we have in place. However, everything went south, as all our clients register themselves as STARTING and then we switch them to UP through the REST API, as part of a deployment workflow process we have in place. So, we ended up with ALL these clients switching to STARTING and traffic stopped! There goes the highly available cluster! At any case, we thought that the STARTING status was in place exactly to support this kind of workflow process. What are we doing wrong then? That we change the status externally through the REST API? If we allowed the instance to change its status on its own, from STARTING to UP, is everything going to work ok? We can do that if this solves the issue, however, this does not feel right as we pretend that the instance knows when it is ok to receive traffic when this is definitely an external, deployment-driven decision. 
- Can you explain more what is "we set overrides at an (EC2) ASG level, and that is guarded by AwsAsgUtil.java"?

**Comment by qiangdavidliu** [comment]
Hi @pparth 

Can I clarify that your (client) applications register with STARTING only, and only transition to UP status via an external trigger (the REST call from the deployment workflow process mentioned)?

We use discovery's statuses slightly differently internally. Internally, we tie discovery statuses (STARTING, UP, DOWN) with our application healthchecks, and the state transitions between these statuses are automatically governed by the applications. For example, an application will register with STARTING, and at some point in time (e.g. Guice container initialized, or some known async warm-up process has completed), the application will automatically transition it's own status to UP. The healthcheck is also tied in to this (eurekaClient.registerHealthCheckHandler()) and is used to move between UP and DOWN programmatically.

The OUT_OF_SERVICE status is used as a special case override. Our deployment workflow has the ability to make PUT and DELETE rest calls to the eureka servers to set and remove OUT_OF_SERVICE override statuses (see https://github.com/Netflix/eureka/wiki/Eureka-REST-operations, I have updated the doc to reflect the DELETE option of removing overrides).

A slight clarification to my point earlier regarding instance-level overrides are scoped only for a registration lifecycle, if a client re-registration happens to a different eureka server (as is the case when the original target eureka server disappears, such as for re-deployment), this is not considered as a new registration lifecycle (as an explicit unregistration never happens), and as such overrides are preserved.

Regarding my comment on AwsAsgUtil, internally our most common form of overrides are applied at the (EC2) AutoScalingGroup level. We synchronized our ASG disables with eureka's OUT_OF_SERVICE status, and the logic for that is contained within AwsAsgUtil.

**Comment by pparth** [comment]
Got it.

Unfortunately, in our case, we maintain multiple Service types per machine in an ASG, so, we cannot link the ASG disables to a specific Service type Eureka status.

Regarding the status overrides, it seems that we are back to zero. According to you, the overrides should be preserved in our case. So, @drax68  please check again about our case and dig up more information about what exactly happened in our system.

**Comment by drax68** [comment]
Re-tested that case, it's reproducible:
Eureka server configuration
```
eureka.appinfo.replicate.interval = 15
eureka.client.refresh.interval = 15
eureka.client.registerWithEureka = true
eureka.datacenter = cloud
eureka.environment = env
eureka.eurekaServer.context = eureka/v2
eureka.eurekaServer.domainName = eureka.env.example.com
eureka.eurekaServer.port = 8010
eureka.lease.duration = 45
eureka.lease.renewalInterval = 15
eureka.name = eureka
eureka.peerEurekaStatusRefreshTimeIntervalMs = 15000
eureka.port = 8010
eureka.preferSameZone = false
eureka.region = us-west-1
eureka.remoteRegion.registryFetchIntervalInSeconds = 15
eureka.serviceEnabled = true
eureka.serviceUrl.us-west-1a = {{us-west-1a-eureka-instance}}/eureka/v2/
eureka.serviceUrl.us-west-1c = {{us-west-1c-eureka-instance}}/eureka/v2/
eureka.shouldUseDns = true
eureka.statusPageUrlPath = /eureka/status
eureka.us-west-1.availabilityZones = us-west-1a,us-west-1c
eureka.vipAddress = eureka.example.com
```
Eureka dns name txt.us-west-1.eureka.env.example.com resolves to TXT record
`"txt.us-west-1a.eureka.env.example.com" "txt.us-west-1c.eureka.env.example.com"`

txt.us-west-1a.eureka.env.example.com resolves to
`"elb1"`

txt.us-west-1c.eureka.env.example.com resolves to
`"elb2"`

Test case is:
1. Deploy new pair of eureka instances behind individual elb
2. Wait for initial sync (let's say existing eureka instances has <apps__hashcode>STARTING_17_UP_122_</apps__hashcode> and newly-created <apps__hashcode>UP_118_</apps__hashcode>)
3. Append new instances to az-specific txt records:
txt.us-west-1a.eureka.env.example.com resolves to
`"elb1" "elb3"`
txt.us-west-1c.eureka.env.example.com resolves to
`"elb2" "elb4"`
4. Logs contains:
```
Updating the serviceUrls as they seem to have changed from [elb1, elb2] to [elb1, elb2, elb3, elb4] 
Updating the replica nodes as they seem to have changed from [elb1, elb2] to [elb1, elb2, elb3, elb4] 
```
And after that many service entries expiring with:
`DS: Registry: expired lease for SERVICENAME - i-foobar`

Not all services expiring at that moment, only about 30% of registered services.
Other services registry data remain unchanged, and all overrides migrated to a new nodes.
As I understand, service completely de-registered on expiration.
What can be the source of this massive expiration on cluster contents changes?

**Comment by pparth** [comment]
@qiangdavidliu Can you take a look at our latest information regarding the issue please?

**Comment by qiangdavidliu** [comment]
@pparth looking at your description, this could potentially be an issue due to the order of operation between bringing up the new servers, and adding their records to the txt record. When a new server comes up, it will do a one time sync with a recognized peer (in this case an existing server). However this is one time only, so by the time this peer becomes a live server (due to the addition of it to the master txt records), the data it contain may now exceed the expiration deadline, especially when clients switch to registering with it.

Can you try the following to see if it helps with your case:
1. Add one elb to the txt record first before bringing up the new server
2. Wait a little to make sure dns propagates
3. Bring up the new eureka server

Eureka clients and servers are able to handle "missing" servers in the cluster.

**Comment by drax68** [comment]
Thank you, @qiangdavidliu 
That sequence helped with unexpected registry data expiration.

**Comment by qiangdavidliu** [comment]
@drax68 glad to hear that this resolves your issue.

**Comment by hw1995** [comment]
i don't know english
