### ISSUE TITLE
HTTPS serviceUrls end up being HTTP in 1.4.1

### ISSUE THREAD

**Issue by william-tran** [Netflix/eureka#750]
https://github.com/Netflix/eureka/blob/v1.4.1/eureka-client/src/main/java/com/netflix/discovery/shared/resolver/aws/ConfigClusterResolver.java#L79 Should probably be 
```
"https".equalsIgnoreCase(serviceURI.getScheme()),
```

**Comment by tbak** [comment]
Fixed by PR #751. Thank you for spotting this.
