### ISSUE TITLE
Eureka server security

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/eureka#755]
Hello everyone!

I used eureka in a private network and it's very fine, similar to AWS, but now i need to use it exposed to the internet and was thinking if there is some security like https and at least a basic auth to protect so other people if they found the server can't register to it.

Is there something? Because i can't use a firewall since the microservices will have dynamic ips.

**Comment by tbak** [comment]
Eureka does not provide any authentication mechanism, but it supports SSL.
To secure your deployment you might create private key/certificates for
both endpoints, and enable client side authentication. To do that you must
inject properly configured instance of EurekaJerseyClient (or build it
with EurekaJerseyClientBuilder). You can find those classes in
eureka-client package. There is unfortunately no documentation how to do
that.
If basic authentication is enough you can always configure it via servlet
container, and on the client side provide authentication credentials in
Eureka URLs (I have never tried that, so I am not 100% sure if this will
work).
/Tomasz

**Comment by spencergibb** [comment]
@tbak basic auto used to work (version < 1.3.xish). Something changed with the use of `*Endpoint` classes. https://github.com/spring-cloud/spring-cloud-netflix/commit/ca81f5671a029fe81d3fe88991d2abf782648310 is how we solved it.

**Comment by tbak** [comment]
@spencergibb Good to know. We will fix it. I have created a separate issue to track it (https://github.com/Netflix/eureka/issues/756).

**Comment by spencergibb** [comment]
@tbak thanks man!

**Comment by kennedyoliveira** [comment]
Thank you everyone for the feedback, i'll wait a solution for #756, and while it doesn't ready i'm gonna try spring cloud netflix.
