### ISSUE TITLE
java.lang.ClassNotFoundException: com.netflix.eureka.converters.EntityBodyConverter

### ISSUE THREAD

**Issue by neo-tian** [Netflix/eureka#762]
I found "@Serializer("com.netflix.eureka.converters.EntityBodyConverter")" in "com.netflix.eureka.util.StatusInfo".

But  the "EntityBodyConverter" is in "com.netflix.discovery.converters",miss "discovery"

I use eureka-core and eureka-client  version is 1.1.147

**Comment by qiangdavidliu** [comment]
@neo-tian thanks for that. This was fixed in release 1.1.158.

**Comment by neo-tian** [comment]
Thank you,that is great

2016-03-31 3:46 GMT+08:00 David Liu <notifications@github.com>:
