### ISSUE TITLE
How to dynamic set eureka client information [InstanceID, port]

### ISSUE THREAD

**Issue by kennedyoliveira** [Netflix/eureka#764]
Hello!

I'm developing an app and i wanna register with eureka after starting the server, and the port will be a random one, that the server will first try to bind and if it success that port will be used, so since eureka-client uses file based configuration, there is someway to set the port and instanceID info without using a file?

Thank you

**Comment by tbak** [comment]
Eureka provides EurekaClientConfig configuration class, so you can always write your own implementation to set Eureka service urls with dynamic ports. If you need this for unit testing, please have a look at our DiscoveryClientResource junit resource that we use internally for testing (eureka-test-utils package). We are using ephemeral ports there.

**Comment by kennedyoliveira** [comment]
Hey @tbak, thank you, i'll sure check your implementation and maybe try to create my own.

Quick question, i noticed when i start the injector the eureka-client begins the initialisation, there is a way to delay it till i call something to start it?

**Comment by tbak** [comment]
@kennedyoliveira Eureka is starting the initialization immediately in the constructor. To delay it, you would have to implement a wrapper.

**Comment by kennedyoliveira** [comment]
@tbak, got it, thank you for clarifying my doubts!
