### ISSUE TITLE
Source code build failure

### ISSUE THREAD

**Issue by searover** [Netflix/eureka#768]
When I clone and build the source code, it appears an error that say nothing but a test case failed in 
EurekaClientServerRestIntegrationTest.java:244 , I have no idea what to do until I look into the source code and find the file, locate 244 line , i see it try to bind port 8080, and then i konw the port 8080 must be already in use, so i solved this problem.

Maybe in the unit test code, we should add some try catch code, let user know what it happens...

**Comment by tbak** [comment]
We should use ephemeral ports in tests. We do this now in most of the tests that create server sockets, but not everywhere. Thank you for spotting this.
