### ISSUE TITLE
Limiting the number of instances of an application

### ISSUE THREAD

**Issue by andreldm** [Netflix/eureka#772]
I'd like to know if it's possible to limit the number of instances registered at a given time.

**Comment by qiangdavidliu** [comment]
@andreldm there are no limits (either on total number of instances, or number of instances per application) currently. Is this some new functionality you are looking at?

**Comment by andreldm** [comment]
I was trying to limit the number of instance to only one at a time. Now I'm convinced this defeats the whole point of service discovery, so Eureka should not be ideal to my case.

**Comment by qiangdavidliu** [comment]
@andreldm one of the tenants of eureka is that instances are abstracted away and application talk to each other over some fungible set of physical instances. If your use case require limiting it to just 1 instance, then yes eureka doesn't make too much sense.
