### ISSUE TITLE
404 in Wiki

### ISSUE THREAD

**Issue by stevewallecs** [Netflix/eureka#775]
A 404 is returned when trying to access http://netflix.github.io/eureka/javadoc/eureka-core/com/netflix/eureka/EurekaServerConfig.html from https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication

**Comment by qiangdavidliu** [comment]
Hi @stevewallecs we are working on some updated documentation. Hold on.

**Comment by qiangdavidliu** [comment]
Fixed the broken link, closing this issue for now. Will be adding some higher level docs for configuration both the client and server later.
