### ISSUE TITLE
No war file created for eureka 2 server

### ISSUE THREAD

**Issue by cschneider** [Netflix/eureka#782]
The wiki says that I should have a eureka server war after the build.

The directory eureka/eureka2-server/build/libs only contains this though:
eureka2-server-2.0.0-SNAPSHOT.jar  eureka2-server-2.0.0-SNAPSHOT-javadoc.jar  eureka2-server-2.0.0-SNAPSHOT-sources.jar

I build using  
./gradlew build

Is this a bug or is the documentation just not up to date?

**Comment by qiangdavidliu** [comment]
Hi @cschneider eureka2 is not a jersey base application, so there is no war file generated. Having said this, the current stable eureka is the build on the master branch, which is the 1.x system. The 2.x system is currently not complete. Thanks.

**Comment by cschneider** [comment]
I know 2.x is not yet released. We are currently evaluating registries and eureka 2 sounds quite good from the API perspective. 
Does it make sense to already look into eureka2? Our product is going to go into production end of this year. Do you think eureka2 will be out until then?
If yes how do I start the server? I do not have the requirement for it to be a war.
