### ISSUE TITLE
Unversioned user agent when shading eureka-client

### ISSUE THREAD

**Issue by mattnelson** [Netflix/eureka#783]
When shading eureka-client the manifest is lost in favor of the parent. DiscoveryBuildInfo[1] assumes that the version can be obtained from the manifest. Which propagates itself as an unknown version on the client user agents[2].

```
Java-EurekaClient/v<version_unknown>
Java-EurekaClient-Replication/v<version_unknown>
```

Since eureka is using the `nebula.netflixoss` plugin a `eureka-client.properties` file is dropped in `META-INF`, I tried to use that file as a drop in replacement of the manifest and found some issues[3]. Do you have a preference for the resolution?
- Wait for gradle-info-plugin to be fixed, then use file as a `Manifest`
- Use the `eureka-client.properties` as is and parse out `Implementation-Version`

[1] https://github.com/Netflix/eureka/blob/v1.4.6/eureka-client/src/main/java/com/netflix/discovery/util/DiscoveryBuildInfo.java#L55
[2] https://github.com/Netflix/eureka/blob/v1.4.6/eureka-client/src/main/java/com/netflix/discovery/shared/transport/jersey/EurekaJerseyClientImpl.java#L198
[3] https://github.com/nebula-plugins/gradle-info-plugin/issues/28

**Comment by qiangdavidliu** [comment]
@mattnelson we are open to either resolution step, though I can foresee potential confusion w.r.t. option 2 as the (archaius based) configuration file for eureka is also called eureka-client.properties.

**Comment by mattnelson** [comment]
The `eureka-client.properties` file will be in the `META-INF` resource folder and while it is the same file name, it would take some work for a user to incidentally put this file on the archaius path. I'll get started on the plugin updates as that seems to be to most correct way to resolve this. I'll have a follow up PR to change eureka to fall back to `eureka-client.properties` once the plugin updates are available.
