### ISSUE TITLE
Improve documentation for the server configuration in the yml file.

### ISSUE THREAD

**Issue by agomezcafeto** [Netflix/eureka#785]
I can not find any documentation about how to configure the eureka server, specifically, documentation related with the yml file.

**Comment by qiangdavidliu** [comment]
@agomezcafeto eureka does not use a yml based configuration. Currently, the configs are self documented in javadoc in EurekaServerConfig.java, and you can get some highlevel set up information from https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2
