### ISSUE TITLE
The default jersey configuration makes the API logic unavailable

### ISSUE THREAD

**Issue by tsjsdbd** [Netflix/eureka#799]
Eureka server code [here](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/resources/ApplicationsResource.java#L150): if http client don't want gzip response, then the server will return result uncompressed.

but when you try this feature, it always return compressed result with Gzip。

after some investgation, i find the default jersey configuration let jersey always compress the response content.
1. [configuration1](https://github.com/Netflix/eureka/blob/bee851e469d0b0d7964743eb24d4ae52d23f0984/eureka-server-governator/src/main/java/com/netflix/eureka/EurekaInjectorCreator.java#L45)
2. [configuration2](https://github.com/Netflix/eureka/blob/master/eureka-server/src/main/webapp/WEB-INF/web.xml#L48)
@qizha

**Comment by qiangdavidliu** [comment]
@tsjsdbd thanks for noting this. What you say is correct. From the server side logic, gzip or not is an option governed by accept encoding. However the default server build contains, as a default filter, the Gzip encoding filter that gzips all responses regardless of accept encoding.

Internally, our usage levels are so high that is not realistic to produce unzip responses for any request, hence the default this way as a server side guard against all incoming requests.

If you do need the ability to return zipped or unzipped data depending on accept encoding, please edit your server build to remove the default usage of the gzip filter.

**Comment by tsjsdbd** [comment]
thanks for kindly reply, I agree that no need to return unzipped data for most scenario.
but on another hand, if the low level implementation finished the job about the feature, the appliacation level should no do it again, just focus on application logic maybe is more concise :-) 
(it have a little code deal with the HTTP header, and judge whether compress the response, and some code for compress algorithm)
