### ISSUE TITLE
How long is the registration information retained on the client side after eureka server closed

### ISSUE THREAD

**Issue by magicDong88** [Netflix/eureka#804]
Application(A) as a service was registered in the eureka server, so another application(B) was able to call the service (A) by eureka client. Then I shutdown the eureka server, What I'm confused about is that the app(B) still was able to call the service(A) during about 30 seconds. 
Could you please explain how long is the registration information retained on the client side after eureka server closed and which property affect the duration.
Thank you,

**Comment by qiangdavidliu** [comment]
Hi, if you are using the provided java eureka-client, then the registry cache on the client side will be forever and does not expire. The data will update if (at least one) eureka server exist and is reachable, and if no eureka servers exist, then the cache will essentially be frozen in time. Note that the default DiscoveryClient.java implementation offers the method getLastSuccessfulRegistryFetchTimePeriod() for users to monitor for staleness of the local registry cache.

If by closing the server, you mean the shutdown of the server for Application(A), then the entries for Application(A) will be purged from the local cache of the client on Application(B). The time delays are:

A shutdown gracefully -> eureka server removes entries for A (0s delay)
A has a dirty shutdown -> eureka server evicts entries for A (90s delay)
        +
B cache update -> B see cache update for removal of A (0-30s cache refresh cycle)

Also please note that if you run with a small number if instances, you may be subject to self-preservation as described here (https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Peer-to-Peer-Communication), and may want to tune the self-preservation thresholds as necessary.
