### ISSUE TITLE
Optimize amazon metadata service calls

### ISSUE THREAD

**Issue by NiteshKant** [Netflix/eureka#81]
This code:

https://github.com/Netflix/eureka/blob/42d73d3e36be60e8ddad3ef2014da286c823c8a5/eureka-client/src/main/java/com/netflix/appinfo/AmazonInfo.java#L118

does 7 network calls for every AmazonInfo.autoBuild() call which gets triggered by default every 30 seconds by InstanceInfoReplicator thread in DiscoveryClient.

We can optimize this to only fetch the public hostname & IP which can only change after an instance has started. We can cache everything else.

**Comment by tbak** [comment]
This was greatly optimized in release 1.1.158
