### ISSUE TITLE
Old 'javax.ws.rs' library

### ISSUE THREAD

**Issue by Writtscher** [Netflix/eureka#810]
I've come across some nasty dependency clashes by using eureka-client jar and some newer libraries. Eureka-Client jar does depend on **jsr311** which is the old specification. Some of my dependecies do require **javax.ws.rs-api** which is the new one. For example **javax.ws.core.Response** is different in the new version and this causes some troubles for me. I've exluded the old one but this is just a ticking bomb.

Are there plans to migrate to the new api specification?

**Comment by qiangdavidliu** [comment]
@Writtscher we have decided to take a different direction and will be making the client side of eureka independent of jaxrs completely. Work is being done internally, however we don't have any timelines that can be shared as of yet.

**Comment by Writtscher** [comment]
Well thanks for the quick answer. I'm fine for now pulling the new library and exclude the *jsr311* dependecy as there is no failure at the moment.
