### ISSUE TITLE
Eureka Server Basic HTTP Auth configuration

### ISSUE THREAD

**Issue by moizkhan2712** [Netflix/eureka#814]
Hi,

I've managed to get multiple Eureka servers up, running and synchronized without issue. Looking at the docs,class definitions and other forum posts, there doesn't seem to be a clear way to implement HTTP authentication server-side. Is this possible at all or not? It looks to be possible in the spring-cloud-netflix eureka repo from this [post](http://stackoverflow.com/questions/28974752/securing-eureka-in-spring-cloud).

Thanks & Regards,
Moiz Khan

**Comment by qiangdavidliu** [comment]
@moizkhan2712 our internal set-up do SSL via fronting the eureka tomcat servers with an apache layer.
