### ISSUE TITLE
Add support for custom HostnameVerifier

### ISSUE THREAD

**Issue by bitsofinfo** [Netflix/eureka#816]
There seems to be no way to specify a custom HostnameVerifier for the DiscoveryClient.

Can this support be easily added?

See #812

**Comment by qiangdavidliu** [comment]
Hi @bitsofinfo that sounds like a useful addition for eureka. We are a bit swamped with other work at this moment, would you like to try a PR for this feature? Thanks.

**Comment by mattnelson** [comment]
This has been released with 1.8.5

https://github.com/Netflix/eureka/releases/tag/v1.8.5

**Comment by bitsofinfo** [comment]
should this be closed?
