### ISSUE TITLE
How can i listen client register event in eureka server?

### ISSUE THREAD

**Issue by fengbaicanhe** [Netflix/eureka#820]
Is there any mechanism in **eureka server** ,that i can listen all eureka client register/deregister event, when i    catch the event,so i can send a notification to someone

**Comment by qiangdavidliu** [comment]
Hi @fengbaicanhe the current eureka server implementation have some level of caching, and does not support real time notifications.

**Comment by fengbaicanhe** [comment]
@qiangdavidliu  Is there any plan for this feature?

**Comment by qiangdavidliu** [comment]
@fengbaicanhe there's nothing on that that we can commit to at the moment unfortunately.

**Comment by fengbaicanhe** [comment]
ok, thanks @qiangdavidliu

**Comment by Luuuuuu** [comment]
@qiangdavidliu is there any detail explanation about cache level implementation?
