### ISSUE TITLE
VPC Deployments

### ISSUE THREAD

**Issue by ShadySQL** [Netflix/eureka#823]
Not sure where to ask this - marked also a question on the google group. I essentially want to know if Eureka only supports deployments of EIP. I dont want to advertise all our services to the world.

**Comment by qiangdavidliu** [comment]
Hi @ShadySQL eureka support other forms of fixed addresses. such as ENI and Route53 DNS (which in EC2 vpc can be private). In all cases (EIP or otherwise) you can secure your service with Security Groups.

**Comment by bsushant-athena** [comment]
@qiangdavidliu what value to provide for `eureka.serviceUrl.us-east-1a=` ??
As private IP's are assigned automatically so we can not hardcode in the code ?
