### ISSUE TITLE
Where does eureka store the registration data?

### ISSUE THREAD

**Issue by killjason** [Netflix/eureka#825]
Where does eureka store the registration data? in Memory? or both memory and file?

**Comment by spencergibb** [comment]
I'm memory

**Comment by killjason** [comment]
if all the eureka servers crash, how to recover registration data?

**Comment by marcosbarbero** [comment]
@killjason if it all crashes the data will be rebuild by the service registration heat beat. As the first startup happens.

**Comment by killjason** [comment]
@marcosbarbero , OK, got it, thx~

**Comment by nikhil101982** [comment]
How does Heartbeat know ip to ping, if the Eureka server crashes then it will change to the new Eureka server.
