### ISSUE TITLE
register only one rest/method/class to Eureka server

### ISSUE THREAD

**Issue by killjason** [Netflix/eureka#827]
In the Eureka client application, we defined 'spring.application.name'  in the file 'application.properties'.
so this application will register to Eureka server, If I just want to register one rest/method/class of this Eureka client application, How should I do?

**Comment by spencergibb** [comment]
This is the wrong repo to ask. Use spring cloud Netflix please.

**Comment by killjason** [comment]
@spencergibb , OK, I create a issue in spring cloud netflix:
https://github.com/spring-cloud/spring-cloud-netflix/issues/1222
