### ISSUE TITLE
Eureka-server.properties has content of MANIFEST.MF on distributions

### ISSUE THREAD

**Issue by miggy8234** [Netflix/eureka#828]
For Eureka-client since version 1.4.6 the Eureka-server.properties file has the exact same content as the MANIFEST.MF inside of the META-INF folder. So when deployed the default file reflects that of MANIFEST.MF. (Issue in version 1.4.7-rc.3 to current version 1.4.11-rc.1)

**Comment by qiangdavidliu** [comment]
Hi @miggy8234 do you mean the configuration based eureka-server.properties? The one that is sourced by the configuration system (archaius) should be under the path WEB-INF/classes/eureka-server.properties .

**Comment by miggy8234** [comment]
Hello @qiangdavidliu , No I mean if I download the latest jar from the maven central repository and deploy it to a server. The eureka.property files will have the same content as the MANIFEST.MF.

Downloaded from here: http://search.maven.org/#search%7Cga%7C1%7Ceureka-client

**Comment by qiangdavidliu** [comment]
Hi @miggy8234 your link is for the client (eureka-client), do you mean the client or the server? For the eureka server themselves, you'll need to build them as a war which packages in the eureka-server.properties prop file.

**Comment by rs017991** [comment]
It's the war file itself:
https://repo1.maven.org/maven2/com/netflix/eureka/eureka-server/1.5.3/eureka-server-1.5.3.war

Take a look at **META-INF/eureka-server.properties**

**Comment by qiangdavidliu** [comment]
Hi @rs017991 the correct property file is in the war at /WEB-INF/classes/eureka-server.properties. The file in META-INF may have the same name, but that is purely an artifact of the war name and is auto generated by the build. It does not affect actual property loading of the property file.

Thanks.
