### ISSUE TITLE
multiple copies of NodeJS service registering from same machine. Eureka Server cannot register

### ISSUE THREAD

**Issue by deekshasharma** [Netflix/eureka#854]
I am running NodeJS service say **MyService** on 3 different ports(8080,8081,8082) on single AWS EC2 machine. Now when my services register with Eureka Server. I see that Eureka server only registers the last instance of service that started on  port 8082. So basically it registers and keeps the data of single service(host:port) if the Amazon instance-id and Service name are same for all instances of MyService.
Is this a bug with Eureka or it is designed to have the service of same type to be deployed on different machines.

Another thing I noticed: With the same setup when I register Service1 , Service2 and Service3 with different names, they are registered with Eureka Server. But becaue its the same service running on 3 ports I need the information about all instances (host1:port1, host2:port2, host3:port3) under the same application name.

**Comment by qiangdavidliu** [comment]
@deekshasharma the default id for eureka registration is the instanceId of the EC2 instance, however there is configuration available to customize the id so they are unique across your services. Are you registering by direct http POST? If you, you'll want to supply a custom instance_id field at the InstanceInfo level.

Similarly, the port field in the InstanceInfo is available to be customized with the port of your services.

**Comment by deekshasharma** [comment]
Thanks for the reply!
Yes I am using http POST to send the registration payload via a Node JS eurekaClient.
I got it what you are saying. We are anyways customizing the appName and port when sending the registration info. We can also do the same for instance-id. 

So to resolve this issue we are currently providing a suffix to our service name like 
(myservice-port1, myservice-port2) and doing that resolves our issue even though the instance-id is same for all.

**Comment by qiangdavidliu** [comment]
👍
