### ISSUE TITLE
Make registration error message more meaningful when using JSON

### ISSUE THREAD

**Issue by drse** [Netflix/eureka#857]
Currently, when using `POST` to register an app with `JSON`, omitting the `port`, `securePort`, and `dataCenterInfo` structures (`$`, `@enabled`, `@class`) produces a generic message:

``` json
{
  "error": "cannot parse request body"
}
```

It's not directly evident how the XML XSD maps to JSON, would be nice if there was more detailed feedback, or a silent fail that can assume defaults for those values.

**Comment by shenpei1989** [comment]
I have the same error now,how did you solve? Can you give me a example of json? Thanks! @drse

**Comment by shenwenxin** [comment]
account same questions, hope get reply!
