### ISSUE TITLE
XSD doc is incomplete and has errors

### ISSUE THREAD

**Issue by vitosamson** [Netflix/eureka#858]
It looks like the XSD spec does not match what Eureka actually expects for the `port` and `securePort` fields, which is:

``` json
"port": {
  "$": <positiveInt>,
  "@enabled": <bool>
},
"securePort": {
  "$": <positiveInt>,
  "@enabled": <bool>
}
```

The XSD spec lists `port` and `securePort` as just `positiveInteger` types. The XSD should be updated to reflect the required structure for those fields.

In addition there seems to be a required `"@class"` parameter on the `dataCenterInfo`. I couldn't find anything about that parameter in the XSD spec.

**Comment by qiangdavidliu** [comment]
HI @vitosamson thanks for the issue, we'll take a look at the documentation.
