### ISSUE TITLE
eureka & swagger-ui

### ISSUE THREAD

**Issue by yihukurama** [Netflix/eureka#859]
- Brixton.SR5 eureka  and swagger ui 2.6.0

I just use swagger ui and eureka for my project. However there is no reproducing about the issue, swagger-ui work well but eureka cannot found the application name. I use two day for this bug, at last I common all about swagger ui and eureka found the service.Could you help me to solve this issue.

**Comment by qiangdavidliu** [comment]
Hi @yihukurama you may want to ask this question at https://github.com/spring-cloud/spring-cloud-netflix

**Comment by Triggerself** [comment]
I have the same issue
