### ISSUE TITLE
Is there a use case for different values of virtualHostname and secureVirtualHostname?

### ISSUE THREAD

**Issue by william-tran** [Netflix/eureka#860]
When is it useful to have a secureVirtualHostname that's different from virtualHostname? We have other flags to signify whether we want to use the secure port (eg ribbon.IsSecure and isSecure flags on EurekaClient methods) and whether that securePort is enabled (InstanceInfo.isSecurePortEnabled). I can see a use for having a null secureVirtualHostname if isSecurePortEnabled is false, then the instance won't come up in a query when the isSecure flag is true, and vice versa for virtualHostname. But I can't come up with a reason to have different non-null values of those two properties.

**Comment by qiangdavidliu** [comment]
Hi @william-tran some of the usage of the metadata such as these are driven by convention, so it depends somewhat on how you want to interpret this. In one scenario it might be used as a way to have a permissive server (I support both) and restrictive clients.

**Comment by csterwa** [comment]
Thank you for the response @qiangdavidliu. We are having difficulty thinking of use cases where virtual hostname and secure virtual hostname should have different non-null property values. Would you be able to point towards customer use cases where this is used?
