### ISSUE TITLE
Can't upsert Route53 Record Set

### ISSUE THREAD

**Issue by elnur** [Netflix/eureka#863]
I'm trying to use the Route53 binder. It works for the first time when a record set doesn't exist. But after instances in an ASG get replaced, the binder can't upsert the same record set it created earlier.

I'm seeing this in the logs:

```
com.netflix.eureka.aws.Route53Binder     : Unable to find free domain in [1c.eureka.example.internal.]
```

Any ideas what's wrong? Any workarounds?

**Comment by elnur** [comment]
I gave full EC2 profile permissions for Route53, EC2, and ASG just in case it could be a permission problem. But it didn't help.

**Comment by elnur** [comment]
Okay, it looks like it's intentional. The binder only looks for free domains. That doesn't make much sense though. Thanks to autoscaling, instances come and go but it'd be nice to have a fixed number of domains to have stable locations of Eureka instances. So if an instance a domain points to is long gone, this Route53 binder can't update the domain to point to a new Eureka instance.

**Comment by qiangdavidliu** [comment]
@elnur we do not use the Route53Binder at Netflix, and it was a component that contributed to us externally. The implementation as it is today may be specific to the contributor's internal needs. You can try to contact @aroger-r7 to discuss.

**Comment by elnur** [comment]
Later, I've figured out that the Route53 binder unbinds itself from domain name on shutdown. But it was too late since I got it all working with EIP. 🙂 

The EIP approach is more predictable here because an EIP gets released when an EC2 instance dies without a clean shutdown, and hence Eureka will assign an EIP to itself in any case. While the Route53 binder relies on proper shutdown to unbind itself.

**Comment by qiangdavidliu** [comment]
@elnur glad to hear that you have resolved your issue.
