### ISSUE TITLE
How to get CPUs info from discoveryClient?

### ISSUE THREAD

**Issue by flamhaze5946** [Netflix/eureka#864]
In this ClassMeta's code I have not found any method to get clients' runtime infomation.
by the way, every time I start my application, about 30s - 60s eureka server can register my application's information up, is it a heartbeat problem? Can I set the heartbeat quickly?(I want to update Clients' information quickly, too)
Thank you !

**Comment by flamhaze5946** [comment]
Now I try to registerAppMetadata to achieve it, thanks

**Comment by qiangdavidliu** [comment]
👍
