### ISSUE TITLE
Eureka propagates registry info to its peer node only(peer's peer cannot get this replication)

### ISSUE THREAD

**Issue by wanghongfei** [Netflix/eureka#865]
I have three Eureka instances A, B and C. A's peer is pointed to B, B is pointed to C, C is pointed to A:

![yvmm2](https://cloud.githubusercontent.com/assets/4201347/19636216/8c1f7580-99fa-11e6-8509-bfedd048aef4.jpg)

When I registered my service to Eureka A, Eureka B got this registry info as expected. But C got nothing at all, which means B didn't propagate info to C.  

Is this the correct behavior as Eureka being designed or there's something wrong with my configuration?

UPDATE
---
I found the answer from `PeerAwareInstanceRegistry#replicateToPeers()`, it contains following code:
```
// If it is a replication already, do not replicate again as this will create a poison replication
            if (peerEurekaNodes == Collections.EMPTY_LIST || isReplication) {
                return;
            }
```
Why don't we add some description for this to wiki?

**Comment by qiangdavidliu** [comment]
@wanghongfei eureka server set up actually requires that you configure as peers all other available servers. So in your example, you would configure both B and C to be peers of A. I have updated the wiki page https://github.com/Netflix/eureka/wiki/Deploying-Eureka-Servers-in-EC2. Thanks.
