### ISSUE TITLE
Delay call to DiscoveryClient.fetchRegistry at boot

### ISSUE THREAD

**Issue by arakelian** [Netflix/eureka#867]
I'm writing a simple application which combines Eureka server, Discovery client, and Zuul Proxy into a single project.  Instead of static routes, I want my Zuul proxy to use Discovery client.

eureka.client.registerWithEureka is set to false.  This is the recommended setting for standalone Eureka servers.

If I set eureka.client.fetchRegistry to false, Eureka server boot and operates normally, but Zuul Proxy will not work because Discovery Client is basically limited to the static routes.  It's unaware of the application registered with Eureka server.

If I set eureka.client.fetchRegistry to true (and eureka.client.serviceUrl.defaultZone pointing back at itself), the Eureka server boots, and Zuul Proxy works.  However, I see a spurious error in the logs at boot time, because DiscoveryClient attempts to immediately load the list of applications due code at line 408.

 if (clientConfig.shouldFetchRegistry() && !fetchRegistry(false)) {
       fetchRegistryFromBackup();
}

It'd be great if we could have another flag, "shouldFetchRegistryImmediately" so that we could change these lines to read:

 if (clientConfig.shouldFetchRegistry() && clientConfig.shouldFetchRegistryImmediately() && !fetchRegistry(false)) {
            fetchRegistryFromBackup();
        }

In my use case, I would set eureka.client.shouldFetchRegistryImmediately to false, and DiscoveryClient would then reload after 30 seconds (the default refresh interval), when the single standalone application has booted and is ready to respond.

**Comment by garakelian** [comment]
@qiangdavidliu, respectfully, you can guard against, make it the default setting, etc., and still allow someone to configure it so that it doesn't load immediately. I'd be happy to submit a PR for this change if I thought that it would be merged.

**Comment by qiangdavidliu** [comment]
@garakelian we welcome any PR that improves eureka from the community.

**Comment by arakelian** [comment]
Closing this as I'm currently not using Eureka. Thank you.

**Comment by Tires** [comment]
I tried to implement this, but I was not able to add any configuration parameter by changing EurekaClientConfig, This interface is implemented by org.springframework.cloud.netflix.eureka.EurekaClientConfigBean also. Only option for me is to remove the whole block:

```
        if (clientConfig.shouldFetchRegistry() && !fetchRegistry(false)) {
            fetchRegistryFromBackup();
        }
```

Any suggestions?
