### ISSUE TITLE
Eureka client can't read the server's registry.

### ISSUE THREAD

**Issue by jianminli** [Netflix/eureka#868]
I have set up an Eureka server and a client, both of which are written in spring boot. I am using these two application for my Spring MVC testing. The server and client are running well.

Server's configuration application.properties is as below.

> server.port=8761
> spring.application.name=service-itself
> eureka.client.service-url.default-zone=http://localhost:8761/eureka/
> eureka.client.register-with-eureka=true
> eureka.client.fetch-registry=false
> logging.level.com.netflix.eureka=OFF
> logging.level.com.netflix.discovery=OFF

client's is as below: application.yml

> spring:
>   application:
>     name: say-hello
> 
> server:
>   port: 8090
> 
> eureka:
>   client:
>     service-url:
>       defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

When accessing the Eureka dashboard localhost:8761, I can see that client has been registered.

For my Spring MVC gateway, as it is not a Spring boot project, so I copied the [example](https://github.com/Netflix/eureka/blob/master/eureka-examples/src/main/java/com/netflix/eureka/ExampleEurekaClient.java) to my project simply for testing whether it can connect to the Eureka server and retrieve the registered the instance of "say-hello" client. Unfortunately, it cannot do so with saying "Cannot get an instance of example service to talk to from eureka" which is printed at line 76 in the example class.

Here is the eureka-client.properties placed in gateway's classpath. I can confirmed that the Client class is reading the config file.

> eureka.name=gatewayEurekaClient
> eureka.vipAddress=say-hello
> eureka.port=8761
> eureka.preferSameZone=true
> eureka.preferSameZone=true
> eureka.shouldUseDns=false
> eureka.serviceUrl.default=http://localhost:8761/eureka
> eureka.serviceUrl.defaultZone=http://localhost:8761/eureka

Some debug information here:

> instanceInfo    InstanceInfo  (id=234)  
>     actionType  null    
>     appGroupName    "UNKNOWN" (id=246)  
>     appName "GATEWAYEUREKACLIENT" (id=247)  
>     asgName null    
>     countryId   1   
>     dataCenterInfo  PropertiesInstanceConfig$1  (id=248)    
>     healthCheckExplicitUrl  null    
>     healthCheckRelativeUrl  "/healthcheck" (id=253) 
>     healthCheckSecureExplicitUrl    null    
>     healthCheckUrl  "http://A156N7AB89AXNZQ:8761/healthcheck" (id=254)  
>     homePageUrl "http://A156N7AB89AXNZQ:8761/" (id=255) 
>     hostName    "A156N7AB89AXNZQ" (id=256)  
>     instanceId  "A156N7AB89AXNZQ" (id=256)  
>     ipAddr  "10.209.66.64" (id=257) 
>     isCoordinatingDiscoveryServer   Boolean  (id=258)   
>     isInstanceInfoDirty false   
>     isSecurePortEnabled false   
>     isUnsecurePortEnabled   true    
>     lastDirtyTimestamp  Long  (id=260)  
>     lastUpdatedTimestamp    Long  (id=263)  
>     leaseInfo   LeaseInfo  (id=264) 
>     metadata    ConcurrentHashMap<K,V>  (id=266)    
>     overriddenstatus    InstanceInfo$InstanceStatus  (id=267)   
>     port    8761    
>     secureHealthCheckUrl    null    
>     securePort  443 
>     secureVipAddress    null    
>     secureVipAddressUnresolved  null    
>     sid "na" (id=270)   
>     status  InstanceInfo$InstanceStatus  (id=271)   
>     statusPageExplicitUrl   null    
>     statusPageRelativeUrl   "/Status" (id=272)  
>     statusPageUrl   "http://A156N7AB89AXNZQ:8761/Status" (id=273)   
>     version "unknown" (id=274)  
>     vipAddress  "say-hello" (id=275)    
>     vipAddressUnresolved    "say-hello" (id=275)

**Comment by jameskaron** [comment]
Could you tell me how you solved the problem?
