### ISSUE TITLE
DiscoveryClient.shutdown() does not shutdown all Threads - MemoryLeak

### ISSUE THREAD

**Issue by klues** [Netflix/eureka#872]
Hi,

I'm using Eureka-Client 1.4.11.
We are running applications containing an eureka-client on Tomcat 7.0.42 and on undeploy although I call EurekaClient#shutdown(), I get the following warning:
SEVERE: The web application appears to have started a thread named [AsyncResolver-bootstrap-1] but has failed to stop it. This is very likely to create a memory leak.

After some time of debugging I found out that the reason is to be found in AsyncResolver#shutdown():
At AsyncResolver.java:144 if I call
executorService.shutdownNow(); 
instead of
executorService.shutdown();

then I do not get the Tomcat-Message anymore. I think the reason is that ExecutorService#shutdown() >>...Initiates an orderly shutdown in which previously submitted tasks are executed...<< (see https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html#shutdown() ), while shutdownNow() >>Attempts to stop all actively executing tasks<<, and therefore the "backgroundTask" is started once more, which itself schedules a new Task (see TimedSupervisorTask.java:61) and therefore some Thread does not termiate...

I do not fully understand these Threads, but if I call executorService.shutdownNow() as mentioned above, I get one FutureTask as result, that was terminated:
http://prntscr.com/d7l5zf
...and Tomcat does not report a memory-leak issue anymore.
Therefore I would recommend to replace AsyncResolver.java:144-145 by:
executorService.shutdownNow();
threadPoolExecutor.shutdownNow();

**Comment by klues** [comment]
created pull request for this issue

**Comment by qiangdavidliu** [comment]
Thanks @klues fixed in #876
