### ISSUE TITLE
Questions: What is the road map for Eureka 2 and is there a timeframe for when Spring Cloud will adopt it 

### ISSUE THREAD

**Issue by russBDigitalGlobe** [Netflix/eureka#875]
Hi,
I'm wondering what the road map is for Eureka 2 and when Spring Cloud will adopt it as part of their release?

Thanks in advance,

Russ Baker

**Comment by spencergibb** [comment]
This is not the forum for spring cloud. And, someone correct me if I'm wrong, but eureka 2 is on hold.

**Comment by qiangdavidliu** [comment]
@spencergibb that is correct. We've done some major change to our approach, and the code that is currently in the 2.x branch can be considered archived.
