### ISSUE TITLE
Register instance API‘s TPS is too low

### ISSUE THREAD

**Issue by tianxiaoliang** [Netflix/eureka#877]
I use ab to test register instance API， the performance is 2k TPS, and the CPU usage is only about 200%，but The baremental has 72 cpu cores，Is there any limit to cpu usage in source code

**Comment by tianxiaoliang** [comment]
Also the heartbeat perf is 5w tps, it became 16w TPS after I open keep alive in tomcat,but register instance API perf is still 2k,and in response header there is no connection:keep-alive header.
So in server side,the register instance handler disabled keep alive? Why?

**Comment by tianxiaoliang** [comment]
I found there is a lock in register method, that makes perf low and low cpu usage，why eureka lock before register a instance？
private final Lock read = readWriteLock.readLock();

**Comment by qiukeren** [comment]
2K TPS is enough for most conditions.
Even in alibaba, the registry center is far from 2K TPS.

2K 的TPS大多数情况下已经够了。
即便是阿里，注册中心每秒也不会注册2K个应用。

**Comment by qiangdavidliu** [comment]
Thanks @qiukeren . @tianxiaoliang agree that the registration code path for eureka can probably be improved for higher TPS, however we have not had the need at Netflix to work on this.
