### ISSUE TITLE
It takes minutes to discover instance in eureka

### ISSUE THREAD

**Issue by tianxiaoliang** [Netflix/eureka#878]
after register a instance,eureka returned 204,but sometimes it takes a long time to query the instance by API, why?

also ,if the instance dead and doesn't  deregister in eureka.it may takes minutes to disappear in eureka.why?

How can I change this to discover at once after register

**Comment by mattnelson** [comment]
The latency is likely being caused by the response cache.

https://github.com/Netflix/eureka/blob/v1.6.1/eureka-core/src/main/java/com/netflix/eureka/registry/ResponseCache.java
