### ISSUE TITLE
App not getting re-register once Eureka server restart...

### ISSUE THREAD

**Issue by aserg** [Netflix/eureka#879]
I register my app on  Eureka  Server  through PCF market Service...The problem is that when Eureka Server gets restarted all apps or client  which was alerady register  gets unbinded and never gets register again automatically even though all apps are already binded to Eureka Server. I have to again restart all my apps to gets themselves register on Eureka Server.....Any help is highly appreciated

**Comment by qiangdavidliu** [comment]
@aserg it looks like your question is more pertinent to the spring-cloud-netflix usage of eureka. I would recommend that you ask your question at https://github.com/spring-cloud/spring-cloud-netflix
