### ISSUE TITLE
What's the relationship about region, zone and a eureka cluster?

### ISSUE THREAD

**Issue by eacdy** [Netflix/eureka#881]
Since I havn't used AWS, I wonder what's the relationship about region, zone and a eureka cluster. I've  drew a picture below, am I right?
![4-2](https://cloud.githubusercontent.com/assets/9031050/21100232/e7157014-c0ad-11e6-8b36-93bf0bd9b6fe.png)

**Comment by samdvr** [comment]
Each region is a geographical location in AWS, every region has multiple availability zone which are completely isolated from each other(Think of it as a separate datacenter)
For example U.S. East(Virginia) is one region with: us-east-1b, us-east-1c, us-east-1d availability zones. More info [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html)

**Comment by eacdy** [comment]
@samdvr Got it.
Seems that eureka can be deployed in different zones, so I wonder whether the picture I drew is right.

**Comment by qiangdavidliu** [comment]
@eacdy your picture is correct. At Netflix our set up is to deploy several servers per zone, and all the servers in the region (across the zones) are peered together for redundancy.
