### ISSUE TITLE
409 Conflict in replication task

### ISSUE THREAD

**Issue by fredboutin** [Netflix/eureka#882]
We got a bunch of 

> The replication of task xxx failed with response code 409

in production after putting an instance out of service and then restarting an application on it. We had to reboot eureka because it never recovered from it. From that comment in the JerseyReplicationClient : `
// In the case of replication, send the current instance info in the registry for the
replicating node to sync itself with this one.` I tried to track down what happens when a 409 is returned and it seems like it is not handled on the server making the request. The server should use the entity instance info it receives with the 409, but it doesn't seem to happen anywhere I checked. I couldn't reproduce the bug, but that's what I've seen from navigating in the code. Does this rings a bell? Any help or clue would be appreciated.

Thanks!

**Comment by jebeaudet** [comment]
I'd like some input as well, we had the same problem

**Comment by qiangdavidliu** [comment]
Eureka uses a client side field within InstanceInfo `lastDirtyTimestamp` for conflict resolution. If you are using the java eureka-client, this should be taken care of already. However if you are using direct http calls, then for any client side updates that changes some InstanceInfo value (e.g. a POST or a PUT), it is recommended that an extra queryParam `lastDirtyTimestamp=System.currentTimeMillis()` be added.

**Comment by fredboutin** [comment]
Thanks for your answer, I guess this is our problem! When we put it out of service, we use this call manually (in a custom UI) : PUT /eureka/apps/{applicationId}/{instanceId}/status?value=UP and we are not specifying any lastDirtyTimestamp.

**Comment by 995270418L** [comment]
and how to specifying the lastDirtyTimestamp param or where add it into eureka client

**Comment by jebeaudet** [comment]
@995270418L It's added automatically by the eureka client. We were using a custom UI that made ajax requests without the `lastDirtyTimestamp` parameter (it's optional).

**Comment by sangyuruo** [comment]
@fredboutin @jebeaudet  Which version has corrected this Issue? thanks!

**Comment by fredboutin** [comment]
We corrected the way we call eureka by adding the lastDirtyTimestamp parameter, no version update was necessary.

**Comment by jebeaudet** [comment]
@sangyuruo you _might_ need https://github.com/Netflix/eureka/issues/933 as well for a complete fix for this issue.

**Comment by sangyuruo** [comment]
@fredboutin @jebeaudet Thanks for your answer!
