### ISSUE TITLE
Register a service under several names

### ISSUE THREAD

**Issue by MarcP04** [Netflix/eureka#884]
I'm looking to register a service under several names to handle service versionning issues, but maybe my approach is totally wrong, you tell me.

Here's what I want to do:
I have a service "Service". The first version of has a "ServiceV1" REST controller, it registers as "ServiceV1" in Eureka registry. I have a feign client for "FeignClientV1" corresponding to that "ServiceV1".
Later, new functionnalities are added to my service. I register them in a "ServiceV2" REST controller, and create a "FeignClientV2" which contains only the new functionnalities. My problem is that today I can only register my service as "ServiceV2" in Eureka registry, while I would like to register it as "ServiceV1" and "ServiceV2" because I want the clients only having the FeignClientV1 to be able to work with either my service v2 or my service v1.

I didn't find anyway to do that, here are related subjects I found:
http://stackoverflow.com/questions/25859782/how-to-locate-services-by-version-with-netflix-eureka-and-ribbon
http://stackoverflow.com/questions/36712303/registering-one-application-multiple-times-aliases-in-netflix-eureka
https://github.com/Netflix/eureka/issues/598 (but I don't see how "eureka.vipAddress" fills the need)

**Comment by qiangdavidliu** [comment]
@MarcP04 you can register multiple vipAddresses for a service, as long as they are comma delimited (e.g. vipAddress=vip1,vip2). In this way, you can use a strategy where your ServiceV1 register with vip `vip1`, and a newer deployment that also support the v2 api register with a vip of `vip1,vip2`.

From a client side, clients that ask for vip1 will get servers for both older and newer deployments, whereas clients that want vip2 will only get the newer servers.
