### ISSUE TITLE
cannot access javax.inject.provider

### ISSUE THREAD

**Issue by xiaoerlyl** [Netflix/eureka#885]
when i try the eureka client examples in a maven project, it said "cannot access javax.inject.provider".

**Comment by cloudgc** [comment]
how did  you  resolve ,i hava same quesition

**Comment by Bananenbieger1234** [comment]
You need to add following dependency:
`<dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
 </dependency>`
