### ISSUE TITLE
Eureka peer-peer communication doc is ambiguous

### ISSUE THREAD

**Issue by asarkar** [Netflix/eureka#890]
> If any time, the renewals falls below the percent configured for that value (below 85% within 15 mins), the server stops expiring instances to protect the current instance registry information.

What does this mean? The service that stopped renewing is shut down (pretty hard to believe Eureka can do that)? Or Eureka just takes that instance out of registry?

> In the case of network outages between peers, following things may happen
The heartbeat replications between peers may fail and the server detects this situation and enters into a self-preservation mode protecting the current state.

Does not receving a heartbeat from an Eureka peer treated the same as not receiving a heartbeat from other services?

**Comment by qiangdavidliu** [comment]
@asarkar thanks for the question. I looked at the related issues on spring-cloud and it looks like you have found the answers you need.

Out of curiosity, what versions of eureka are you running with? I read your blog (nice summary) and a few things with eureka/ribbon latencies have been improved recently.

**Comment by asarkar** [comment]
@qiangdavidliu Not all my questions have been answered. If you read my blog, you'd have seen references to 2 tickets opened on Spring Cloud that're still open. For the sake of completion, if you could take the time to answer those, I think the blog will become more useful.

[spring-cloud-netflix#373](https://github.com/spring-cloud/spring-cloud-netflix/issues/373)

[spring-cloud-netflix#203](https://github.com/spring-cloud/spring-cloud-netflix/issues/203)

Also, I'm interested in knowing what are the improvements in Eureka you mentioned. We've moved to using Kubernetes service discovery from Eureka so I don't have a ready answer of what version we were previously using.
