### ISSUE TITLE
Multiple eureka servers to lookup

### ISSUE THREAD

**Issue by erikgollot** [Netflix/eureka#892]
Is there a way to lookup multiple Eureka servers with Feign ?
I do not talk about multiple servers into multiple zones but really 2 or more Eureka servers not linked ?
My need is that we've one information system with its own Eureka server and a Group level information system with also its own Eureka server. The two Eureka servers cannot know each other.
Thanks

**Comment by erikgollot** [comment]
And some services are provided by the local information system and orher by the Group level information system

**Comment by qiangdavidliu** [comment]
@erikgollot it is possible to create multiple eureka-clients within the same JVM (if you avoid using DI), and potentially you may then be able to configure these separate clients to connect to the two separate server groups.

**Comment by erikgollot** [comment]
Oh yes thanks
It could be nice to add this capability into the annotation. I wiil see if I can investigate this
