### ISSUE TITLE
Problem peering with HTTP Authentication.

### ISSUE THREAD

**Issue by Milesy** [Netflix/eureka#893]
During troubleshooting at the following issue - https://github.com/spring-cloud/spring-cloud-netflix/issues/1647 I have came to see that the Jersey Client which is responsible for peering does not respect any HTTP authentication across the cluster.

This is within eureka-core-1.4.12

We use a shared Eureka defaultZone and all our of Eureka peers and the services which are discoverable must be locked down both with SSL and also with some authentication.

If we use a defaultZone like : 

`eureka.defaultZone=https://eureka:password@host1.business.net:8761/eureka/,https://eureka:password@host2.business.net:8761/eureka/`

everything works as expected, but it is not the ideal solution because those URLs are logged out into unsecured log files with the username and password within them.

The discovery client we configure in such a way:

```
    @Bean
    public DiscoveryClient.DiscoveryClientOptionalArgs discoveryClientOptionalArgs() {
        DiscoveryClient.DiscoveryClientOptionalArgs args = new DiscoveryClient.DiscoveryClientOptionalArgs();
        List<ClientFilter> filters = new ArrayList<>();
        filters.add(new HTTPBasicAuthFilter(eurekaUsername, eurekaPassword));

        if ("true".equals(eurekaLogging)) {
            filters.add(new LoggingFilter());
        }

        args.setAdditionalFilters(filters);

        return args;
    }
```

We would like the Jersey Client within the JerseyReplicationClient class to also be configurable so we can inject an authentication filter into it, for example where it is used here:

```
    @Override
    public EurekaHttpResponse<ReplicationListResponse> submitBatchUpdates(ReplicationList replicationList) {
        ClientResponse response = null;
        try {
            response = jerseyApacheClient.resource(serviceUrl)
                    .path(PeerEurekaNode.BATCH_URL_PATH)
                    .accept(MediaType.APPLICATION_JSON_TYPE)
                    .type(MediaType.APPLICATION_JSON_TYPE)
                    .post(ClientResponse.class, replicationList);
            if (!isSuccess(response.getStatus())) {
                return anEurekaHttpResponse(response.getStatus(), ReplicationListResponse.class).build();
            }
            ReplicationListResponse batchResponse = response.getEntity(ReplicationListResponse.class);
            return anEurekaHttpResponse(response.getStatus(), batchResponse).type(MediaType.APPLICATION_JSON_TYPE).build();
        } finally {
            if (response != null) {
                response.close();
            }
        }
    }
```

This is one of the fails we see within the logs:

```
26-01-2017 15:04:39 [TaskBatchingWorker-target_host1-18] ERROR c.n.e.c.ReplicationTaskProcessor - Batch update failure with HTTP status code 401; discarding 1 replication tasks
26-01-2017 15:04:39 [TaskBatchingWorker-target_host1-18] WARN  c.n.e.u.b.TaskExecutors - Discarding 1 tasks of TaskBatchingWorker-target_host1-18 due to permanent error
26-01-2017 15:04:50 [AsyncResolver-bootstrap-executor-0] INFO  c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Running the evict task with compensationTime 0ms
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Evicting 1 items (expired=1, evictionLimit=1)
26-01-2017 15:04:50 [Eureka-EvictionTimer] WARN  c.n.e.r.AbstractInstanceRegistry - DS: Registry: expired lease for EUREKA/host2:eureka:8761
26-01-2017 15:04:50 [Eureka-EvictionTimer] INFO  c.n.e.r.AbstractInstanceRegistry - Cancelled instance EUREKA/host2:eureka:8761 (replication=false)
```

I am looking for the appropriate approval within our business to contribute myself, if that will help get things moving quicker.

Regards,

Chris

**Comment by qiangdavidliu** [comment]
@Milesy thank you for the issue. We can take a look at this, but definitely if you are able to get the appropriate approval for a contribution, that'll likely lead to a quicker turn around.

**Comment by shivamgoel** [comment]
Is there a work around ?

**Comment by jonbcs** [comment]
Any solutions here. Surely one can exclude logging the defaultZone URL's at least?
