### ISSUE TITLE
Why properties eureka.securePort and eureka.securePort.enabled do not affect HomepageUrl and StatusUrl?

### ISSUE THREAD

**Issue by klues** [Netflix/eureka#894]
Hi,

I'm using eureka-client version 1.4.11 and trying I'm getting the infos of registered clients from my eureka-server using the method DiscoveryClient#getInstancesByVipAddress().

Now we want to use a secure connection between our application-clients and the services managed by eureka and therefore getting secure URLs from the InstanceInfos returned by DiscoveryClient#getInstancesByVipAddress().

**For me the expected behavior would be:**
setting the properties:
_eureka.securePort=443_
_eureka.securePort.enabled=true_
in my configuration should result in getting https-URLs from the instanceInfos retrieved by DiscoveryClient#getInstancesByVipAddress(), therefore I expect these values:
instanceInfo..getHomePageUrl() == **https**://< hostname >:**443**/home
instanceInfo.getStatusPageUrl() == **https**://< hostname >:**443**/status
instanceInfo.getHealthCheckUrl() == **https**://< hostname >:**443**/health

**But the actual behaviour is:**
with securePort.enabled=true
I get the following URLs:
instanceInfo..getHomePageUrl() == **http**://< hostname >:**80**/home
instanceInfo.getStatusPageUrl() == **http**://< hostname >:**80**/status
instanceInfo.getHealthCheckUrl() == **http**://< hostname >:**80**/health
and there is the additional property:
instanceInfo.getSecureHealthCheckUrl() == **https**://< hostname >:**443**/health

So i can use instanceInfo.getSecureHealthCheckUrl() for my purpose, but it seems strange for me that the other properties remain unsecure http-URLs if I set securePort.enabled=true.

**Comment by qiangdavidliu** [comment]
@klues thanks for raising this issue. What you describe make sense, however the reason it is this way today is primarily due to legacy reasons and unfortunately making large scale changes here would be difficult without breaking some level of backwards compatibility.
