### ISSUE TITLE
inter services communication not working via zuul routes

### ISSUE THREAD

**Issue by ajayaks** [Netflix/eureka#896]
I am trying to call service A from service B via application name and below is the setup.

1. Setup Eureka server and register other services and conductor server.
 conductor server is registered in eureka services list.
2. Setup zuul gateway and defining routing for conductor like below:- Zuul is running on 1113 port.
users:
      path: /apis/users/**
      serviceId: users-service
      stripPrefix: false

tasks:
      path: /apis/tasks/**
      serviceId: tasks-service
      stripPrefix: false

Both the services are working fine if i call them via zuul gateway in browser, meaning routing is fine.
http://localhost:1113/apis/users
http://localhost:1113/apis/tasks

Problem i am having is its not working user service is calling task service as below:-

Not working
restTemplate.getForObject(String.format("http://tasks-service/apis/tasks/") [Not working]

Below is working if i use server and port 
restTemplate.getForObject(String.format("http://localhost:8380/apis/tasks/") [working]

Its showing the correct name in services listed in eureka and working if i call that routes directly in browser but communication b/w the services is not working.

Please suggest.

**Comment by spencergibb** [comment]
This is not the proper forum for spring cloud Netflix

**Comment by ajayaks** [comment]
Would you please suggest or redirect me for the correct forum.

**Comment by spencergibb** [comment]
See https://github.com/spring-cloud/spring-cloud-netflix/issues/1666

**Comment by qiangdavidliu** [comment]
Thanks @spencergibb
