### ISSUE TITLE
Multiple eureka clients as docker instances in a single host

### ISSUE THREAD

**Issue by sankarbalu** [Netflix/eureka#902]
I am trying to setup multiple eureka clients as docker containers in a single VM. 

By default, with network mode as bridge, eureka exports the container id as host name. To override the same, i added -h $(hostname) to docker run command. This resolved the hostname that is sent by eureka clients on the heartbeat message to eureka server and now the clients are registered with exact host names (say Host1:Port1). 

But when I try to run a second instance of the same eureka client by triggering another docker container with a different port, the docker instance is up and running without any issues. But instead of registering a new instance on eureka server like Host1:P2, the old instance was overridden and now eureka dashboard only shows Host1:P2. 

Is there a better option to run multiple instances of the same eureka client in a single host and register them in eureka correctly?

**Comment by qiangdavidliu** [comment]
@sankarbalu eureka uniquely identifies a registering client via two keys, the instanceId and the appName. For your clients to be unique, you need to have at least one of these two be different between your clients.

It is possible to custom configure the instanceId of a client via config `eureka.instanceId=<some id>` (see https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/PropertyBasedInstanceConfigConstants.java#L11).

**Comment by qiangdavidliu** [comment]
Closing old issue. Please re-open if necessary.
