### ISSUE TITLE
Discover Services in Starting status

### ISSUE THREAD

**Issue by amit2103** [Netflix/eureka#903]
Hey,

We are trying to discover nodes from Eureka for a service.  I see that I can only see services which are in UP status after I try to get the nodes like :-  List<InstanceInfo> instances = application.getInstances();.

Is this by design or I need to do something extra to get all nodes, including one which are in Starting status (besides the ones in already UP Status).

Thanks

**Comment by qiangdavidliu** [comment]
Hi @amit2103 by default, this is the behaviour. This can be changed via configuration `eureka. shouldFilterOnlyUpInstances=false`. (See https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/DefaultEurekaClientConfig.java#L392)
