### ISSUE TITLE
Instances Renew Problem.

### ISSUE THREAD

**Issue by Jaredjin** [Netflix/eureka#905]
When I POST /refresh service node, The log show me service status is UP, but eureka server not receive UP log, the service is not exist and not available.
service log:
`com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
com.netflix.discovery.DiscoveryClient    : Unregistering ...
com.netflix.discovery.DiscoveryClient    : DiscoveryClient_SERVICE.SMS/10.128.17.115:service.sms:7002 - deregister  status: 200
com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application service.sms with eureka with status DOWN
o.s.c.n.e.s.EurekaServiceRegistry        : Registering application service.sms with eureka with status UP`

eureka server log:
`[c.n.e.registry.AbstractInstanceRegistry  : Cancelled instance SERVICE.SMS/10.128.17.115:service.sms:7002 (replication=false)
`

**Comment by qiangdavidliu** [comment]
@Jaredjin your logs looks a bit strange, there are both registration and also unregistration logs mixed together. Are you in a shutdown sequence?

Additionally, looks like you are using spring cloud netflix, so you might also be able to get help here:
https://github.com/spring-cloud/spring-cloud-netflix .

**Comment by qiangdavidliu** [comment]
Closing old issue. Please re-open if necessary.
