### ISSUE TITLE
disable load balancing?

### ISSUE THREAD

**Issue by magg** [Netflix/eureka#906]
Hello

Is there a way to disable load balancing?

I have a setup where I have an Eureka server, one grpc client microservice (1 AMI) and two grpc servers microservices ( so 2 AMIs). The case in general would having one client and N servers and having eureka provide service discovery. 

I want to hit both servers with the client. But Eureka load balances the request, if I do one request it hits one then the other.

thanks!
- Miguel

**Comment by qiangdavidliu** [comment]
@magg how are you using loadbalancing? Most native uses of eureka uses the getInstances() -> List api which is not opinionated on loadbalancing.

**Comment by qiangdavidliu** [comment]
Closing old issue. Please re-open if necessary.
