### ISSUE TITLE
Overriding status does not replicate to other Eureka servers

### ISSUE THREAD

**Issue by mherlund** [Netflix/eureka#908]
When running multiple Eureka servers and setting them up as replicas, overridden status messages made to one of the servers does not get replicated to the other servers.

For instance, when setting `PUT /eureka/v2/apps/appID/instanceID/status?value=OUT_OF_SERVICE` on one server, the other Eureka server still shows a status of **UP**.

Should the overriddenstatus value be replicated to all Eureka servers, or would the override need to be sent to all instances?

eureka version 1.4.12

**Comment by qiangdavidliu** [comment]
@mherlund eureka server replication protocol by default does replicate status overrides to all peers. Is this something you saw regularly, or a one off? Thanks.
