### ISSUE TITLE
GraceTime property for Eureka client?

### ISSUE THREAD

**Issue by derTobsch** [Netflix/eureka#909]
I did not found anything about a grace time property when a client should wait until it calls for the first time a eureka server. 

Is there such a property?

**Comment by qiangdavidliu** [comment]
@derTobsch do you mean for registration or data fetch?
For registration, rather than grace time, we prefer to control the registration state via eureka status.
For data fetch, we actually want to ensure that data is loaded in to the client at constructor time.

Thanks.

**Comment by qiangdavidliu** [comment]
Closing old issue. Please reopen is necessary.
