### ISSUE TITLE
Does eureka has a function to unregister a service which is not available(in java application)

### ISSUE THREAD

**Issue by LXChild** [Netflix/eureka#911]
as the title

**Comment by qiangdavidliu** [comment]
@LXChild the java client contains a shutdown method that unregisters. This internally translates to an unregister REST call (https://github.com/Netflix/eureka/wiki/Eureka-REST-operations).

**Comment by LXChild** [comment]
Thank for reply me, as you say, i saw this line in the page: "Following are the REST operations available for non-java applications to use Eureka."it says in non-java application, any thing wrong?



发自我的小米手机
在 David Liu <notifications@github.com>，2017年3月17日 上午1:52写道：

@LXChild<https://github.com/LXChild> the java client contains a shutdown method that unregisters. This internally translates to an unregister REST call (https://github.com/Netflix/eureka/wiki/Eureka-REST-operations).

**Comment by qiangdavidliu** [comment]
Closing old issue. Please reopen is necessary.
