### ISSUE TITLE
RAM ressources limitation

### ISSUE THREAD

**Issue by applelight** [Netflix/eureka#912]
Hi, 

I would like to limit the amount of RAM used by Catalina in Eureka container. I would like to know if there is any limitation (on the "aggressive") side I should consider as a minimum amount of RAM so the container would start without any issues.

I was not able to find any ressources utilisation guideline.

Regards,

P.S: Sorry for my poor english writing.

I would like to change:
CATALINA_OPTS="$CATALINA_OPTS -Xmx1024m"

to

CATALINA_OPTS="$CATALINA_OPTS -Xmx512m"

Same for CPU time... Is there any limit (on the low side) I shouldn't cross ?

**Comment by qiangdavidliu** [comment]
@applelight eureka server's resource requirements do ramp up as the number of connected clients in your environment increases, so it is hard to give you a good low limit. In practice, we've used EC2 m3.xlarge in smaller testing environments. These are 4cpu instances. For memory, I would recommend try to have a couple of GB.

**Comment by applelight** [comment]
Thank you for the answer, on my side, I was able (in a small testing env.) to set RAM and CPU to 1GB ans 1 CPU utilisation without any problem. Just under that seem`s to be problematic. 

Thank you again.
