### ISSUE TITLE
Confirmation on Eureka behaviour about the API level detail

### ISSUE THREAD

**Issue by haripalpatil** [Netflix/eureka#913]
Hello
We have a situation where we wanted to use Eureka service registry and discovery. We are able to use the service discovery and we can able to get the service instance host name detail with following code taken from Spring.io

This will return us host detail for the given service but we would like to know what different REST API expose by that service and how we can call that REST API using service registry reference dynamically. Please let us know if any mechanism to find individual REST API from service registry and call those REST API.

@Component
class DiscoveryClientExample implements CommandLineRunner {

    @Autowired
    private DiscoveryClient discoveryClient;

    @Override
    public void run(String... strings) throws Exception {
        discoveryClient.getInstances("photo-service").forEach((ServiceInstance s) -> {
            System.out.println(ToStringBuilder.reflectionToString(s));
        });
        discoveryClient.getInstances("bookmark-service").forEach((ServiceInstance s) -> {
            System.out.println(ToStringBuilder.reflectionToString(s));
        });
    }
}

**Comment by spencergibb** [comment]
If you are using spring-cloud-netflix, that is the right place to ask questions. Eureka has metadata you could use, but generally, if you ask for "photo-service", your client should know how to use it.

**Comment by haripalpatil** [comment]
Thanks,
We are trying to use  Netflix Eureka as a service registry to register our services on Pivotal Cloud Foundry. Not sure which is correct place to ask this question.

Yes agree Eureka has metadata information but it does not expose the REST API level detail for individual service in metadata. 
It contain detail such as "registrar_uri", "instanceId", "zone" etc those are mostly the service registry detail and not the service level detail.

The 'photo-service' is just an example. Yes client should be aware of the service but just looking for option to dynamically identify the service API from registry and call the API, if possible.

**Comment by spencergibb** [comment]
>  to dynamically identify the service API from registry and call the API, if possible.
I don't think eureka is the right thing for that.

**Comment by haripalpatil** [comment]
Thanks Spencer for confirmation !!

Hi All - Request to please update here, if anyone is aware of any other way/tool to dynamically call API other than eureka on PCF, or else will close this issue in few days. Thanks all in advance.
