### ISSUE TITLE
Enable/Disable instance API question

### ISSUE THREAD

**Issue by kirillsablin** [Netflix/eureka#915]
Hello,
Could you please explain next situation:

Consider sequence of api calls 

PUT /eureka/v2/apps/appname/instanceid/status?value=OUT_OF_SERVICE - to temporary remove service out of service

DELETE /eureka/v2/apps/appname/instanceid/status?value=OUT_OF_SERVICE - to remove previous override

Will next heartbeat put instance into UP status? Or delete request should contain value=UP to make it happen?  
PUT /eureka/v2/apps/appname/instanceid?status=UP&lastDirtyTimestamp=... - heartbeat 

Thank you for your time!

**Comment by qiangdavidliu** [comment]
Hi @kirillsablin , the next heartbeat will put the instance into either UP or DOWN, depending on what the registered healthcheck to the eureka-client is (if none, it should be UP).
