### ISSUE TITLE
HTTP is harcoded in serviceUrl Creation with DNS

### ISSUE THREAD

**Issue by erdog** [Netflix/eureka#916]
Hi,

I'm setting up Eureka replication with HTTPS. I currently have it working by setting the defaultZone equal to  all of the eureka instances (https://peer1.local:8761/eureka,https://peer2.local:8761/eureka). However, this is not what I want. I want to use the DNS TXT record discovery of other Eureka instances, so i don't have to hard code the machine hostnames. Configured like this, Eureka finds the IP addresses from DNS, but it creates service urls with plain http, not https. This is causing the discovery not to work.

Looking at the code, I see that http is hardcoded in the service url creation. I believe this means that you can only use https, if you hardcode other eureka instances in the defaultZone property.

https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/endpoint/EndpointUtils.java#L148

Is there a way to override this, or does this need to be implemented?

Thanks!

**Comment by qiangdavidliu** [comment]
HI @erdog looks like a code level fix is necessary here to enable https. We welcome any PRs for updates.
