### ISSUE TITLE
Using Eureka service as Service discovery in Pivotal cloud foundry web services

### ISSUE THREAD

**Issue by pktippa** [Netflix/eureka#918]
I have a free account on Pivotal cloud foundry web services(PWS). I am trying to use Eureka service discovery provided in marketplace. I am able to start the service and able to bind the apps to the service and get the service details in VCAP_SERVICES env variable of apps.

VCAP_SERVICES: '{"p-service-registry":[{\n  "credentials": {\n    "uri": "https://eureka-cdb95aee-5332-4a30-b92c-b18a81141719.cfapps.io",\n    "client_secret": "STHux3jxcItf",\n    "client_id": "p-service-registry-403161c8-5ca7-492f-ba0c-b6a3e4ec7bf7",\n    "access_token_uri": "https://p-spring-cloud-services.uaa.run.pivotal.io/oauth/token"\n  },\n  "syslog_drain_url": null,\n  "volume_mounts": [\n\n  ],\n  "label": "p-service-registry",\n  "provider": null,\n  "plan": "standard",\n  "name": "service-registry",\n  "tags": [\n    "eureka",\n    "discovery",\n    "registry",\n    "spring-cloud"\n  ]\n}]}'

Able to get the authentication token by running the below command as given in https://docs.cloudfoundry.org/api/uaa/#client-credentials-grant

curl -k -X POST -H "application/json" -H 'Content-Type: application/x-www-form-urlencoded' --data "grant_type=client_credentials&client_secret=STHu3jxOcItf&client_id=p-service-registry-403161c8-5ca7-492f-ba0c-b6a3e4ec7bf7&response_type=token" https://p-spring-cloud-services.uaa.run.pivotal.io/oauth/token

After getting the access token when I request the Service discovery api’s given in https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

It is giving me 404 for all the API’s.

**Comment by qiangdavidliu** [comment]
@pktippa for spring cloud packaging of eureka, please ask questions at https://github.com/spring-cloud/spring-cloud-netflix

**Comment by mgddp** [comment]
@pktippa Where you able to get any solution to this ?

**Comment by aasthasmile** [comment]
I am stuck at the same point. Eureka Server is registered on Pivotal Cloud Foundry and services are registered there but I am not able to find services in the client using @DiscoveryClient from Cloud services. If you were able to solve this issue ,please mention a version of your solution??
