### ISSUE TITLE
Is there a way to implement the eureka-client in Java EE?

### ISSUE THREAD

**Issue by realrudi** [Netflix/eureka#919]
Hello there

After including the eureka-client dependency in my maven/javaEE project I'm not able to deploy it anymore because of several CDI Exceptions.

Does anyone have any experience in writing a JavaEE-Eureka-Client without Spring usage (deployment is on payara 4.1)?

Best regards
Erik

**Comment by KonradEichstaedt** [comment]
Hi Erik, 

yes we did this several times. Using Google to produce the client like this: 

 @Produces
  public EurekaClient getEurekaClient() {
    if (client == null) {
      synchronized (lock) {
        if (client == null) {
          Injector injector =
              Guice.createInjector(Modules.override(new EurekaModule()).with(new AbstractModule() {

                /*
                 * Overriding the default inject because using the lokal Config instead of AWS
                 * Config
                 */

                @Override
                protected void configure() {

                  bind(EurekaInstanceConfig.class)
                      .toProvider(MyDataCenterInstanceConfigProvider.class).in(Scopes.SINGLETON);

                  bind(EurekaClientConfig.class).toProvider(DefaultEurekaClientConfigProvider.class)
                      .in(Scopes.SINGLETON);

                  // this is the self instanceInfo used for registration purposes
                  bind(InstanceInfo.class).toProvider(EurekaConfigBasedInstanceInfoProvider.class)
                      .in(Scopes.SINGLETON);

                  bind(EurekaClient.class).to(DiscoveryClient.class).in(Scopes.SINGLETON);

                }
              }));

          client = injector.getInstance(EurekaClient.class);
          ApplicationInfoManager.getInstance().setInstanceStatus(InstanceStatus.UP);
        }
      }
    }

    return client;

  }

**Comment by KonradEichstaedt** [comment]
you need this dependencies: 

<dependency>
			<groupId>com.google.inject</groupId>
			<artifactId>guice</artifactId>
			<version>4.1.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>21.0</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
		</dependency>

		<dependency>
			<groupId>com.netflix.eureka</groupId>
			<artifactId>eureka-client</artifactId>
			<version>1.6.2</version>
		</dependency>

**Comment by m-a-l-p** [comment]
Hi,

I have the same case. I need to implement a EurekaClient for our JAX-RS rest endpoints. I'm assuming that this is how i would be able to do it as well, is that right?
May I know why Guice is needed? is it the one that would handle the maintenance/lifecyle of the EurekaClient singleton? What about netflix.governator?
Is there a need to handle the shutting down of EurekaClient singleton anywhere in the jersey?

By the way, i tried this and i got a warning that ApplicationInfoManager.getInstance() is already deprecated and the javadocs suggests to use DI.

Many thanks,
Toni
