### ISSUE TITLE
Feature Request: Client support for multiple applications registering from 1 process

### ISSUE THREAD

**Issue by elad-regev** [Netflix/eureka#92]
I would like Eureka to support multiple services hosted within the same JVM,
which would allow the eureka-client to register all of them instead of the current 1 app per process model (The singleton design prevents me from creating multiple DiscoveryClients in the same JVM).

I would like to know if others may require such feature, in order to decide how to proceed with bridging this gap.

Thanks,
Elad.

**Comment by brenuart** [comment]
This may now be possible thanks to the DI-refactoring work introduced in recent versions. You may still be stuck by the following issue though: https://github.com/Netflix/eureka/issues/554

**Comment by cforce** [comment]
Is there an example how code looks like to do that multi register?

**Comment by qiangdavidliu** [comment]
Issue #554 have been addressed, so it is now possible to create multiple instances of DiscoveryClient (with their own configs) and achieve multiple registration from the same process. Note that to do this the server would have to not use Guice to create the clients.

**Comment by nekperu15739** [comment]
Could you please give it a sample, thanks
