### ISSUE TITLE
DiscoveryClientHealthTest is failing in a host with single CPU

### ISSUE THREAD

**Issue by ekesken** [Netflix/eureka#921]
Because of a race condition. This assert:

https://github.com/netflix/eureka/tree/64e5e2ee97c6036d9a2f447bada79d643c985fb6/eureka-client/src/test/java/com/netflix/discovery/DiscoveryClientHealthTest.java#L72

fails, because this thread:

https://github.com/netflix/eureka/tree/64e5e2ee97c6036d9a2f447bada79d643c985fb6/eureka-client/src/main/java/com/netflix/discovery/InstanceInfoReplicator.java#L47

triggers this change:

https://github.com/netflix/eureka/tree/64e5e2ee97c6036d9a2f447bada79d643c985fb6/eureka-client/src/main/java/com/netflix/appinfo/ApplicationInfoManager.java#L213

which causes overriding of the mock value for hostname which is set here:

https://github.com/netflix/eureka/tree/64e5e2ee97c6036d9a2f447bada79d643c985fb6/eureka-test-utils/src/main/java/com/netflix/discovery/junit/resource/DiscoveryClientResource.java#L272

this change triggers a status update which changes status from STARTING to UP, which causes test to fail.

If there is a single CPU, "DiscoveryClient-InstanceInfoReplicator-0" thread always (at least in all my trys) running before "main" thread executing the failing assert.

**Comment by qiangdavidliu** [comment]
Thanks for the report @ekesken . We'll take a look into this ...

**Comment by qiangdavidliu** [comment]
Should be fixed in #946
