### ISSUE TITLE
Enable customize discovery client scheduler thread pool

### ISSUE THREAD

**Issue by maximkir** [Netflix/eureka#927]
Today's implementation has a hard coded value of 3. While other 2 executors (heartbeat & cache Refresh) can be customized with properties (client.heartbeat.threadPoolSize & client.cacheRefresh.threadPoolSize). 
I suggest to add another property: client.scheduler.threadPoolSize for client scheduler core size.

**Comment by qiangdavidliu** [comment]
@maximkir looks like the size of 3 for the top level schedule is a legacy of old client needs, and there really only need to be 2 threads (1 for cache refresh, 1 for heartbeat). The InstanceInfoReplicator function used to share the same pool (hence the size of 3) but that now has its own scheduler.

As the actual execution tasks are protected, there should be no need to make the pool size configurable and it should instead be set to 2. Was there some reason you found in your environment that prompted the need to make this pool size configurable? Thanks.

**Comment by maximkir** [comment]
No, I just inspected the tread pools that created by the discovery client and their roles. The fixed value catch my eye with comparison to other pools. 
A comment that explains the fixed value can be nice for future readers.

**Comment by qiangdavidliu** [comment]
Thanks, done.
