### ISSUE TITLE
Best practices for Eureka server upgrades

### ISSUE THREAD

**Issue by jebeaudet** [Netflix/eureka#929]
Hi Netflix,

I'm looking at the best practices to gracefully upgrade Eureka servers without downtime and I have yet to find any information about that. I've ran into issues lately (more on that later) and I want to make sure I'm doing this properly. From my experience, there seems to be 3 ways to update servers (we're using the TXT DNS service urls endpoint resolution and have 2 eureka servers in different zones) : 

### TXT DNS upgrade
I haven't tested this one but I'm guessing it should work. You start by adding a new EIP in the relevant zone's DNS where you're spawning a new Eureka server. You spawn the new server, it grabs the new EIP and eventually, clients will start to send heartbeats to the new server and it will get replication from the old one. 

Once everything is up and running, remove the old EIP from the zone's DNS, wait for propagation and client service urls refreshes and shutdown the old server. This in theory should be without any error logs but a much longer process since you need to wait DNS propagation and service urls refreshes. It is also hard to assert that every client are aware of the new EIP other than checking the logs. You could also potentially have DNS cache problems.

### Side by side upgrade
This is the method we currently use, it involves spawning a new instance with the new version of the server side by side with the old. No modification to the TXT DNS are made. Once the server is up and running and the registry is replicated, the old server is terminated. Its EIP then gets released and grabbed by the new server.

This works but it creates a lot of noise in the logs since for a while (when the old server is shutting down, you get connect timeouts error logs).

### In place upgrade
You shutdown the old server, replace the jar and boot it up again on the same instance. 

This also generates a lot of error logs.

### Conclusion
What is the prefered way to upgrade Eureka servers without downtime and with assurance that no registry sync occur? I'm fine with some error logs if they're necessary from my end.

**Comment by qiangdavidliu** [comment]
Hi @jebeaudet we internally deploy in a way that is a combination of your last two methods. We terminate the older instance without editing the TXT records (running sub-par) and bring up a new instance that assumes the vacated EIP once it is up.

This does generate some connection logs on the other eureka servers (clients have additional logic to mitigate even this) but eureka is designed to be resilient to running sub-par.

Please do note that we run a lot more than 2 servers internally. I would recommend at least 3 so when you are deploying, you are never down to just a single live server.

**Comment by jebeaudet** [comment]
Thanks for the quick feedback @qiangdavidliu, this is valuable information to me and many others that will end up here with a google search, I could not find any information about upgrades anywhere. Thanks again!
