### ISSUE TITLE
Veracode Testing identifies Insufficient Entropy issue in eureka client jar

### ISSUE THREAD

**Issue by jbaurchn** [Netflix/eureka#932]
Veracode has identified 2 issues in the following classes  in eureka-client-1.4.12.jar

ResolverUtils.java 96
SessionedEurekaHttpClient.java 92

The issue details are as below.

**Insufficient Entropy (CWE ID 331)
**Description**
Standard random number generators do not provide a sufficient amount of entropy when used for security purposes.
Attackers can brute force the output of pseudorandom number generators such as rand().

**Recommendations**
If this random number is used where security is a concern, such as generating a session identifier or cryptographic
key, use a trusted cryptographic random number generator instead.

Can you please help  confirm if this indeed an issue which needs to be fixed in code or a false positive from Veracode. If to be fixed, can you also let us know if there is any timeline for fixing it.

**Comment by qiangdavidliu** [comment]
Hi @jbaurchn thank you for the analysis. The usage here is not for security purposes.
