### ISSUE TITLE
Eureka with ECS

### ISSUE THREAD

**Issue by afilichkin** [Netflix/eureka#937]
Hi,
We are using Eureka with AWS ECS service that can scale docker containers.
In ECS if you leave out the host port, or specify it as being '0', in your task definition, then the port will be chosen automatically and reported back to the service. After the task is running, describing it should show what port(s) it bound to.

How does Eureka can resolve what port to use if we have several EC2 instance. For example Service A from EC2-A try to call Service B from EC2-B. So Eureka can resolve hostname , but cannot identify exposed port

**Comment by afilichkin** [comment]
Let me summarize this stuff.
So, Eureka works fine with AWS ESC if we have static Docker port. We just need expose this port then Eureka can resolve AWS host using AmazonInfo (http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html#_using_eureka_on_aws)

But Eureka doesn’t help you if you want to use ECS autoscalling feature.

Actually, we can use Eureka with ECS(autoscalling) and Docker only with Docker network host (docker run --net=host). But this approach is not good. For Kubernetes it’s OK, because each Docker image is isolated in Pod(some Kubernetes expert mentioned that they are going to remove Eureka, because Kubernetes itself can do all this stuff).

Currently, it’s not possible to run Eureka with ECS if you need dynamic Docker port. Amazon ECS agent doesn’t support it yet( https://github.com/aws/amazon-ecs-agent/issues/151)

**Comment by DirkLachowski** [comment]
We have solved that by enabling the docker rest api on the ecs host. You can then create an introspector that asks the docker daemon on the host for the port mapping and use that info in a custom  Eureka instance config bean.

**Comment by bhanu-singh** [comment]
please read article at https://medium.com/@bhanu.pratap/service-discovery-in-spring-cloud-using-netflix-eureka-in-aws-fargate-2c5c294fee5c

**Comment by gustoliv** [comment]
> We have solved that by enabling the docker rest api on the ecs host. You can then create an introspector that asks the docker daemon on the host for the port mapping and use that info in a custom Eureka instance config bean.

@DirkLachowski can you give an example of this configuration, please?

**Comment by DirkLachowski** [comment]
@gustoliv Sure, unfortunately it's an internal project on our gitlab so i'm unable to make it public. Will try to sketch the idea.

### Enabler annotation

```java
@Retention(value=java.lang.annotation.RetentionPolicy.RUNTIME)
@Target(value={java.lang.annotation.ElementType.TYPE})
@Documented
@Import(EurekaConfig.class)
@Configuration
public @interface EnableDockerRegistration {

}
```

### Eureka Config

```java
@Configuration
public class EurekaConfig {
	
	private final static Log LOG = LogFactory.getLog(EurekaConfig.class);
	
	@Bean
	@Autowired
	// Bean name is important, see https://github.com/spring-cloud/spring-cloud-config/issues/329
	public EurekaInstanceConfigBean eurekaInstanceConfigBean(InetUtils inetUtils) throws UnknownHostException {
		AmazonInfo info = AmazonInfo.Builder.newBuilder().autoBuild("eureka");
		DockerEurekaInstanceConfigBean config = new DockerEurekaInstanceConfigBean(inetUtils);
		config.setDataCenterInfo(info);
		info.getMetadata().put(AmazonInfo.MetaDataKey.publicHostname.getName(), info.get(AmazonInfo.MetaDataKey.localIpv4));
		config.setHostname(info.get(AmazonInfo.MetaDataKey.localHostname));
		config.setIpAddress(info.get(AmazonInfo.MetaDataKey.localIpv4));
		
		ContainerIntrospector introspector = new ContainerIntrospector(info.get(AmazonInfo.MetaDataKey.localIpv4));
		InspectContainerResponse container = introspector.inspect(InetAddress.getLocalHost().getHostName());
		Ports ports = container.getNetworkSettings().getPorts();
		Map<ExposedPort, Binding[]> bindings = ports.getBindings();
		Binding[] binding = bindings.get(new ExposedPort(8080));
		if (binding != null && binding.length > 0) {
			Integer hostPort = binding[0].getHostPort();
			LOG.info("Registering host port: " + hostPort);
			config.setNonSecurePortForced(hostPort);
			config.setInstanceId(info.get(AmazonInfo.MetaDataKey.instanceId) + ":" + hostPort);
		} else {
			throw new IllegalStateException("Unable to get mapped port, exiting...");
		}
		
		return config;
	}
}
````

### Docker config bean

```java

public class DockerEurekaInstanceConfigBean extends EurekaInstanceConfigBean {

	private final static Log LOG = LogFactory.getLog(DockerEurekaInstanceConfigBean.class); 
	
	public DockerEurekaInstanceConfigBean(InetUtils inetUtils) {
		super(inetUtils);
	}

	@Override
	public void setNonSecurePort(int nonSecurePort) {
		LOG.info("Trying to set nonSecurePort to: " + nonSecurePort);
		if (super.getNonSecurePort() == 0) {
			super.setNonSecurePort(nonSecurePort);
		} else {
			LOG.info("Skiped setting nonSecurePort to: " + nonSecurePort + " because it's allready set to: " + super.getNonSecurePort());
		}
	}
	
	
	public void setNonSecurePortForced(int nonSecurePort) {
		super.setNonSecurePort(nonSecurePort);
	}
}
```

## Introspector
```java
public  class ContainerIntrospector {
	private final RestTemplate restTemplate = new RestTemplate();
	private final Log LOG = LogFactory.getLog(getClass());
	private final String instanceAddress;
	
	public ContainerIntrospector(String instanceAddress) {
		LOG.info("Creating container introspector for host: " + instanceAddress);
		this.instanceAddress = instanceAddress;
	}
	
	private String asEndpoint(String entityUri) {
		return "http://" + instanceAddress + ":2375/" + entityUri;
	}
	
	public InspectContainerResponse inspect(String containerId) {
		LOG.info("inspecting container: " + containerId);
		return restTemplate.getForObject(asEndpoint("containers/{id}/json"), InspectContainerResponse.class, containerId);
	}
	
}
```


On top of that you need a bunch of Pojos with json mappings for the docker api responses. We've extracted the relevant part from https://github.com/docker-java/docker-java - we couldn't use it directly because of it's jersey dependency but you should get the idea. Pojos are in https://github.com/docker-java/docker-java/tree/master/src/main/java/com/github/dockerjava/api/model

If you have assembled all that parts using it in a boot-app is  as simple as:

```java

@SpringBootApplication
@ImportResource("classpath:/aws.xml")
@EnableEurekaClient
@EnableDockerRegistration
public class ApplicationBootstrapper {
	
	public static void main(String[] args) {
            SpringApplication.run(ApplicationBootstrapper.class, args);
        }
}

```

One thing you maybe want to change is the id the apps register with. We are creating an `<instanceId>:<docker-port>` id. You can change that quite at the end of the `EurekaConfig` bean.

<img width="1326" alt="Bildschirmfoto 2019-07-17 um 17 07 51" src="https://user-images.githubusercontent.com/226266/61387155-dfdf2180-a8b5-11e9-83d1-6144d2997a35.png">


Feel free to reach out to me by mail if you need further infos.

**Comment by gustoliv** [comment]
@DirkLachowski Thanks a lot man!
