### ISSUE TITLE
set hostname in eureka-client.properties

### ISSUE THREAD

**Issue by realrudi** [Netflix/eureka#938]
Hello

How to set the hostname in the eureka-client.properties file?

This is my current configuration:

`...
<application>
<name>ACR-SERVICE</name>
<instance>
<instanceId>pleven2</instanceId>
<hostName>pleven2</hostName>
<app>ACR-SERVICE</app>
<ipAddr>127.0.1.1</ipAddr>
<status>UP</status>
...`

instanceId and hostname are set tp pleven2, which is the hostname of the server hosting my eureka service.

Here is my 

eureka-client.properties file

`eureka.name=acr-service

eureka.vipAddress=acr

eureka.port=8080
eureka.securePort=8181
eureka.securePort.enabled=true

eureka.hostname=api-v2

eureka.preferSameZone=true
eureka.shouldUseDns=false
eureka.serviceUrl.default=http://api-v2:8080/eureka/v2/
eureka.homePageUrl=https://${eureka.hostname}:${eureka.securePort}/acr-service/v1.0`

So, which setting i have to use to set the hostname and the instancId?

Best Regards
Erik

**Comment by qiangdavidliu** [comment]
@erudisch would you mind clarifying your question? When you say 'hostname', are you referring to the hostname of your registering application (including the eureka client), or the remote eureka server(s)?
