### ISSUE TITLE
how can eureka server cancel  a service when enable enableSelfPreservation

### ISSUE THREAD

**Issue by niuhp** [Netflix/eureka#941]
when set eureka.server.enableSelfPreservation=true to eureka server,and a service is really not available(maybe the network is not available or the service process is killed by someone with [kill -9] or [docker stop]),when the service will be unregistered?????

**Comment by qiangdavidliu** [comment]
@niuhp self preservation mode is only activated when a large percentage of services are potentially expiring at the same time (i.e. in a network partitioned scenario). By default, the configured percentage is 15%. It should not activate for single server expirations. The config to set the percentage is dynamically configurable at run time, so if you do run in to self preservation mode and need to end it for a legitimate reason, you can alway temporarily lower the percentage threshold as required. See https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/DefaultEurekaServerConfig.java#L221
