### ISSUE TITLE
Eureka REST operations 404 issue

### ISSUE THREAD

**Issue by lorgine** [Netflix/eureka#945]
hi man,when i use Eureka REST operations, it reports 404 error,and after trying some times,i remove v2 it is ok, so can you update wiki?
https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

**Comment by qiangdavidliu** [comment]
Hi @lorgine I'm sure if I understand your issue? The documentation for the REST APIs are still accurate.

**Comment by leiy88** [comment]
@qiangdavidliu 
For example:
`Request URL:http://localhost:8761/eureka/apps
Request Method:GET
Status Code:200 
Remote Address:[::1]:8761`

`Request URL:http://localhost:8761/eureka/v2/apps
Request Method:GET
Status Code:404 
Remote Address:[::1]:8761`

**Comment by spencergibb** [comment]
If you are using Spring Cloud, it works without v2

**Comment by kingschan1204** [comment]
mark

**Comment by HaoChou** [comment]
mark

**Comment by cherrishccl** [comment]
mark

**Comment by johnnyflute** [comment]
why spring don't need v2@spencergibb
