### ISSUE TITLE
after 90s ,eureka-server dose not kick off client

### ISSUE THREAD

**Issue by hao0111** [Netflix/eureka#948]
hi,i use spring-cloud with C.version , i  shutdown one of eureka-client service, after 90 seconds,but the eureka-sever console  show the service that has already shutdown!!! whatever i restart eureka-server ,it has the problem same to before,how can i do? please help me,thanks

**Comment by spencergibb** [comment]
This is not the tracker for spring-cloud. https://github.com/spring-cloud/spring-cloud-netflix

**Comment by hao0111** [comment]
sorry,i got it!thank you
