### ISSUE TITLE
Unnecessary checking of isThisMyUrl

### ISSUE THREAD

**Issue by fahimfarookme** [Netflix/eureka#954]
I was debugging some failover scenarios and found that the `if` condition below never becomes true, hence unnecessary.

```
for (final PeerEurekaNode node : peerEurekaNodes.getPeerEurekaNodes()) {
       // If the url represents this host, do not replicate to yourself.
       if (peerEurekaNodes.isThisMyUrl(node.getServiceUrl())) {
            continue;
        }
       replicateInstanceActionsToPeers(action, appName, id, info, newStatus, node);
 }
```

[https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java#L633](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/registry/PeerAwareInstanceRegistryImpl.java#L633)

This is because eureka server never adds itself to peer-node collection. i.e.
[https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java#L140](https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java#L140)

**Comment by thank037** [comment]
#953 Hello @zkwentz

**Comment by qiangdavidliu** [comment]
@fahimfarookme that looks to be the case, thanks. This is likely a legacy of some optimisations elsewhere.
