### ISSUE TITLE
Unable to return status to UP after overridden status was set to OUT_OF_SERVICE

### ISSUE THREAD

**Issue by goatherder** [Netflix/eureka#955]
Hi,

We're having some trouble understanding the expected behaviour with Eureka and the instance overridden status'.  We'd expect to be able to override a status (ie: set it to OUT_OF_SERVICE - eg: via spinnaker) - and then remove this to return the service to it's original status.

However, this doesn't seem to be what happens from a couple of observations (running eureka server 1.6.2 - and various eureka clients...  mostly spring):

Setting the status to OUT_OF_SERVICE manually:  curl -XPUT http://eureka_server:8080/eureka/v2/apps/APP/<id>/status?value=OUT_OF_SERVICE

results in:

status = OUT_OF_SERVICE
overriddenstatus = OUT_OF_SERVICE

(lastDirtyTimestamp is also updated)

Then, removing this status override (as per netflix rest api doc) - curl -v -XDELETE http://eureka_server:8080/eureka/v2/apps/APP/<id>/status

results in:

status = UNKNOWN
overriddenstatus = UNKNOWN

heartbeats continue to come through from the client... which result in a 404 from the server:

INFO  com.netflix.eureka.registry.AbstractInstanceRegistry:363 [http-apr-8080-exec-14] [renew] Instance status UNKNOWN possibly due to deleted override for instance <id>; re-register required

And the instance DOES try to re-register... BUT - it fails due to the lastDirtyTimestamp in the heartbeat being old:

WARN  com.netflix.eureka.registry.AbstractInstanceRegistry:211 [http-apr-8080-exec-23] [register] There is an existing lease and the existing lease's dirty timestamp 1496744179917 is greater than the one that is being registered 1496740143467

So - the service sits forever trying to heartbeat -> re-register (and it gets a 204 response on the re-register by the way).

Is this expected behaviour?  Or is this possibly a configuration issue/client incompatability?

The only way to bring the service back up is to issue a:

curl -v -XDELETE http://eureka_server:8080/eureka/v2/apps/APP/<id>/status?value=OUT_OF_SERVICE

(this is what spinnaker does... I guess it looks at the status vs overridden status?) - but this takes a while - I assume the asg rule eventually brings this up.

Or, to bring the service up immediately, we could also run:

curl -v -XDELETE http://eureka_server:8080/eureka/v2/apps/APP/<id>/status?value=UP

But this all seems to defeat the purpose of an overridden status.  Unless I'm missing something?

Thanks.

**Comment by qiangdavidliu** [comment]
Hi @goatherder this is a bug that was fixed in #984  and released in 1.8.1. It will also be back-ported shortly to the 1.6.x branch.

**Comment by qiangdavidliu** [comment]
In the meantime, using a suggested status value when deleting an override is one way to alleviate the issue.
