### ISSUE TITLE
Documentation: Optimised replication

### ISSUE THREAD

**Issue by Lovett1991** [Netflix/eureka#957]
Is it possible to have the replication events sent as a pool periodically (or delayed on event)? So that a node will not have to receive the same amount of traffic as the primary.

The reason I ask is it would be nice to deploy instances of eureka on very small vm's, I've had a tinker with the eureka client so that it round robins between nodes to split load, but if each node is going to forward the heartbeat immediately then our traffic on the primary node will be the same anyway.

**Comment by Lovett1991** [comment]
After looking through source, I have found that eureka does effectively have a delayed event so updates are grouped before being replicated.

Is it possible to have this documented, as well as what the effects of reducing the number of workers for replication will have?

**Comment by qiangdavidliu** [comment]
@Lovett1991 thanks for the issue, will look to add documentation on batched replication.
