### ISSUE TITLE
Status returns invalid JSON

### ISSUE THREAD

**Issue by Lovett1991** [Netflix/eureka#959]
When calling the Status endpoint the JSON returned is invalid, I believe it is missing the last '}'

Was called with the header: Accept Application/JSON

When called without the header a valid xml is returned.

**Comment by cptstffn** [comment]
https://<eureka-url>/eureka/status
Still returns (with  Accept Application/JSON) HTTP Status: 200 but as body: 
Expected ',' instead of ''

https://<eureka-url>/eureka/apps
instead is able to return the content as a valid json. 

Is number one a misconfiguration from us or a common problem?
