### ISSUE TITLE
Eureka REST operation issues

### ISSUE THREAD

**Issue by wangzanmaoge** [Netflix/eureka#963]
if i want to register new application instance, how to write the json file/xml file?

**Comment by flyhero** [comment]
I wrote it like this：

{
    "instance": {
    	"instanceId":"192.168.0.102:qrcode-service:8990",
        "hostName": "192.168.0.102",
        "app": "QRCODE-SERVICE",
        "vipAddress": "qrcode-service",
        "secureVipAddress": "qrcode-service",
        "ipAddr": "192.168.0.102",
        "status": "UP",
        "port": {"$": "8990", "@enabled": "true"},
        "securePort": {"$": "443", "@enabled": "true"},
        "healthCheckUrl": "http://192.168.0.102:8990/health",
        "statusPageUrl": "http://192.168.0.102:8990/info",
        "homePageUrl": "http://192.168.0.102:8990",
        "dataCenterInfo": {
            "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo", 
            "name": "MyOwn"
        }
    }
}

**Comment by Z-starts** [comment]
@flyhero its error:

{
    "error": "cannot parse request body"
}

**Comment by flyhero** [comment]
you need to change here :  `"securePort": {"$": "443", "@enabled": "false"}`

**Comment by Z-starts** [comment]
`"dataCenterInfo": {
      "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
      "name": "MyOwn"
    }`


and how to add metadata with json. @flyhero

**Comment by junneyang** [comment]
anyone has solved yet? thanks

**Comment by junneyang** [comment]
this works for me
`{
    "instance": {
        "instanceId": "192.168.0.1:plugin-test-aaa-service:80",
        "hostName": "192.168.0.1",
        "app": "plugin-test-aaa-service",
        "ipAddr": "192.168.0.1",
        "vipAddress": "plugin-test-aaa-service",
        "status": "UP",
        "port": {
            "$": 80,
            "@enabled": True,
             
        },
        "securePort": {
            "$": 443,
            "@enabled": False,
             
        },
        "homePageUrl": None,
        "statusPageUrl": "http://192.168.0.1:80/plugin-test/aaa-service/hello",
        "healthCheckUrl": None,
        "dataCenterInfo": {
            "@class": "com.netflix.appinfo.MyDataCenterInfo",
            "name": "MyOwn"
        },
        'leaseInfo': {
            'renewalIntervalInSecs': 15,
            'durationInSecs': 60
        }
    }
}`
