### ISSUE TITLE
Eureka REST operations not available

### ISSUE THREAD

**Issue by jeanabraham** [Netflix/eureka#971]
Hi,

I have the Eureka server running locally. But, none of the eureka URIs are accessible. Trying the HTTP actions on [this page](https://github.com/Netflix/eureka/wiki/Eureka-REST-operations). 

Example:
`GET http://localhost:8761/eureka/v2/apps`

Is there any additional configuration I need to enable? Thanks!

Jean

**Comment by mrcnc** [comment]
Try removing the `v2`

**Comment by tietang** [comment]
GET http://localhost:8761/eureka/apps
