### ISSUE TITLE
EurekaClient getApplication returns null

### ISSUE THREAD

**Issue by raphaelln** [Netflix/eureka#978]
I have 2 eureka servers running at different ports. My service successfully registered on the second eureka. 

As far I know, this is correct, only register and after receives the requests will register in another server instances.

>  "Once the server starts receiving traffic, all of the operations that is performed on the server is replicated to all of the peer nodes that the server knows about. If an operation fails for some reason, the information is reconciled on the next heartbeat that also gets replicated between servers."

And following my application config:
```eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
```

And my external client code returns null.

```
@Autowired
private EurekaClient eurekaClient;
   ....
 final Application application = eurekaClient.getApplication("SERVICE-NAME");
 final InstanceInfo instanceInfo = application.getInstances().get(0);
```

If I change the application config to (replace the order of the eureka servers):

```eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8761/eureka/
```
The client code above works, because the eurekaClient only search for applications of the first configured eureka server.

I've been playing with this for a few hours, wondering if some configuration is invalid. 

Thanks for any help.

**Comment by spencergibb** [comment]
This isn't the issue tracker for spring cloud netflix.

**Comment by qiangdavidliu** [comment]
Closing as this is a spring cloud related issue. As an aside, the scenario described shouldn't occur, unless there is some async replication happening. One possibility for this to occur is mismatched server peer configuration where one server is configured to know about the peer, but the other server is not.
