### ISSUE TITLE
Question: The properties are not grabbed.

### ISSUE THREAD

**Issue by melisoner2006** [Netflix/eureka#980]
Hello, I'm going through the examples under eureka-examples folder and it seems like no matter what I do the eureka-client properties are not being set. My framework is Spark-Java. I already posted my question here:  @https://stackoverflow.com/questions/45921685/how-to-configure-eureka-client-and-service-properties.

Can someone help?
Thanks

**Comment by qiangdavidliu** [comment]
Looks like the question has been address on stackoverflow. Closing this issue. Please reopen if this continues to be an issue.
