### ISSUE TITLE
server in denial of service caused by flooding replication requests from peers

### ISSUE THREAD

**Issue by xiazuojie** [Netflix/eureka#982]
https://github.com/Netflix/eureka/blob/3677ac7d9114e95b051659b7a6d32cc0b8def36e/eureka-core/src/main/java/com/netflix/eureka/cluster/ReplicationTaskProcessor.java#L56

We have an eureka cluster of 8 peers. Under heavy load, peer replication tasks may cause high CPU usage and put peers in denial of service state.

Let's say we have a certain peer named A.
When server A is in high CPU usage and it may fail to respond to replication requests. The other peers will get org.apache.http.conn.ConnectTimeoutException(extends IOException).
isNetworkConnectExceptionserver: the method decides whether it's a network-related issue by checking if it's an IOException. When it's an IOException(TransientError), other peers will retry sending replication request to server A. These retrial tasks will timeout too and be retried indefinitely.
All these retrial tasks leave server A no time to recover and end in denial of service state.

**Comment by skyesx** [comment]
here's a relative pull request #1031

**Comment by qiangdavidliu** [comment]
Linked PR have been merged and should be released soon.
