### ISSUE TITLE
Add application group to instance info

### ISSUE THREAD

**Issue by NiteshKant** [Netflix/eureka#99]
Inside netflix we wish to add a grouping criteria for different application under an umbrella. For this purpose eureka needs to publish the application group which then can be used by other clients to do any logic based on the application group.

The application group can be specified via a property "namespace" + "appGroup" where namespace by default is "eureka." and hence the property eureka.appGroup can be used to specify the application group. Alternatively, in absence of this property, eureka will also look at a java environment property "NETFLIX_APP_GROUP" to infer the application group. The requirement of this environment property is purely due to internal requirements.

**Comment by zhangdc007** [comment]
is the application group just a label to tell apart application ? or the different application group can not find other if they has not permission ?
My requirement is apps in different group and regist in a eureka ,for example ,group A and B，if A has permission to B,then apps in group A  can get  address in app Group B,so A can invoke B' api,if not ,A has no B's app's address,and can not invoke.

**Comment by spurtAndy** [comment]
@zhangdc007 你解决了吗
