### ISSUE TITLE
Eureka-client always returns overridden: UNKNOWN, even though the value is set to something else

### ISSUE THREAD

**Issue by jasollien** [Netflix/eureka#990]
I regularly output this line in my java code from the instance (java eureka-client v1.8.1)

logger.info("overridden: " + ApplicationInfoManager.getInstance().getInfo().getOverriddenStatus().name());

This always prints UNKNOWN.

ApplicationInfoManager.getInstance().getInfo().getStatus().name() however, seems to work as expected

By looking at the JSON data however, this looks fine:

![image](https://user-images.githubusercontent.com/3275463/30854408-cce28dee-a2b1-11e7-811a-3c5987c7a916.png)

I tried attaching your source code, and set a breakpoint in setOverriddenStatus. And here it is always the correct status, except from first time, when it is UNKNWON.

public Builder setOverriddenStatus(InstanceStatus status) {
            result.overriddenstatus = status;
            return this;
        }

**Comment by jasollien** [comment]
I somehow got it working by using: 
DiscoveryManager.getInstance().getLookupService().getInstancesById(instanceInfo.getInstanceId()).get(0).getOverriddenStatus(), but it does not look nice

**Comment by qiangdavidliu** [comment]
@jasollien looks like you have resolved your issue. Closing this issue. Please re open if you need.
