### ISSUE TITLE
API changes report for Eureka Client

### ISSUE THREAD

**Issue by lvc** [Netflix/eureka#995]
Hi,

I'd like to share my results on API changes analysis of the library: https://abi-laboratory.pro/java/tracker/timeline/eureka-client/

The report is generated by the https://github.com/lvc/japi-compliance-checker tool for jars found at http://central.maven.org/maven2/com/netflix/eureka/eureka-client/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![eureka-client-2](https://user-images.githubusercontent.com/1517837/31162706-a551c4b6-a8e7-11e7-8298-e6340547aed1.png)
![eureka-client-1](https://user-images.githubusercontent.com/1517837/31162707-a5539f2a-a8e7-11e7-9474-7243bf250be5.png)

**Comment by qiangdavidliu** [comment]
Hi @lvc Thank you for the information, this look quite interesting. Appreciate the report.
